### ISSUE TITLE
cant add patients in add patients form

### ISSUE THREAD

**Issue by naveen17797** [LibreHealthIO/LibreEHR#1001]
![screenshot from 2018-02-15 20-01-59](https://user-images.githubusercontent.com/18109258/36261666-20c943be-128b-11e8-84ab-f4827d0e9f91.png)

cant add patients, console gives reference error,  i have installed librehealth several times, but this doesnt seems to go.Am i the only one facing this?

**Comment by naveen17797** [comment]
bugs are meant to be fixed  see this [pull request](https://github.com/LibreHealthIO/LibreEHR/pull/1002)

**Comment by teryhill** [comment]
Closing fix is in the code base.
