### ISSUE TITLE
date picker picking up future dates when added manually

### ISSUE THREAD

**Issue by naveen17797** [LibreHealthIO/LibreEHR#1007]
![screenshot from 2018-02-16 09-12-05](https://user-images.githubusercontent.com/18109258/36296040-2d5f15fa-1311-11e8-9ebb-ae3b5a3bf485.png)

**Comment by naveen17797** [comment]
fixed this bug in the below PR
https://github.com/LibreHealthIO/LibreEHR/pull/1006

**Comment by teryhill** [comment]
Pr 1012 which contained this change was merged.
