### ISSUE TITLE
No errors but still no continue button in step-4 

### ISSUE THREAD

**Issue by kamsuri** [LibreHealthIO/LibreEHR#1018]
![image](https://user-images.githubusercontent.com/14004808/36389802-87aa14bc-15c6-11e8-9325-a73ce82bf46f.png)
There are no errors but still i am not getting continue button. Can anyone help me with this?

**Comment by aethelwulffe** [comment]
Hi @kamsuri  Art Eaton here.  Welcome aboard.
I don't use chrome, but this should not be a browser issue.  Any info on your server environment you can share?  As of last weekend, I didn't have any install issues.

**Comment by teryhill** [comment]
@kamsuri Did you try clearing the browser cache?

**Comment by pri2si17-1997** [comment]
@kamsuri This should not happen. Have a look at your logs.

**Comment by kamsuri** [comment]
Thanks @aethelwulffe, @teryhill and @pri2si17-1997 for the suggestions. I solved the issue by clearing cache and also, i used incognito mode.
