### ISSUE TITLE
The style of LibreEHR-master.zip is not the same as Demo.

### ISSUE THREAD

**Issue by miamiroblan** [LibreHealthIO/LibreEHR#1059]
The style of LibreEHR-master.zip is not the same as Demo.
Something is missing in this .zip
I just installed the https://github.com/LibreHealthIO/LibreEHR.git. and looks like the styles files are missing elements.

![untitled-1](https://user-images.githubusercontent.com/37223713/37321945-307d5f8c-2651-11e8-99d6-a0c7fcc72df4.jpg)

**Comment by naveen17797** [comment]
Actually this is due to reason that we have introduced color picker as experimental feature, i am working on this to fix this soon to make color picker stable.

**Comment by naveen17797** [comment]
You can change colors under user preferences> primary color, secondary color

**Comment by naveen17797** [comment]
This would be fixed by the end of this day.

**Comment by teryhill** [comment]
This is a duplicate issue closing

**Comment by aethelwulffe** [comment]
@miamiroblan Link to #1056 for the existing issue tracking, and #1060 where the fix is being implemented.  Thank you for you bug report contribution.
