### ISSUE TITLE
Patient Portal Email Validation Update Required

### ISSUE THREAD

**Issue by amughalbscs16** [LibreHealthIO/LibreEHR#1066]
The function used for validation of email in patient_portal is using a self defined function. I think it should be using the php built in function for checking whether the email is correct or not.
![register function](https://user-images.githubusercontent.com/28474804/37605735-a5fabbd8-2bb5-11e8-87cc-a0abfcbbbd40.PNG)
**Presently implemented Function:**
function validEmail($email)
{
    if (preg_match("/^[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,3})$/i", $email)) {
        return true;
    }

    return false;
}

**The Suggested Update For the Function:**

function validEmail($email)
{
if (filter_var($email, FILTER_VALIDATE_EMAIL)) {
      return true; 
    }
 return false;
}

**Comment by teryhill** [comment]
I like using "Built In" Functions. I think that the current function chokes on a .io site.

**Comment by amughalbscs16** [comment]
So should I make a commit with this new function? If you also agree with it.

**Comment by teryhill** [comment]
Yes send a commit for it.

**Comment by amughalbscs16** [comment]
Here is the pull request I have sent please accept it soon. This function works for .io domain as well I have tested it on that too.
The Pull Request Link
https://github.com/LibreHealthIO/LibreEHR/pull/1067

**Comment by amughalbscs16** [comment]
Solved
