### ISSUE TITLE
Calendar events need to respect clinic hours

### ISSUE THREAD

**Issue by teryhill** [LibreHealthIO/LibreEHR#1071]
The system will and does give an alert that the provider is not available but allows the action anyway. 

If you create an appointment for 1 pm and then change the time to 11 but forget to change the PM to am you now have an appointment set for 11 pm

![image](https://user-images.githubusercontent.com/4655366/37669962-7bb88560-2c3e-11e8-8d7d-500937d88921.png)

The appointment should not be allowed if it is before or after the clinic hours.

![image](https://user-images.githubusercontent.com/4655366/37670112-e006af42-2c3e-11e8-8e05-a56f3be1079a.png)

The AM/PM flag should be set to reflect the clinic open hours.

So the clinic does not end up with this 

![image](https://user-images.githubusercontent.com/4655366/37670210-1f34968e-2c3f-11e8-801d-5b2eaa77a6ba.png)

**Comment by apooravc** [comment]
@teryhill There should be a check for confirming that time selected is within the clinic hours and if not, it should not allow the user to make the appt. and raise an alert saying why. Working on it.

**Comment by teryhill** [comment]
That is correct.

**Comment by aethelwulffe** [comment]
You sure a no-exception policy should be in effect?  Hours can temporarily change.  What happens if someone changes the clinic hours and an existing appointment is outside of those bounds?

**Comment by apooravc** [comment]
@aethelwulffe I think this issue focuses more on the case where a range of clinic hours is given and when an appointment is made, it is checked. For the case you mentioned, if someone changes clinic hours, a script should traverse the DB and appointments out of bounds currently set should be displayed to user, so he/she can change them. Thoughts?

**Comment by teryhill** [comment]
This is getting over thought. It is meant to prevent a user from scheduling an appointment at midnight.

**Comment by aethelwulffe** [comment]
Just doing the devil's advocate thing here.
Terry, please review this first if you can.  We have some...similar PR's here, and I am too way far off in left field to really compare everything right now.  I am just totally wiped for the rest of the month, and 5 of the next 10 days I am out of town...I hate being useless, but there I am.

**Comment by teryhill** [comment]
@aethelwulffe you are NOT useless my friend. I will run the show for you.
