### ISSUE TITLE
Increase readability Creation of a new Patient Code Updation

### ISSUE THREAD

**Issue by amughalbscs16** [LibreHealthIO/LibreEHR#1076]
There is a condition checking for if the result['pid'] is > 1 it should instead pe result['pid'] >= 1 as in the case of there is no patient the 1st value for patient id  = 0; The patient id for the 2nd will be 1 and hence the code seems to be something difficult to understand what. The New code is easy to understand for a new person who is starting to read the code. What do you think @teryhill.
Old code:
function getNewPid()
{
    $result = sqlQuery("select max(pid)+1 as pid from patient_data");
    $newpid = 1;
    if ($result['pid'] > $newpid) {
        $newpid = $result['pid'];
    }
    if ($newpid == null) {
        $newpid = 0;
    }
    return $newpid;
}

New Proposed Code:
function getNewPid()
{
    $result = sqlQuery("select max(pid)+1 as pid from patient_data");
    $newpid = null;
    if ($result['pid'] >= 1) {
        $newpid = $result['pid'];
    }
    if ($newpid == null) {
        $newpid = 0;
    }
    return $newpid;
}
Should I send a commit, if yes please tell so I can do it.

**Comment by teryhill** [comment]
@amughalbscs16  Let me think about it. That code is very old and has worked with no issues that I know of for the 5+ years I have been working with the code. I know that in some instances outside of the patient_data table PID of 0 is valid.

**Comment by amughalbscs16** [comment]
pid = 0 is valid here as well, but the readability is better in the new code, in the start the $newpid is null and it changes as with the conditions. as it took me a bit of time to go through the conditions of old written code. The code should be as fast readable as possible, thats what i am proposing.

**Comment by teryhill** [comment]
Go ahead and send your commit .
