### ISSUE TITLE
Care Coordination (170.314(b))

### ISSUE THREAD

**Issue by tmccormi** [LibreHealthIO/LibreEHR#11]
Replace ZHH feature with one that's part of the core.

**Comment by teryhill** [comment]
I have Sherwin's code that he worked on for his Care Coordination Module. Not sure if it is the same in function. I can send you the demo site info if you want to see his version.

**Comment by aethelwulffe** [comment]
I would like to close this issue and defer it and #324, #12, #13, #14, to a MU project.
