### ISSUE TITLE
Flowboard layout needs to adjust to screen width

### ISSUE THREAD

**Issue by tmccormi** [LibreHealthIO/LibreEHR#118]
Also, per screenshot.  The flowboard layout needs to be 'responsive' and dynamically size to match the frame.... like the rest of the frames do.

![screenshot from 2016-08-23 11 27 13](https://cloud.githubusercontent.com/assets/285835/17979308/c27f9928-6aae-11e6-88be-4df25d93fb51.png)

**Comment by aethelwulffe** [comment]
We have three open issues on the flow-board.  dynamic size, close button, and stomping on tabs (I think).  Should we move all three to a single issue, or can we post a plan of attack?

**Comment by aethelwulffe** [comment]
Is a popup window or a floater, or scaling, or browsertab or anything else an option for the flowb or calendar?  It's one of the few things that are best as horizontal frames.
