### ISSUE TITLE
Adding a tab to globals called Statement

### ISSUE THREAD

**Issue by teryhill** [LibreHealthIO/LibreEHR#125]
I want to add some additional tabs to globals to try and get the items to make more sense as to what they effect. here is one example with out the statement tab.
![tab_example](https://cloud.githubusercontent.com/assets/4655366/17985751/353dcf08-6ae5-11e6-9275-9020ee14316c.PNG)

**Comment by aethelwulffe** [comment]
Haven't you and I been over this a few dozen times already?  Are we ready to try making this a menu instead of restricting everything to top-level tabs?

**Comment by teryhill** [comment]
Dalmatians . even if there is a new menu we still need (IMHO) need to move the Yunk around

**Comment by aethelwulffe** [comment]
Yes.  The Yunk is very Yunky.  I mean, What the Yunk?

Can we just push for a "Financial" tab and get all the stuff that 
billers and managers give a hoot about jammed into it?

It would be great to have sub-menus under that that said "Reporting", 
"Printing" et cetera, but I am sure you will find somewhere to jam it in.

**Comment by aethelwulffe** [comment]
@teryhill 
I just added the encounter reason to the Billing Manager for BPUC.  This is proving to be seriously sloppy-looking and extremely valuable stuff.  The amount of time it saves when checking for non-billable encounters is incredible.  The billing notes print in red, then the reason prints in green, which is the only differentiation between the two, but it seems to be enough.  This is useful in so many ways, It's hard to think of the most important ones.
  I would like to try this out with a branch.  If I enable it as a global option, should we do a separate value, or do some wonky multi-select/radio numeric or non-numeric changes to the existing billing manager options for a Quaternary state?

**Comment by teryhill** [comment]
@aethelwulffe  Send me an E-mail with the info on the encounter reason on the billing manages with the changes and I will start testing it

**Comment by aethelwulffe** [comment]
https://github.com/SunCoastConnection/MI2BPUC/commit/06d998e9c8fba8cfe4c12ec65bb1c1c3657f8c21

Private repo for BPUC.  Just four line differences.
