### ISSUE TITLE
User Credentialing

### ISSUE THREAD

**Issue by aethelwulffe** [LibreHealthIO/LibreEHR#131]
One issue in billing is the common usage of last names of providers being hacked like "Bowen, MD" instead of "Bowen" so that the credentials appear in patient reports and on the encounter summary.  In house, we are using the "valedictory" field in the users table (from the admin address book).  In form_encounter ("NewPatient"...frack, what a name choice), we simply echo this field after lastname to achieve the desired result.  We have not quite gotten around to doing that for the patient report exports.  This seems like a minor thing, but it is a common hack and it commonly causes issues, especially with Medicaid.

**Comment by teryhill** [comment]
Added suffix to the user/address book
