### ISSUE TITLE
TEST SERVERS!

### ISSUE THREAD

**Issue by aethelwulffe** [LibreHealthIO/LibreEHR#135]
I have a free IP or two, and we have a free box.  Is it a good idea to have a cronjob that looks at the repo, checks what branches are available, then pushes a copy of the branch (or some other mysterious magical way) to WWW so that we always have an near-instant demo copy of each live branch running?
  This becomes more and more realistic the more stuff we delete....

**Comment by tmccormi** [comment]
There github plugin that do autodeploy as well.   I like the nightly build, with a clean/reset demo database base each morning...  Brady's "up for grabs" test sites that are branch based are great, but he manually spins them.

We could eventually have the system spin a test site for any pull request.   There would have to be magic migration hooks for database updates ..

**Comment by tmccormi** [comment]
Looks like we can do this wit librehealth gitlab CI and create a couple (or more deployments)
1) Release demo
2) Development tip

**Comment by aethelwulffe** [comment]
I posted something for Robbie to look at, though I am leery of taking full lead on this.  I could do it, but Bryan says I have 4,996 linux configuration tasks to log before he gives me my Unix wings.  Tell me what to do, otherwise I am working on the Windoze package.

**Comment by tmccormi** [comment]
We have a place now, but we don't need test server setup for the Pulbish milestone so I'm removing this from that

**Comment by teryhill** [comment]
@tmccormi @aethelwulffe  can this be closed?

**Comment by aethelwulffe** [comment]
I guess so.  Doesn't seem important to anyone.
After march, I will be asking Bryan if we can dedicate one of our IP's (we have two we are not actually using) and a good big fat chunk of bandwidth to making a pushable test server pack of vm's.
