### ISSUE TITLE
Discussion of better users config for "Home" defaults

### ISSUE THREAD

**Issue by tmccormi** [LibreHealthIO/LibreEHR#162]
Which items to open on startup/home and which tabs should be locked by default

Each user would have different needs:
Front Desk might need Calendar/Patient FInder/Messages with Finder locked
Doctor Might want Flowboard and Messages with Flowboard locked
etc..

**Comment by aethelwulffe** [comment]
The beat-around-the-bush answer is:  How much configuration can we add 
to User Preferences?

Remind me again what is "patient finder"?  Is that  the (originally) 
sidebar search, the dynamic search, or the new/search?

I would say Front Desk (INTAKE) should be Dynamic Search, Calendar 
(probably also Flowboard with all providers) and Pre-Billing Issues 
(once it is tweaked to not show [OLD] insurance data errors)

reception (SCHEDULER) should be similar to the above, but no flowboard.

Billing (CHECKOUT) should be Flowboard, possibly appt-enc report, and 
Billing Manager.

providers (CLINICIAN...please, not Physician, nor Doctor) should be 
Flowboard.

All should have messages with an indicator, but not locked open.

**Comment by tmccormi** [comment]
by finder I mean: main/finder/dynamic_finder.php
Which on the old menu is called "Patient->Patients"

The other search that used to be at the bottom of the menu is gone (but not deleted I think)

**Comment by tmccormi** [comment]
One thing we need, from having used this, is attention to tabs that should always be able to be stepped on and possibly a user configurable limit to the number of open tabs...

**Comment by tmccormi** [comment]
Lots of my customers have different roles for low and mid levels (which they call Clinicians) from the providers that are Physicians (or acting, PA, NP)

**Comment by aethelwulffe** [comment]
On my plate:  "unstomp" all menu items.  Then stomp some of them.  I will assign each feature a "code", then post the codes as a map so we have all the items in some sort of view so they can be re-assigned to a single code.  Currently, I have no idea of what UI's may need to have a forced stomp.

**Comment by tmccormi** [comment]
This might be helpful ...
http://www.jsoneditoronline.org/

**Comment by aethelwulffe** [comment]
Nice.
Gotta hit the appointment bit first though.  Maybe the user thing as well....

**Comment by tmccormi** [comment]
Apparently the OpenEMR 'Home' button that would take you back to default login screen was lost in the new tabs menu stuff.

**Comment by aethelwulffe** [comment]
Yeah.  Thinking of a little logo button to replace it.

**Comment by tmccormi** [comment]
I thought of a great button to add to the title bar  "CLOSE ALL TABS"...  @aethelwulffe

**Comment by tmccormi** [comment]
Need to split this up into actionable issues.  Tagging as a discussion issue

**Comment by teryhill** [comment]
@tmccormi , @aethelwulffe  is this still being discussed or can it be closed?
