### ISSUE TITLE
Documentation Required for the Menu Builder in LibreEHR

### ISSUE THREAD

**Issue by teryhill** [LibreHealthIO/LibreEHR#17]
A document needs to be written for the menu tool.

**Comment by aethelwulffe** [comment]
I will attempt to add a menu item to the system following the post in the code comments I saw.  I will document that process as best I can.  After that point, I need to come up with some plan to write a tool that addresses adding menu items.  Then I suppose we can see if it is possible to get that tool built in 10 days.

**Comment by tmccormi** [comment]
This issue is not on the release milestone list.  It does not need to exist in 10 days.   It's a new feature for the next release.

**Comment by teryhill** [comment]
What's on the milestone list?
I missed that discussion

**Comment by tmccormi** [comment]
Check the Github issues Milestone list...  If it's on the release milestone it's listed.   Take additional discussion on that to the list group not on the issue comments please :-)

**Comment by aethelwulffe** [comment]
So we feel that this is not a required factor for release?  Very well.  I would at least propose that the documentation for adding a new menu item, or using a tool (I have heard rumored) to create the menu from an existing left_nav get done by August.  There is always the option to switch back to frames to get to your extra menu items.
  I can understand the point of it being a future item, because frankly, the left_nav isn't really all that amenable to users anyway.  I still think it is a very good one for milestone 2.

**Comment by tmccormi** [comment]
see #3

**Comment by tmccormi** [comment]
That's funny.  left_nav is not even amenable to programmers :-)

**Comment by aethelwulffe** [comment]
Ja, Ja, but after 11 years, it seems reasonable.  Kinda like living with an 11 year-old.

**Comment by tmccormi** [comment]
see #172 as a step in the right direction.  This also allows the menu to be different on a per site basis with the same code base.

**Comment by tmccormi** [comment]
So ..  planning on adding this tool to allow easy editing and rearranging menu items:  
https://github.com/josdejong/jsoneditor 

Just the minimum needed + the PHP/HTML to load the file and save it.

A  ../../../library/js/jsoneditor/LICENSE
A  ../../../library/js/jsoneditor/NOTICE
A  ../../../library/js/jsoneditor/img/jsoneditor-icons.svg
A  ../../../library/js/jsoneditor/jsoneditor.map
A  ../../../library/js/jsoneditor/jsoneditor.min.css
A  ../../../library/js/jsoneditor/jsoneditor.min.js

Here's what it looks like with default CSS

![jsonmenueditor](https://cloud.githubusercontent.com/assets/285835/21283563/68ee3360-c3b9-11e6-8e3a-2fbcf48828bd.png)

Full editing of the file including drag and drop sections and JSON Validation

Which asks the question .. should I put the tool in the library/js for reuse it in other TREE based dev that could become JSON format ... or put it in the interface/main/tabs/js directory with the MENU specific stuff?

**Comment by tmccormi** [comment]
see pull #334

**Comment by tmccormi** [comment]
pull #334 merged, which helps but still need a good description of what the fields all mean.
