### ISSUE TITLE
CSS error list

### ISSUE THREAD

**Issue by aethelwulffe** [LibreHealthIO/LibreEHR#196]
Expected color but found 'none'.  Error in parsing value for 'background-color'.  Declaration dropped.style_light.css:1007:20
Unknown property 'speak'.  Declaration dropped.typicons.min.css:1:368
Unknown property 'font-smoothing'.  Declaration dropped.typicons.min.css:1:521
Error in parsing value for 'cursor'.  Declaration dropped.ajax_calendar.css:17:29
Error in parsing value for 'cursor'.  Declaration dropped.ajax_calendar.css:138:29
Unknown property 'zoom'.  Declaration dropped.demo_table.css:36:5
Expected declaration but found '_'.  Skipped to next declaration.demo_table.css:82:1
Expected declaration but found '_'.  Skipped to next declaration.demo_table.css:157:1
Expected declaration but found '_'.  Skipped to next declaration.demo_table.css:267:1
Unknown property '-moz-border-radius'.  Declaration dropped.demo_table.css:332:19
Expected declaration but found '_'.  Skipped to next declaration.demo_table.css:336:1

**Comment by pri2si17-1997** [comment]
Hello @aethelwulffe, can you please tell the steps to reproduce this?

**Comment by aethelwulffe** [comment]
I think you got them.
