### ISSUE TITLE
Create Release Notes 1.0.0

### ISSUE THREAD

**Issue by tmccormi** [LibreHealthIO/LibreEHR#200]
A full list of changes summarized in one line for each major thing, posted on the wiki page

**Comment by tmccormi** [comment]
Vote: should this be in the Documentation directory?

**Comment by aethelwulffe** [comment]
Release notes for 1.0.0 relative to WHAT?
  Not that I don't approve of the concept, but what is the delta vs. x?

**Comment by tmccormi** [comment]
A point.  Relative to the point we forked from OpenEMR is what I as thinking, but I could go without if that is the consensus

**Comment by aethelwulffe** [comment]
But we pulled it off of a fork...Hmmmm.  I suppose there is a commit history.  A Loooong history.

**Comment by aethelwulffe** [comment]
That is exactly 100 pull commits.
