### ISSUE TITLE
Database still silently failing to install some tables

### ISSUE THREAD

**Issue by tmccormi** [LibreHealthIO/LibreEHR#209]
This is on the new ehr.librehealth.io deployment.   The display wierdness is also evident here.
![ehr librehealth io](https://cloud.githubusercontent.com/assets/285835/18764379/04355150-80c6-11e6-8f48-c31c936fe936.png)

**Comment by tmccormi** [comment]
This is a 16.04 ubuntu, mysql  Ver 14.14 Distrib 5.7.15, for Linux (x86_64) using  EditLine wrapper

**Comment by tmccormi** [comment]
I'm going to dump it and do a clean install in case Robby did something wrong, but he installed from development_101, so it should have been good.

**Comment by teryhill** [comment]
I am going to send a commit backing out the change for layout style

**Comment by tmccormi** [comment]
Sorry, that made no difference at all on the ehr.librehealth.io site.

**Comment by teryhill** [comment]
just for kicks go into globals and change the concurrent layout save and see if that changes things

**Comment by aethelwulffe** [comment]
Wait a minute:  Is this issue due to tables not existing?  I can verify that in the last master I built the windows install from, that table certainly gets created.  Looking at it now.
That does not mean that the database on the demo got loaded fully/properly.  It very well may be that the time-outs and query limits caused the install to break (silent is still bad) but the database >does< have good queries.

**Comment by tmccormi** [comment]
I just reinstalled and re-ran setup and the table did not get created.  
* Table 'libreehr.libreehr_postcalendar_events' doesn't exist

**Comment by aethelwulffe** [comment]
Running master (As it is) tables get created.  Running from the layout options and INNODB database changes, that branch loads everything AND the menu looks right.  Still has the "modules" and "external" piece, and doesn't have that do_action stuff, but it is good otherwise.

**Comment by aethelwulffe** [comment]
Just restored the dem_layout_options branch to diff off of.

**Comment by tmccormi** [comment]
This is the list of tables that silently failed to be created.
> `batchcom`
> `drug_inventory`
> `drugs`
> `amendments`
> `amendments_history`
> `log_comment_encrypt`
> `patient_tracker`
> `patient_tracker_element`
> `insurance_data`
> `libreehr_postcalendar_events`

**Comment by tmccormi** [comment]
I think this is a mysql version/setup difference on the new server, but needs to be figured out

**Comment by teryhill** [comment]
What version is mysql?

**Comment by tmccormi** [comment]
I was pretty sure we fixed all of these:   but here's what I'm getting, as an example.

mysql> source postcalendar_event.sql;
Query OK, 0 rows affected, 1 warning (0.00 sec)

ERROR 1067 (42000): Invalid default value for 'pc_eventDate'

**Comment by tmccormi** [comment]
`pc_eventDate` date NOT NULL default '0000-00-00',

**Comment by tmccormi** [comment]
development_101 and master database.sql are the same (expect for Terry's ICD10) so if this leaked back in it was a while ago.

**Comment by tmccormi** [comment]
mysql Ver 14.14 Distrib 5.7.15, for Linux (x86_64) using EditLine wrapper @teryhill

**Comment by tmccormi** [comment]
should I just have robby turn strict mode off?  (I'd prefer to just fix these)

**Comment by tmccormi** [comment]
Might be able to just put
`set sql_mode='TRADITIONAL'; `
at the top of database.sql

I'm going to try that.

**Comment by tmccormi** [comment]
That was backwards ...
`set sql_mode='';

Working now.  We can address this after the release.

**Comment by tmccormi** [comment]
@teryhill  did your latest merge fix all know issues here?

**Comment by teryhill** [comment]
I need to do some more testing
