### ISSUE TITLE
CHART NOTES

### ISSUE THREAD

**Issue by aethelwulffe** [LibreHealthIO/LibreEHR#215]
There has recently been some discussion toward dropping the nasty clunky dated old "pnotes".

It is true that this little feature is as bad as it could be, however, from this a basic concept is apparent.
The calendar-driven encounter-based documentation system is too tied to the whole workflow.

For example:  Patient misses appointment.  Though most people don't seem to understand that marking the appointment as "NO SHOW" is a permanent record, they often either want, or actually need to provide further documentation, such as;
- Patient missed appointment because they are in the hospital.
- Patient didn't show because their last med change has left them too sick to drive.
- Patient called to see if it was OK to start tapering off of his prescribed spinach portions.  Said it was OK to reduce from alt. h. to alt. hor.

Putting this into an encounter is hell on the billers.  They look into the billing manager, and there this unbillable thing sits forever.  In a paper chart, you do not fill in a routing slip for a phone call.  You use a "CHART NOTE".

The pnotes suck.  You have the option of choosing "Chart Note", but the implementation just stinks.

I propose a new documentation type.  In the main patient menu, right above or under "Encounter", add a link to a form called "Chart Note".  I think the use of this would be pretty intuitive.
In function:
- Chart Notes should be about who, when, and how, but not where.  It doesn't have a "TO:" component.  It is just part of the patient's chart.
- They should not ever be something that a biller should ever worry about.
- They should be displayed as prominently as the PNOTES are right now, and appear in the encounter/documents history list...but NOT be form_encounter.
- They must be part of demographics-level patient reporting for export or CCD/CCR.

A related feature is a check box in either the encounter form, or perhaps in the billing manager that supports the logic of "This encounter is not billable, make it never ever show up in the billing manager ever again unless I specifically choose "show unbillable encounters".

**Comment by tmccormi** [comment]
The term Chart is confusing, to most of my customers that means medical records.   I agree in general that the ability to enter a running log of notes related to the patient, but not necessarily to an encounter is needed.  I also agree that the pnotes implementation is poor.    I personally use a web tool called "Google Keep" that has just the right amount of ease of use.  Not suggesting we use that, just that it's a better model for note keeping.

I would call it "Patent Notes" still, but the don't need "categories".  We could use Ken's tags though and make the searchable by tags.   I would use doctables (like the patient finder) as the note browser

**Comment by aethelwulffe** [comment]
I am pretty sure the term chart note is a technical term, means "medical record annotation", is not confusing to clinicians (very intuitive), and is exactly the application I am talking about.  This is NOT a messaging tool.  It is an annotation in a medical record.  The difference between a chart note and an intervention (encounter) is that there is no facility involved.   That means you can't bill it.  It is still part of the linear consultation/intervention history.
  I discussed this with several medical language specialists (they all retire here) including my mother-in-law.  Seriously, it isn't good to disagree with her.  All the same, if a combined total of 130 years transcibing notes isn't enough, we should get some clinician opinions from a wide variety of sources.  Terminolgy is paramount.

In any case, I feel the important issue is visibility of the option to NOT use the encounter form.  Tags are another very good idea.  I would be interested in seeing the note example you are talking about.
  Another issue/case is related to structured date.  My thinking is that the tags system will provide enough structure options, leaving only the narrative.  Even so, I think that making the "official annotation in the permanent medical record file" form...by whatever name, readily extensible so that any template can be used would be a good thing.

**Comment by tmccormi** [comment]
This is the note taking tool in List Mode, there is also a Tile View mode.   

![googlekeep-example](https://cloud.githubusercontent.com/assets/285835/18883382/d8811cbc-8497-11e6-9f5d-fbc4552c8412.png)

**Comment by aethelwulffe** [comment]
Yes, general idea.

There is a tendency in "modern" UI's to insist on excessive 
white-space.  In a data correlation environment (think spreadsheet etc), 
this is not a real good thing.  Sure, it looks pretty, if your eye 
muscles can move around that much, but I think we need something that 
condenses and expands readily (and not too greedy with territory).  By 
time you have 20 or thirty notes on something, you need to be able to 
see a list of titles or the first sentence to be able to dive into what 
you need. Organization by tag is great, but they will be looking for 
chronology...and I think this needs to display along with encounter and 
document history...which could also use a face-lift, but not at the 
expense of seeing less data.  The levels of difference in how the data 
is displayed should be thematic choices, and not wired into the code.

My guess is that it may all come down to tags.  Not to say "make a 
general note, then tag it as chart note, billing note, addendum, or 
dated reminder".  I think that the menu selection should drive what the 
user wants, not "do a general thing, then brand it".  All the same, on 
the back end, it COULD be all the same thing, just with tags applied 
contextually, and arguments (parameters, attributes) sent to the form 
via the menu for what we see.

With a single uber-abstract model, we could replace (as I count) about 9 
different separate applications with one new clean chunk.

**Comment by teryhill** [comment]
add a billing notes table. Set a type of "encounter", "Patient", "Chart" etc then display them in the specified areas in the order they were entered or reverse order them.
Just my two cents

**Comment by tmccormi** [comment]
"There is a tendency in "modern" UI's to insist on excessive white-space."  I totally agree with that.
What I like is the simple format for entering a note with tagging if desired, bullet/checkboxes as a option and not much else for editing, then archive, delete, and make reminder.

**Comment by aethelwulffe** [comment]
Agreed.  All functions should be available within the code.  It should, 
in this oh-so-serious format, be pretty damn utilitarian depending on 
your choice of theme.  The note should be VERY simple, and look the same 
all over the place.  There /should be plenty /of additional functions 
available, maybe at all times, but the context you pick out of the menu 
should pre-select the commonly desired features for that context.  This 
simplifies input, as well as keeps the user on-track.

   I'd like more amplification of the previous post.  Sounds like you 
have a firm idea, but I am not following it.  I do agree it is damn 
stupid to have things like "billing note" as a single static item in the 
patient_data table.  We need to pare that beast down, if for no other 
reason.

As for calling it "billing note", I dunno.  I think we need something 
more generic, but at the same time quite identifiable. Getting rid of 
tables named things like "notes" or "lists" is high on my desirability 
list...provided we are touching that code anyway.

**Comment by teryhill** [comment]
Billing notes is just the term for lack of a better descriptor. Table name is up for grabs, my point is mainly the consolidation of those items to a specific table as opposed to having them floating all over the place in multiple tables with redundant or similar field names.

**Comment by teryhill** [comment]
My main thought is there is currently no way to tell what the old notes were or really who changed them. So if you have an encounter note that says "applied to patient ded" and some one removes it that info is gone.

**Comment by aethelwulffe** [comment]
Pass the Gravy and the Ammunition.  That's what I think.  We can kill a 
lot of rats if we just get the right cat.

**Comment by aethelwulffe** [comment]
Yeah, that system is trying to act as a messaging thingie.  It fails to 
achieve anything at all.

If it is passed to a chart note, then that is PERMANENT.  You should be 
able to write an addendum, but the users should be stuck with whatever 
is written and approved.  Tying it into a system where you can delete 
the messages, or you have a specific addressee is contraindicated for 
this application.

**Comment by tmccormi** [comment]
Actually, Slack (or the open source version:Rocket Chat) UI for notes/conversations also a good design, maybe better.   It's around conversations, but it's not threaded so it's really just searchable, taggable sequential notes.

![slack-notes-example](https://cloud.githubusercontent.com/assets/285835/18887619/ab29dc74-84a9-11e6-927e-252511a832be.png)

**Comment by teryhill** [comment]
sounds like this is multiple issues in the same topic.

**Comment by aethelwulffe** [comment]
Killing this topic and posting the enhancement towards new message system with assignment, task list etc..
