### ISSUE TITLE
Changing to demographics thru billing screen not working.

### ISSUE THREAD

**Issue by teryhill** [LibreHealthIO/LibreEHR#216]
If you try to go to the encounter or demographic screen from billing it does not work

**Comment by tmccormi** [comment]
Are you working on this one, or looking for help?

**Comment by teryhill** [comment]
Help

**Comment by tmccormi** [comment]
What does the error log say?  What about the JavaScript console in firebug?

**Comment by teryhill** [comment]
It just does not go anywhere , try it. as soon as I get off the support calls I have lined up I will look futher if no one else has.

**Comment by aethelwulffe** [comment]
I am occupied for the next hour, but will see what I can hit after that.

Was this running off of the build I posted last night?

Were tags involved?

**Comment by teryhill** [comment]
yes last nights build. The other guys are having the same problem. Fresh install

**Comment by teryhill** [comment]
A quick look says it is having a problem with the frames code for opening the new windows. Billing_report.php lines 159 and 173 uncaught ref

**Comment by aethelwulffe** [comment]
First slow-down today, pushed a commit to Libre from some other stuff I had to do today, so I will look into this until I get an alert about helping with a demo tomorrow.  Any other progress?

**Comment by teryhill** [comment]
Nothing other than my last entry. Also there is a bug in that the screens will not autologoff. Have not made an issue for that one.

**Comment by tmccormi** [comment]
Auto logoff was fixed on OpenEMR... any progress on this otherwise?

**Comment by teryhill** [comment]
I know where it problem is I just need to figure out the solution

**Comment by aethelwulffe** [comment]
Bump.
