### ISSUE TITLE
Roll Version number for Patches

### ISSUE THREAD

**Issue by tmccormi** [LibreHealthIO/LibreEHR#225]
update version.php for "real Patch" to 1

**Comment by tmccormi** [comment]
We have two patches.  We should check this in as the last thing before we release the patch and distro.

**Comment by aethelwulffe** [comment]
Should we call them something other than patches?  Then we never have to worry about having too many patches.  Maybe "Badges" or perhaps Enhancements or Accents.  Maybe we should refer to them as "LibreBling".
  Perhaps calling them Age Spots would be too accurate.

**Comment by aethelwulffe** [comment]
Added branch Version-Roll that can be used to accommodate additional changes needed for the release.

**Comment by tmccormi** [comment]
Why?   It's easy for me to check out the file on the master, edit and push... for that.  Not a good practice to keep a branch floating around. In my opinion.

**Comment by tmccormi** [comment]
I'm pushing the latest commits.  Please test and let me know if all is well with the master branch and I'll roll the patch version.

**Comment by aethelwulffe** [comment]
So did you roll that patch?

**Comment by tmccormi** [comment]
We have not done any patches to the master in a long time, probably need to revisit this issue and our policy for patches at this point.

**Comment by tmccormi** [comment]
This is also part of the #91 migration and setup model
