### ISSUE TITLE
62 copies of jquery

### ISSUE THREAD

**Issue by aethelwulffe** [LibreHealthIO/LibreEHR#233]
This is a little excessive.  Also, many of the versions at older than 10 years, and about 8 of the versions are not called in any code anywere.

**Comment by aethelwulffe** [comment]
jquery.1.3.2 produces a lot of warnings and errors.  Upgrading it removes a great number of those.

**Comment by teryhill** [comment]
Would be good to consolidate them in one place.

**Comment by aethelwulffe** [comment]
I have a great number consolidated into a single version/file.  The UI versions and custom versions...well that is another matter.  I will have to hunt down new versions of those, or see about replacing the components if needed.

**Comment by aethelwulffe** [comment]
#291 is the new squash branch.

**Comment by aethelwulffe** [comment]
Testing task list.  Each item in this list should be verified and tested by someone other than me ('cause I have as best I can.)
ZEND stuff, eRX.php, the TAGS stuff, the contrib dupe check (not on this list), fax, as well as some items like AMC tracking have not been tested due to them either being impractical to test for me, not working in the first place (most common), or totally obsolete in any case.
Updating this list will progress this issue in terms of % complete.  This is a good feature, and we should make use of it instead of sticking to one tiny item per issue...at least for testing.
- [ ] interface\billing\billing_process.php
- [ ] interface\billing\billing_report.php
- [ ] interface\billing\edih_view.php
- [ ] interface\billing\edit_payment.php
- [ ] interface\billing\era_payments.php
- [ ] interface\billing\indigent_patients_report.php
- [ ] interface\billing\new_payment.php
- [ ] interface\billing\search_payments.php
- [ ] interface\billing\sl_receipts_report.php
- [ ] interface\clickmap\template\general_new.html
- [ ] interface\code_systems\dataloads_ajax.php
- [ ] interface\fax\fax_dispatch.php
- [ ] interface\forms\aftercare_plan\new.php
- [ ] interface\forms\annotate_diagram\mapdiagram\template\annotate_new.html
- [ ] interface\forms\annotate_diagram\selectnew.php
- [ ] interface\forms\fee_sheet\review\initialize_review.php
- [ ] interface\forms\LBF\new.php
- [ ] interface\forms\note\new.php
- [ ] interface\forms\note\print.php
- [ ] interface\forms\note\view.php
- [ ] interface\forms\patient_encounter\common.php
- [ ] interface\forms\track_anything\history.php
- [ ] interface\forms\transfer_summary\new.php
- [ ] interface\forms\treatment_plan\new.php
- [ ] interface\forms\vitals\templates\vitals\general_new.html
- [ ] interface\login\login.php
- [ ] interface\logview\erx_logview.php
- [ ] interface\logview\logview.php
- [ ] interface\main\authorizations\authorizations.php
- [ ] interface\main\calendar\modules\PostCalendar\pntemplates\default\user\ajax_search.html
- [ ] interface\main\calendar\modules\PostCalendar\pntemplates\default\views\day_print\ajax_template.html
- [ ] interface\main\calendar\modules\PostCalendar\pntemplates\default\views\day_print\outlook_ajax_template.html
- [ ] interface\main\calendar\modules\PostCalendar\pntemplates\default\views\month_print\ajax_template.html
- [ ] interface\main\calendar\modules\PostCalendar\pntemplates\default\views\month_print\outlook_ajax_template.html
- [ ] interface\main\calendar\modules\PostCalendar\pntemplates\default\views\week_print\ajax_template.html
- [ ] interface\main\calendar\modules\PostCalendar\pntemplates\default\views\week_print\outlook_ajax_template.html
- [ ] interface\main\calendar\modules\PostCalendar\pntemplates\default\views\header.html
- [ ] interface\main\calendar\add_edit_event.php
- [ ] interface\main\calendar\find_appt_popup.php
- [ ] interface\main\calendar\find_patient.php
- [ ] interface\main\calendar\find_patient_popup.php
- [ ] interface\main\dated_reminders\dated_reminders_add.php
- [ ] interface\main\dated_reminders\dated_reminders_log.php
- [ ] interface\main\finder\dynamic_finder.php
- [ ] interface\main\finder\patient_select.php
- [ ] interface\main\messages\messages.php
- [ ] interface\main\tabs\main.php
- [ ] interface\main\display_documents.php
- [ ] interface\main\left_nav.php
- [ ] interface\main\main_screen.php
- [ ] interface\modules\zend_modules\module\Carecoordination\view\layout\mapper.phtml
- [ ] interface\modules\zend_modules\module\Carecoordination\view\layout\setup.phtml
- [ ] interface\new\new_comprehensive.php
- [ ] interface\new\new_search_popup.php
- [ ] interface\orders\lab_exchange.php
- [ ] interface\orders\patient_match_dialog.php
- [ ] interface\orders\pending_followup.php
- [ ] interface\orders\pending_orders.php
- [ ] interface\orders\procedure_provider_edit.php
- [ ] interface\orders\types.php
- [ ] interface\orders\types_edit.php
- [ ] interface\patient_file\encounter\coding.php
- [ ] interface\patient_file\encounter\delete_form.php
- [ ] interface\patient_file\encounter\forms.php
- [ ] interface\patient_file\encounter\search_code.php
- [ ] interface\patient_file\encounter\trend_form.php
- [ ] interface\patient_file\history\encounters.php
- [ ] interface\patient_file\history\history.php
- [ ] interface\patient_file\history\history_full.php
- [ ] interface\patient_file\reminder\active_reminder_popup.php
- [ ] interface\patient_file\reminder\clinical_reminders.php
- [ ] interface\patient_file\reminder\patient_reminders.php
- [ ] interface\patient_file\report\custom_report.php
- [ ] interface\patient_file\report\patient_report.php
- [ ] interface\patient_file\rules\patient_data.php
- [ ] interface\patient_file\summary\add_edit_amendments.php
- [ ] interface\patient_file\summary\advancedirectives.php
- [ ] interface\patient_file\summary\create_portallogin.php
- [ ] interface\patient_file\summary\demographics.php
- [ ] interface\patient_file\summary\demographics_full.php
- [ ] interface\patient_file\summary\disclosure_full.php
- [ ] interface\patient_file\summary\immunizations.php
- [ ] interface\patient_file\summary\labdata.php
- [ ] interface\patient_file\summary\list_amendments.php
- [ ] interface\patient_file\summary\pnotes.php
- [ ] interface\patient_file\summary\pnotes_full.php
- [ ] interface\patient_file\summary\pnotes_full_add.php
- [ ] interface\patient_file\summary\print_amendments.php
- [ ] interface\patient_file\summary\stats_full.php
- [ ] interface\patient_file\transaction\add_transaction.php
- [ ] interface\patient_file\transaction\record_request.php
- [ ] interface\patient_file\transaction\transactions.php
- [ ] interface\patient_file\education.php
- [ ] interface\patient_file\front_payment.php
- [ ] interface\patient_file\letter.php
- [ ] interface\patient_file\pos_checkout.php
- [ ] interface\patient_file\printed_fee_sheet.php
- [ ] interface\patient_tracker\patient_tracker.php
- [ ] interface\patient_tracker\patient_tracker_status.php
- [ ] interface\practice\ins_search.php
- [ ] interface\reports\amc_tracking.php
- [ ] interface\reports\appointments_report.php
- [ ] interface\reports\appt_encounter_report.php
- [ ] interface\reports\audit_log_tamper_report.php
- [ ] interface\reports\background_services.php
- [ ] interface\reports\cdr_log.php
- [ ] interface\reports\chart_location_activity.php
- [ ] interface\reports\clinical_reports.php
- [ ] interface\reports\collections_report.php
- [ ] interface\reports\cqm.php
- [ ] interface\reports\custom_report_range.php
- [ ] interface\reports\direct_message_log.php
- [ ] interface\reports\edi_270.php
- [ ] interface\reports\edi_271.php
- [ ] interface\reports\encounters_report.php
- [ ] interface\reports\external_data.php
- [ ] interface\reports\front_receipts_report.php
- [ ] interface\reports\immunization_report.php
- [ ] interface\reports\insurance_allocation_report.php
- [ ] interface\reports\inventory_activity.php
- [ ] interface\reports\inventory_list.php
- [ ] interface\reports\inventory_transactions.php
- [ ] interface\reports\ippf_cyp_report.php
- [ ] interface\reports\non_reported.php
- [ ] interface\reports\pat_ledger.php
- [ ] interface\reports\patient_edu_web_lookup.php
- [ ] interface\reports\patient_flow_board_report.php
- [ ] interface\reports\patient_list.php
- [ ] interface\reports\patient_list_creation.php
- [ ] interface\reports\prescriptions_report.php
- [ ] interface\reports\receipts_by_method_report.php
- [ ] interface\reports\referrals_report.php
- [ ] interface\reports\report_results.php
- [ ] interface\reports\sales_by_item.php
- [ ] interface\reports\services_by_category.php
- [ ] interface\reports\svc_code_financial_report.php
- [ ] interface\reports\unique_seen_patients_report.php
- [ ] interface\super\rules\base\template\basic.php
- [ ] interface\super\rules\controllers\edit\template\criteria.php
- [ ] interface\super\edit_globals.php
- [ ] interface\super\edit_layout.php
- [ ] interface\super\edit_list.php
- [ ] interface\super\field_id_popup.php
- [ ] interface\super\show_groups_popup.php
- [ ] interface\super\show_lists_popup.php
- [ ] interface\tags_filters\components\jquery\jquery.min.map
- [ ] interface\tags_filters\vendor\components\jquery\component.json
- [ ] interface\tags_filters\vendor\components\jquery\composer.json
- [ ] interface\tags_filters\vendor\components\jquery\jquery.min.map
- [ ] interface\tags_filters\vendor\components\jquery\package.json
- [ ] interface\tags_filters\vendor\composer\installed.json
- [ ] interface\tags_filters\vendor\robloach\component-installer\tests\ComponentInstaller\Test\Process\RequireJsProcessTest.php
- [ ] interface\tags_filters\vendor\robloach\component-installer\README.md
- [ ] interface\tags_filters\views\forms\patients_tags_form.php
- [ ] interface\tags_filters\views\layouts\filters_layout.php
- [ ] interface\tags_filters\views\layouts\patients_tags_layout.php
- [ ] interface\tags_filters\views\layouts\tags_layout.php
- [ ] interface\tags_filters\composer.json
- [ ] interface\tags_filters\composer.lock
- [ ] interface\usergroup\addrbook_edit.php
- [ ] interface\usergroup\adminacl.php
- [ ] interface\usergroup\facilities.php
- [ ] interface\usergroup\facilities_add.php
- [ ] interface\usergroup\facility_admin.php
- [ ] interface\usergroup\facility_user.php
- [ ] interface\usergroup\facility_user_admin.php
- [ ] interface\usergroup\user_admin.php
- [ ] interface\usergroup\user_info.php
- [ ] interface\usergroup\usergroup_admin.php
- [ ] interface\usergroup\usergroup_admin_add.php
- [ ] interface\eRx.php
- [ ] patients\find_appt_popup_user.php
- [ ] patients\index.php
- [ ] patients\summary_pat_portal.php
- [ ] templates\documents\general_view.html
- [ ] templates\practice_settings\general_list.html
- [ ] templates\prescription\general_edit.html
- [ ] templates\prescription\general_list.html
- [ ] setup.php

**Comment by aethelwulffe** [comment]
Do we mark this one as duplicate, drop, or is there any use in the compiled work-list above?

**Comment by teryhill** [comment]
rerun your stuff. I should have gotten a lot of them with the datepicker upgrade. Hopefully the list will be shorter.

**Comment by aethelwulffe** [comment]
Good.  I will maintain this and check off or delete (if they don't exist anymore).

**Comment by aethelwulffe** [comment]
Snuffing this.
