### ISSUE TITLE
Tags system Color Picker JS missing

### ISSUE THREAD

**Issue by tmccormi** [LibreHealthIO/LibreEHR#241]
When adding a new tag the "color picker is blank", afterwards if you click on 'None' in the color column you get this ...
**Not Found
The requested URL /LibreEHR/interface/tags_filters/javascript; was not found on this server.**

![tag-color-javascript-missing](https://cloud.githubusercontent.com/assets/285835/19532685/ac70f672-95f1-11e6-8b24-7874a548986f.png)

**Comment by tmccormi** [comment]
@kchapple can you take a look at this please - it was a clean install of LibreEHR master branch

**Comment by aethelwulffe** [comment]
Status?

**Comment by tmccormi** [comment]
Pull #336 fixed the color selector
