### ISSUE TITLE
Some Frames need be configuration to Close on Select

### ISSUE THREAD

**Issue by tmccormi** [LibreHealthIO/LibreEHR#242]
Frames like the Patient Finder and Globals should close themselves after you take the end-action (like selection of the patient or "Save".

This probably could be configurable but maybe not necessary.

**Comment by aethelwulffe** [comment]
I think configurable.  If the patient finder disappears after diving 
into each record as someone is reviewing them, I would get strangled 
within minutes.  Globals is arguable.

**Comment by aethelwulffe** [comment]
Updating this.  This is related to #531 as well.

**Comment by yehster** [comment]
Tabs can also "unlock" rather than close.  So then you could click back over to the results. Again, the default behavior of locking all existing tabs isn't ideal. The thing is, in the "old top/bottom model" you did in fact lose the finder search result when you clicked on a patient.

**Comment by teryhill** [comment]
Is this still an active issue?

**Comment by aethelwulffe** [comment]
Globals probably should NOT close after saving, as people may be hitting the save button as they go through each tab.  An alert "Settings Saved" that fades after a second would be a nice feature...so maybe this is still valid.
