### ISSUE TITLE
Create configuration tools for dynamic menu management

### ISSUE THREAD

**Issue by tmccormi** [LibreHealthIO/LibreEHR#3]
Construct more configuration tools for menus, making decisions about the JSON vs. DB approaches for the frameless configuration.

**Comment by tmccormi** [comment]
This issue IS on the miles stone list and is intended to just cover the basics, like documentation new structure

**Comment by aethelwulffe** [comment]
Document the new structure...and if we happen to get a little further along...

**Comment by TonyArra** [comment]
Why not use a properly formatted .json file?

**Comment by teryhill** [comment]
Any help you have to offer will be appreciated

**Comment by aethelwulffe** [comment]
json string sure (and hey, while we are at it, might as well format it properly, right?), but stored in the db.  The database should be the application instance, not the database plus some fiddly extra configured files that make it all work.

**Comment by TonyArra** [comment]
Well, at the point that you're storing it as a JSON document in the database (AFAIK, MySQL now supports a JSON data type, but hasn't implemented a super-efficient JSONB storage type like PostgreSQL yet), you might as well go all out and store it as a tree in its own table. I'm assuming that the issue here is how to make it configurable by the user, so I guess if it's stored in the database it'll require a GUI for editing. Storing it as  .JSON file, however, would allow the user to simply edit the file in a readable format.

**Comment by teryhill** [comment]
Sounds like a plan.

**Comment by aethelwulffe** [comment]
Can we assign this to you?  :package:

**Comment by TonyArra** [comment]
Sure, was just looking into the code behind this. Didn't realize that the JSON is already being used to seed a menu_tree table.

**Comment by aethelwulffe** [comment]
Well it would be absolutely awesome if we could get a JSON warrior to hit some of this.
I have personally been hoping to include a directory parser for the interface/reports directory added into the mix.  Having someone take this to the point where there was a functioning configuration UI of *any* kind would be a major leap forward.
Got any styling buddies?

**Comment by tmccormi** [comment]
what about these options:
https://github.com/josdejong/jsoneditor - JSON Editor is a web-based tool to view, edit, format, and validate JSON. It has various modes such as a tree editor, a code editor, and a plain text editor.

There are several similar projects, but this one is active and was updated 5 days ago.

**Comment by teryhill** [comment]
it looks to me like @TonyArra Is willing to take this on

**Comment by tmccormi** [comment]
How soon? :-)

**Comment by tmccormi** [comment]
This looks dang simple to do...  https://github.com/josdejong/jsoneditor/blob/master/docs/usage.md

**Comment by TonyArra** [comment]
I'm starting a branch for it on my fork; was thinking of doing a tree-editor for the database table and bypassing the JSON altogether if possible. Also trying to see if a friend of mine who's into design is interested in the project.

**Comment by tmccormi** [comment]
All for whatever the volunteer thinks is the best model!

**Comment by tmccormi** [comment]
A decent tree editor could be used to upgrade the document category management as well ....

**Comment by aethelwulffe** [comment]
Desperately.
  Frankly, I would like to start using the same tool to handle all menus everywhere.

**Comment by aethelwulffe** [comment]
@TonyArra   Hi Tony, putting out a poke for the week.  Got a link to that branch?

**Comment by tmccormi** [comment]
see pull #334

**Comment by tmccormi** [comment]
Done
