### ISSUE TITLE
Unable to save Demog Changes (edit mode)

### ISSUE THREAD

**Issue by tmccormi** [LibreHealthIO/LibreEHR#300]
New install of development_101 on ubuntu 14.04 from source.

SAVE button unresponsive.  I think the javascript section is not loading fully now or something.  JS not my forte as you all know.

![unable-to-save-demochanges](https://cloud.githubusercontent.com/assets/285835/21120134/b1bcc198-c07a-11e6-898f-d5687ae0f4b2.png)

**Comment by teryhill** [comment]
Do you have a PHP log entry?

**Comment by tmccormi** [comment]
No it's not a PHP error.  But I think I got it.  Some JS code was badly commented out and I "fixed" it. but I typoed the fix.   

I have fixed it now ....

**Comment by aethelwulffe** [comment]
Uh, sorry, but line 116 of demographics_full should read:

`var mypcc = "<?php echo $GLOBALS['phone_country_code']; ?>";`
It needs that semicolon thingie, and I am not so sure of the single quote usage dependability.

**Comment by teryhill** [comment]
got it

**Comment by aethelwulffe** [comment]
```
 <input type='entry' size='20' name='i<?php echo $i?>plan_name' value="<?php echo $result3{"plan_name"} ?>"
 onchange="capitalizeMe(this);" />
```
This also has colonoscopy issues....and I have issues with someone using curly braces in an array...Does that even work?  Also, good practice to put single quotes inside double...not double inside double.  Note the semicolon after the php closing tag.
 `<input type='entry' size='20' name='i<?php echo $i?>plan_name' value="<?php echo $result3{"plan_name"} ?>"`
What is that extra "i" in front of the php tag?
If you want that, I would think to do
```
 name="<?php echo "i{$i}plan_name;?>"
 <?php echo"<input type='entry' size='20' name='i{$i}plan_name' value='{$result3['plan_name']}';?> 
 onchange="capitalizeMe(this);" />"///still something funny here....
```

**Comment by aethelwulffe** [comment]
Tony, my forte is _just a little bit_ forward of the quillions.

**Comment by tmccormi** [comment]
Nice "repost"

**Comment by aethelwulffe** [comment]
When I lay it on, I go to the hilt.
