### ISSUE TITLE
pubpid is causing issues

### ISSUE THREAD

**Issue by aethelwulffe** [LibreHealthIO/LibreEHR#309]
Pubpid is not getting set, at least on my test environment php7 maria.
I recommend a find and replace branch to remove the whole concept from the code base.  How do you guys feel about me doing that?

**Comment by tmccormi** [comment]
PUBPID is used extensively to provide a alternative tracking for ID from external EMR Conversions.   

That said it's very misunderstood and frequently used incorrectly in code.    We need to have a place or two for external IDs, but PUBPID should not be what is displayed when PID is what is meant ((Like on the Active Patient links, Finder, etc ...)

**Comment by aethelwulffe** [comment]
I am down with leaving it in the database, though ID and PID could actually be the same themselves as well.
So, without removing the concept completely and leaving it as an alternate id in addition to insurance numbers, ssn's and all that rot even when it is only useful in a few rare cases for special purposes by certain vendors, we can still correct the usage in the code base.  I will assign myself to this, as I have done just that a number of times in the past already.

**Comment by aethelwulffe** [comment]
#318

**Comment by tmccormi** [comment]
Can this be closed?

**Comment by aethelwulffe** [comment]
Been working for over a month, so I guess so...
