### ISSUE TITLE
Cleanup branches

### ISSUE THREAD

**Issue by tmccormi** [LibreHealthIO/LibreEHR#316]
There are a lot of branches that are dead (merged or abandoned)  I'm going to remove the from the server.
 Please let me know if I should keep any of these.  I've already removed the current pull requests from this list.

git push origin :1500_margins_user_definrd
git push origin :Document-Plugin_PR_169
git push origin :Encounter-Form-Rename
git push origin :External-URL-tab
git push origin :Fixes_to_270_file
git push origin :HEAD -> origin/master
git push origin :Jerrys_preprinted_hcfa
git push origin :Logo-Cleanup
git push origin :Wild_Machete
git push origin :adLDAP_removal
git push origin :add_statement_tab_to_globals
git push origin :annotate_diagram
git push origin :billing_widget_fix
git push origin :cash_receipts_chg
git push origin :clean-up-forms
git push origin :cleanup-issue-110-tdm
git push origin :cleanups_tdm
git push origin :code_cleanup
git push origin :dem-layout-redux
git push origin :drop-deident-scripts-issue-#110
git push origin :edi_270_upto_5010_standard
git push origin :enc_history
git push origin :exclude_from_claim
git push origin :floating_messages_in_demographics
git push origin :freeb_demolition
git push origin :insurance_inactivate_patient
git push origin :issue-97-ptlist
git push origin :issue-99-database-sql
git push origin :issue108upgradeDB/Art
git push origin :issue_36_syntax_bug
git push origin :issue_55_zerodates
git push origin :issue_5_dropphpmyadmin
git push origin :issue_6_dropZEND
git push origin :jquery_upgrade
git push origin :menu-border-hack
git push origin :misc_billing_form_changes
git push origin :navigation_menu_fix
git push origin :new_logo_#114
git push origin :read-json-directly
git push origin :remove_upgrade_utils
git push origin :rename-enh-finder
git push origin :sql_admin_#84
git push origin :syntax-usergroup
git push origin :taxonomy_added_for_caid

**Comment by aethelwulffe** [comment]
Uh...why have these not been deleted?  Actually...I am pretty damn sure 
that I didn't have all these dead branches on my system until 
recently...has the LibreBot or Herobrine been at it around here?

**Comment by tmccormi** [comment]
Naw, just sometimes I forget to check the "delete branch" button after a merge (in Stash it's the default)...

**Comment by tmccormi** [comment]
OK, I'm going to toast this branches now...

**Comment by tmccormi** [comment]
Done
