### ISSUE TITLE
Is there a need to pursue MU compliance

### ISSUE THREAD

**Issue by teryhill** [LibreHealthIO/LibreEHR#324]
Do we work towards this? I agree that there should not be all the bloat that was caused by putting everything in the system. Not being certified greatly limits my client base , unless the government changes things.

We need to look at issues 11 - 14 and determine if they are in fact needed. Or do we just cater to the non US market where MU is not needed.

**Comment by tmccormi** [comment]
I think MU should, at the very least be sidelined in favor of focus on a good core product.   OpenEMR (hopefully) can be the MU offering by any of us that need to do that.    I'm doing that as we speak.

MU is expensive and the current MU2 implementation requires external services that are proprietary ie: #11 #12  #13 #14 

Until we have serious funds I think this is out of reach for LibreHealth EHR

I think we can safely close those as "won't fix" or at least "Long Term Issue"

**Comment by teryhill** [comment]
parts of 12 and 13 will be handled with the new portal . 11 is there I think with sherwins ccm. 14 is a work as you go.

If we want to be MU certified I think we should put the pieces in as we go.

**Comment by tmccormi** [comment]
Anything that truly has a "Meaningful Use" can and should continue moving forward.   I agree that those are things that meet that standard.

**Comment by aethelwulffe** [comment]
Yes...we build a product that can be used meaningfully.
Yes, many of the core ideas in MU2 should be explored...but never ever ever to simply sastisfy a checkbox.  That is the pitiful idiotic mindset of mismanagement that failed to look in to the intent of a standard and do something in an _elegant_ fashion using basic system engineering approaches.  The project management...while I am not intending to be personally insulting...was completely amateur and incompetent.  It needed someone that was capable of looking at government standards and seeing the real product underneath. 
 We have no need to use that "hit the checkbox" idiot approach again.  We are better than that.  You look at the WHOLE standard, you look at the WHOLE set of problems, then you design a WHOLE product performance goal that meets all points.  If there is anything in a standard that simply cannot be weaseled into a quality product...then that becomes a "mod" for nationalization.  
  First item is an adaptable base that provides the minimal usage of an EHR.  I think we are headed that way.  Main point is to work toward meeting the standard, then when you are sure you blow the requirements away and you have a slick way of proving it, THEN you start the process of getting certified.  THAT _is a real_ "industry standard" with meaning.  That is how you get an aircraft certified for flight, an ICD certified for implant, and a car certified for production and sale.  Industry, not hobby.

**Comment by tmccormi** [comment]
Spoken like a real Systems Engineer :-)  good rant

**Comment by aethelwulffe** [comment]
Interim goal:  Start an MU2/3/15/MIPS whatever project...vs. an issue.
LONG TERM GOAL:  Start doing something about it.  Add the functions, and add them well, noting the intended use.
For the U.S., we MUST have whatever certification is required to be a valid product.  We don't have a pathway to that right now, but we CAN work it into our design management.  I suggest we make a project skeleton and close this issue and the related ones.

**Comment by teryhill** [comment]
Don't see any need in keeping this clutter.
