### ISSUE TITLE
Login Logo

### ISSUE THREAD

**Issue by tmccormi** [LibreHealthIO/LibreEHR#325]
The new login script is hard coded for interface/pic/LEHR_logo.png.
There are unused "images" now in sites/*/images like login_logi.gif etc.

previously a user could change the login logo by uploading a replacement to the sites/*/images dir.  This feature has been lost, but the tools to support it are still there.

So ...  Keep the hard coded one or modify it to use the user/vendor changeable model?

I think both ... in the sense the we should have a small LibreHealth EHR shield down in the corner and allow the header graphic to be replaceable.  What about that?

**Comment by tmccormi** [comment]
Maybe something like this?
![nagp-demosite-lehr](https://cloud.githubusercontent.com/assets/285835/21327216/e12171be-c5e2-11e6-92ec-89605d9b4357.png)

**Comment by aethelwulffe** [comment]
Yeah, there used to be TWO logos...the header one (which we have no 
header on the logon page) and the one in the fill, which I suppose we 
are using now.

Main logo configurable by global is nice, with the little powered-by 
logo more difficult to simply replace.

I have actually needed a multilogo login page in the past, and being 
able to drop them in somehow would still be nice for me...thinking if I 
should take this on.  Probably not right now.

**Comment by aethelwulffe** [comment]
Yeah,

dimension checks and the like for the imported file would be good so 
things don't get goofy is another good idea.

**Comment by teryhill** [comment]
Maybe using the LibreHealth logo. like at the top of the forums

**Comment by tmccormi** [comment]
not a bad idea at all.

**Comment by tmccormi** [comment]
#345 pull requested  - The current pull uses the shield, I have a version that uses the LibreHealth version as well.  I can switch them if desired.

![login-shield](https://cloud.githubusercontent.com/assets/285835/22046481/d0793810-dcd5-11e6-9759-bcc15cc916ad.png)

![librehealth-login](https://cloud.githubusercontent.com/assets/285835/22046488/d9eab4aa-dcd5-11e6-868a-9b1b93806bfe.png)
