### ISSUE TITLE
DocumentTree menu gone again

### ISSUE THREAD

**Issue by tmccormi** [LibreHealthIO/LibreEHR#326]
I'm getting this error again on new installs:
GET https://libreehr.vu2vu.com/demo/libreehr/DocumentTreeMenu.js 
controller.php?document&list&patient_id=1015:27 Uncaught ReferenceError: TreeMenu is not defined
    at controller.php?document&list&patient_id=1015:27

They were moved in this commit
24c1ea1 Locate DcoumentTree_Menu.js (#252)
D       CategoryTreeMenu.js
D       DocumentTreeMenu.js
A       library/js/DocumentTreeMenu.js

They code still expects them to be in the root dir as near as I can tell

**Comment by tmccormi** [comment]
This fixes it ... but it's a hack: 
in the EHR root
# sudo ln -s library/js/DocumentTreeMenu.js DocumentTreeMenu.js

**Comment by tmccormi** [comment]
Did I mention how much I hate javascript?   I'm getting a 404 not found on a file that is CLEARLY there...

![whereswaldo](https://cloud.githubusercontent.com/assets/285835/21373592/f0baf0da-c6d4-11e6-9055-6ce39f47c8b9.png)

```
tony@dragonfire:/var/www/LibreEHR/templates/documents$ ls ../../library/js/DocumentTreeMenu.js 
../../library/js/DocumentTreeMenu.js

```

**Comment by tmccormi** [comment]
OK it appears to be fixed.  Pull request coming, please test..

```
index e48ea6d..4f0aba4 100644
--- a/templates/document_categories/general_list.html
+++ b/templates/document_categories/general_list.html
@@ -14,10 +14,10 @@
 </style>
 {/literal}
 <script type="text/javascript">
-var deleteLabel="{xl t="Delete"}";
+var deleteLabel="{xl t='Delete'}";
 </script>
 
-<script type="text/javascript" src="../../library/js/DocumentTreeMenu.js"></script>
+<script type="text/javascript" src="library/js/DocumentTreeMenu.js"></script>
 <table>
        <tr>
                <td height="20" valign="top">{xl t="Document Categories"}</td>
diff --git a/templates/documents/general_list.html b/templates/documents/general_list.html
index 4e61ca5..b13ac49 100644
--- a/templates/documents/general_list.html
+++ b/templates/documents/general_list.html
@@ -7,7 +7,7 @@
 {literal}
 {/literal}
 
-<script src="DocumentTreeMenu.js" language="JavaScript" type="text/javascript"></script>
+<script type="text/javascript" src="library/js/DocumentTreeMenu.js"></script>
 </head>
 <!--<body bgcolor="{$STYLE.BGCOLOR2}">-->
```

**Comment by aethelwulffe** [comment]
YAY!  That is exactly what I was seeing when I was testing the pubpid branch.  I thought you said it worked fine for you, so I was only looking for issues with my machine.

**Comment by tmccormi** [comment]
It was working because for some reason the damn js file was still in the root dir, despite my best efforts
