### ISSUE TITLE
Referral report for Transactions fails with SQL 

### ISSUE THREAD

**Issue by tmccormi** [LibreHealthIO/LibreEHR#327]
New referral entered and saved fine.  But when you run the report you get this in development_101 branch

![referral-report-sql](https://cloud.githubusercontent.com/assets/285835/21367038/57695098-c6b1-11e6-9a9a-685e75d3cbb7.png)

**Comment by tmccormi** [comment]
Can someone that a quick look at this?

**Comment by aethelwulffe** [comment]
On it.

**Comment by aethelwulffe** [comment]
That value doesn't exist.
```
DROP TABLE IF EXISTS `transactions`;
CREATE TABLE `transactions` (
  `id`                      bigint(20)   NOT NULL auto_increment,
  `date`                    datetime     default NULL,
  `title`                   varchar(255) NOT NULL DEFAULT '',
  `pid`                     bigint(20)   default NULL,
  `user`                    varchar(255) NOT NULL DEFAULT '',
  `groupname`               varchar(255) NOT NULL DEFAULT '',
  `authorized`              tinyint(4)   default NULL,
  PRIMARY KEY  (`id`),
  KEY `pid` (`pid`)
) ENGINE=InnoDB AUTO_INCREMENT=1 ;
```

**Comment by aethelwulffe** [comment]
Nor does refer_date, body, refer_to or any of those others...

**Comment by aethelwulffe** [comment]
Those are layout_options field ID's
This report is crap.

**Comment by aethelwulffe** [comment]
So is the referral system.

**Comment by tmccormi** [comment]
perhaps the report should just be removed?

**Comment by aethelwulffe** [comment]
Good choice

**Comment by aethelwulffe** [comment]
Rod changed that stuff two years ago, and the report never made it.

**Comment by aethelwulffe** [comment]
https://github.com/LibreHealthIO/LibreEHR/commit/4ea4311875fcb9a7a5db98e109c29167a6e2242a
