### ISSUE TITLE
Date of Birth field accepting Future Dates

### ISSUE THREAD

**Issue by Elgayar** [LibreHealthIO/LibreEHR#338]
When entering a future date, it should prevent that by alerting the user with an error message, however it doesn't and instead it displays the age in negative. Which is meaningless. 

![image](https://cloud.githubusercontent.com/assets/6567844/21679524/50584586-d34d-11e6-96db-adefcb5a71c3.png)

**Comment by nileshprasad137** [comment]
I'll work on this!

**Comment by nileshprasad137** [comment]
please assign this to me , as i am unable to assign this to myself @teryhill @tmccormi

**Comment by tmccormi** [comment]
Done.  have a bit of fun...

**Comment by nileshprasad137** [comment]
@tmccormi Some help needed !
I tried to create a patient but when i click `Create new patient` after entering credentials in `face sheet` , nothing was happening . Do I have to fill all all the details in `contacts`, `privacy` etc to add a new patient?
 Also note that there is no option to select dob from calender like it has in issurance,  Refer screenshots below. 

![dob_issue](https://cloud.githubusercontent.com/assets/16336390/23548174/387143d0-002c-11e7-882a-31db0bf528be.PNG)
![dob_2](https://cloud.githubusercontent.com/assets/16336390/23548309/de935384-002c-11e7-8cc8-8a6802f201d6.PNG)

**Comment by teryhill** [comment]
Name , sex and DOB should be all that is needed to create a new patient

**Comment by nileshprasad137** [comment]
@teryhill was there a datepicker like that of an insurance before ,,in dob fields?

**Comment by teryhill** [comment]
Yes , but now they should be like DOB. 

![image](https://cloud.githubusercontent.com/assets/4655366/23553972/15f99d10-fff1-11e6-91a1-636094a9db18.png)

**Comment by nileshprasad137** [comment]
@teryhill okay , i was on a old version , its getting created now! Sorry for the confusion

**Comment by nileshprasad137** [comment]
@teryhill @tmccormi Have a look at this.
![screenshot 88](https://cloud.githubusercontent.com/assets/16336390/23563298/068a787e-006c-11e7-9b51-c116002f6453.png)

I modified Jquery file of calender and now it cannot accept any future date .
I guess this solves multiple issues  :wink:

**Comment by teryhill** [comment]
What about future dates in appointments and flow board?

**Comment by nileshprasad137** [comment]
oops  :see_no_evil: I'll correct that.

**Comment by teryhill** [comment]
If you could give a option to allow future date on demand that would work.

**Comment by nileshprasad137** [comment]
@teryhill  Or maybe a different jquery calender file for appointments and flowboard though it'll be a bit repetitive.

**Comment by nileshprasad137** [comment]
@teryhill I am a bit stuck up here. Have a look at file [https://github.com/LibreHealthIO/LibreEHR/blob/master/interface/new/new.php](https://github.com/LibreHealthIO/LibreEHR/blob/master/interface/new/new.php)

See the code from line 231 to 239
`<script>
    $(function() {
        $("#DOB, #regdate").datetimepicker({
            timepicker: false,
            format: "<?= $DateFormat; ?>"            
        });
        $.datetimepicker.setLocale('<?= $DateLocale;?>');
    });
</script>`

 I tried to add a line `maxDate:0` for setting up max date to today , but it was not working. And the point to be noted is ** even if you delete this script block , the calender runs fine**, so i think its redundant or something is overriding this script.

Please have a look , and correct me, if I am wrong.

**Comment by teryhill** [comment]
@nileshprasad137  you are correct that code block has no bearing on the DOB . You need to look at options.inc in the \library directory. I have a change to that program that has not been committed to the code base yet so look at PR 467 . The code you are looking for is from line 364-387

**Comment by nileshprasad137** [comment]
@teryhill @tmccormi 
DOB not accepting future dates and flowboard accepting future dates  :simple_smile:

![screenshot 92](https://cloud.githubusercontent.com/assets/16336390/23579354/c5d23faa-0111-11e7-9ed4-39ad3b64ef59.png)

![screenshot 93](https://cloud.githubusercontent.com/assets/16336390/23579353/c5d145dc-0111-11e7-8886-5e95064004c6.png)

Any more possible loopholes or
Issue resolved ?

**Comment by teryhill** [comment]
@nileshprasad137  ?PR#

**Comment by nileshprasad137** [comment]
ok , sending!

**Comment by teryhill** [comment]
@nileshprasad137 Nice clean fix. It also takes care for deceased date.

**Comment by nileshprasad137** [comment]
yes , but unfortunately i did'nt create a new Pull request! I merged that with Master so its coming in that pull request #448 .  :pensive:

I'll not do that mistake again.
Is there a possibility of that getting fixed ? 
Its time for me to work with different branches .

**Comment by teryhill** [comment]
@tmccormi  can you fix this?

**Comment by naveen17797** [comment]
@teryhill  seems this is the issue i have raised in my current PR, they didnt add server side validation.
