### ISSUE TITLE
Download Prescription PDF is not working

### ISSUE THREAD

**Issue by Elgayar** [LibreHealthIO/LibreEHR#339]
When clicking on Download PDF at the Prescription section, nothing happens.

![image](https://cloud.githubusercontent.com/assets/6567844/21679631/baab3d08-d34d-11e6-9679-7d0b6c4ce09a.png)

**Comment by nileshprasad137** [comment]
@teryhill @tmccormi This thing works now! Just check it.

**Comment by teryhill** [comment]
@nileshprasad137 Yes I verified it is working thanks @tmccormi @aethelwulffe  Closing this
