### ISSUE TITLE
Flowboard Appt Status and Appt Status from Widget are not in sync

### ISSUE THREAD

**Issue by tmccormi** [LibreHealthIO/LibreEHR#342]
Apparently the flowboard has it's own field for status and does not share the appt status from the calendar tables directly.

![available-vs-ptincall-diff](https://cloud.githubusercontent.com/assets/285835/21693326/55f2e324-d335-11e6-8ade-d5c446f806fd.png)

**Comment by teryhill** [comment]
The way it was originally done was it used the same file. I have not made a change to look at something else

**Comment by tmccormi** [comment]
Interesting ...  Will dig some more on this.

**Comment by tmccormi** [comment]
In the example the demographics screen is the current status and I watched the flowboard refresh several times without updating....  I was using chrome from linux... I wonder if there is a caching issue?

**Comment by teryhill** [comment]
Yes but if you change it via any thing it was updating

**Comment by tmccormi** [comment]
Which means is separated at the data level.  You are assuming that all changes come via that UI and manual data entry.  We have updates that are automated based on external events...

Perhaps you created a function call that updates both places and we missed that?

**Comment by teryhill** [comment]
manage_tracker_events (I think) should be in the patient_tracker.inc.php file in /library

**Comment by teryhill** [comment]
look at the call in appointments.inc to fetch appointments

**Comment by tmccormi** [comment]
OK.  Looks like this is an issue for the API core code not the base EHR code.  Closing now.  Thanks.
