### ISSUE TITLE
Floating Alert configuration setting in globals are under Billing tab

### ISSUE THREAD

**Issue by tmccormi** [LibreHealthIO/LibreEHR#347]
Alerts for Messages and Allergies are in the billing tab instead of "Features"

![alerts-globlas](https://cloud.githubusercontent.com/assets/285835/22083583/9faaee0c-dd81-11e6-8cb9-3477f7c26697.png)

**Comment by teryhill** [comment]
I have some added some other tabs and will commit that soon
