### ISSUE TITLE
Default Tabs - Clear Patient Action - Tabs reversed

### ISSUE THREAD

**Issue by tmccormi** [LibreHealthIO/LibreEHR#370]
When you do a clear patient the tabs are restored in the opposite order.  That is what was Tab 1, Tab 2  displayed from left to right now displays from right to left Tab 2 first then Tab 1 ...

![reversed-tabs](https://cloud.githubusercontent.com/assets/285835/22441003/73290162-e6ea-11e6-82f7-2ff16295331d.png)

(note: sent email to yehster) ..

**Comment by aethelwulffe** [comment]
Clearly a stack operation...;-)

**Comment by tmccormi** [comment]
From @yehster 

https://github.com/yehster/LibreEHR/commit/56f8326a363322b9c907ae2507136ec97d56cd70
Fixes the ordering.

One of the design choices in the current tab system is "naming" them (lst, pat, enc, fin, etc...) instead of just numbering them so that content consistently goes to specific tabs.  This is important to help differentiate patient specific data (the enc (encounter) and rev (review) so that when switching to a new patient or clearing the patient, it's easier to know exactly which tabs to close...) 

The initial notion behind making 'pat' and 'lst' not closeable was to make sure that if the existing OpenEMR code made reference to the RTop frame, it would be guaranteed to exist, 

Trying to just provide some design context and maybe spur some ideas for the layout. 


Kevin Yeh
6:23 PM (15 minutes ago)

to me 
Oh, and in case you care, here's what was happening...

"lst" is the name for what's normally the first tab, and "pat" is the second.  

If "lst" is closed, then a patient is opened, then the patient cleared, a new "lst" needs to get created, but since "pat" already existed as part of viewing the patient, "lst" is in the list after "pat" hence the positioning of the tabs gets swapped.  The solution was to close "pat" when clearing the patient so both tabs always get recreated and thus they get put back in the correct order. 

I worry a little about opening and closing tabs a lot of times as I'm not sure how well garbage collection of the closed tabs works in this environment, but it's probably ok.

**Comment by tmccormi** [comment]
Done and merged
