### ISSUE TITLE
Add encounter # to the pull down in the title bar

### ISSUE THREAD

**Issue by tmccormi** [LibreHealthIO/LibreEHR#382]
Similar to this code from a customized OpenEMR instance

![encounter](https://cloud.githubusercontent.com/assets/285835/22531957/2924b84e-e899-11e6-8977-4faa65819a71.png)

**Comment by aethelwulffe** [comment]
Recommend format [555555]~2016-01-01:WHATEVER

**Comment by tmccormi** [comment]
ok by me.

**Comment by tmccormi** [comment]
I'm afraid this is above my pay grade.   The code is all Knockout bases JS.   

- main_title.php has a block HTML that  is id="past_encounter"
- patient_data_template.php has something:  I guess related to using Knockout, but means nothing to me 
```
<div data-bind="click: clickEncounterList"><?php echo xlt("Past Encounter List");?>
                        (<span data-bind="text:encounterArray().length"></span>)
                    </div>
```
and patient_data_view_model.js is involved, but I have no clue what a self.id=ko.observable(id) means at all.

This is not a development method that is meaningful to me.

-

**Comment by aethelwulffe** [comment]
View model controllers got you down?  Well stop contracting things out 
to UberGeeks!

**Comment by tmccormi** [comment]
But I wasn't planning on me being the one to work on it :-)

**Comment by aethelwulffe** [comment]
Maintainable code eh?
I'm on it.  I got my knockout tutorial open.

**Comment by tmccormi** [comment]
I'm sure it's perfectly wonderful if you are versed in the "new fangled stuff".

**Comment by teryhill** [comment]
Just making it tough on the rest of us
