### ISSUE TITLE
PFB Change . Customer wants to see checked out items

### ISSUE THREAD

**Issue by teryhill** [LibreHealthIO/LibreEHR#410]
Currently you can set a roll off timer for the checked out items so while the flow board is running they roll off (disappear). This is handy for the normal working of the flow board. This customer wants to go in and periodically check the checked out items bus does not want to go to gloabls to reset the switch. When a status is selected IE checked out then the roll off timer is circumvented.

**Comment by aethelwulffe** [comment]
Looks like a good feature, and is +/- 53.  No lines added!
