### ISSUE TITLE
Glory Road UI

### ISSUE THREAD

**Issue by aethelwulffe** [LibreHealthIO/LibreEHR#420]
Goals:
1.  Optimize vertical space.
2.  Make all toolbar elements fully interactive, minimizing the need for navigation or context labels.
3.  Organize menu cascades and toolbar layout to minimize navigation steps.
4.  Group related toolbar elements for readability and to minimize navigation errors.

![gloryroad](https://cloud.githubusercontent.com/assets/553751/22858255/a9869d74-f085-11e6-9507-6454616183c0.png)

Functions (Left, Right, or Centered display):
[CLEAR] -Clear Active Patient.  Removes patient from the session data.
[RESET VIEW] -Reset to default user view.
[PATIENT NAME and DEMOGRAPHICS FIELD(s)] -Display configured patient name values.  Clicking on any element in this acts as the active patient search, and will display a selection drop-down, obviating the need to go to the full patient search tab.
[LATEST ENCOUNTER] -This field lists the most recent encounter for the active patient.  This field's format is configurable to remove the label text.
[CURRENT ENCOUNTER] -This field (when interfaced) provides the Encounter History dropdown.  If the currently selected encounter is NOT the most recent, the field displays an alert (colorization, "OLD", or whatever is configured as the user preference).
[STATUS] -This is the flowboard status.  It is interactive to allow status updates.  The full status, in the form of a series of small icons or the like could take place of this, changing from red to green as the steps are progressed through.
[TAB MENU ITEMS] -JSON menu items.  The behavior of how many tabs, possibly ordering, and any number of other things related to this should be placed in a user configuration file.
[USER] -Displays user session data.  This also produces the "Preferences, Logout" dropdown.

[TABS] -iframes are resizable, and the tabs follow the frame.

**Comment by teryhill** [comment]
I like it. You want me to add Dr Ray's role based code to it?

**Comment by aethelwulffe** [comment]
WEll, There ain't no code as yet, just this picture, Copyright Art Eaton 2017

**Comment by tmccormi** [comment]
Other that the patient name/data being the "search" button it's OK, 
Thoughts:
Latest should be ACTIVE ENCOUNTER, latest implies most recent but not necessarily the working encounter.

I think CURRENT ENCOUNTER is just confusing, Maybe button called "Enc History"?  what does it open, same as now a single past encounters? or does it open the View History Tab?  
Should we differentiate between finding a single encounter to see/edit/sign for the past on a pick list and choosing to do that from broader view of the encounter history?

RESET View should be on the left under "Clear Patient" 

And we should discuss the location of the "History | Report | Transactions  ..." links should these be active patient menu items instead?   Report is confusing to everyone as well.  It should be "View/Print Medical Record" or something

**Comment by aethelwulffe** [comment]
My thoughts,
In no particular order (perhaps reverse):

The history/report/etc.. stuff should be integrated into the "chart" portion of the menu, yes.  Also totally agree on the "export/view/print" change (without every synonym), because indeed, "Report" confuses the shit out of people.  I like the idea of a button with smaller font that lets you do a two row label like "Print Patient" or "Export Records"something people can relate to "output the darn records to some other media."
I wanted to separate the "Reset" buttons to avoid mis-keying.  It should either be physically separated, or have a "are you sure, are you really really sure" function, which I don't particularly like (but could be better for some people anyway).  This is a documented "Industry Standard" type thing that you find the FAA using, and I am brainwashed to think that way.

I believe that having the search feature right there (and in the spot you interact with the patient chart) is a huge benefit, and we should discuss that.  I feel just as strongly that the behavior should be configurable, so if someone wants a dead menu that does nothing but print stuff on a crowded screen, then should damn well have it.

  Buttons that do not display the data are simply taking up space.  We already have a button you have to click to get a drop-down to compare what encounter you are in, and what encounter you want to be in etc...  The idea here is to make LATEST or "Most Recent" a useful point of data that lets them see when the last visit was.  CURRENT or Active encounter, which is intended to be a "Now viewing Encounter #" information point is to help minimize the buttloads of duplicate encounters that people are making and having to deal with in regular use.  This has always been a big issue.

**Comment by teryhill** [comment]
@aethelwulffe  what happened to your picture ? I no longer see it

**Comment by aethelwulffe** [comment]
503 error.  Times out. dunno what for to do with that.  Looks like there is a server error here.  Can't re-upload it either.  Just tried.

**Comment by azwreith** [comment]
I'd like to start working on this after I'm done with the other issues! :smile:

**Comment by aethelwulffe** [comment]
You already have been working on this.  Effectively, everyone has been.  We should just gather our notions as to what makes the UI better, then implement them as separate deliverables in other issues...referencing back to this one so we can keep a running tally of progress.

**Comment by aethelwulffe** [comment]
My guess is that the "tabs follow iframes" bit would be next, as well as possibly "make tab icons big enough to see".

**Comment by teryhill** [comment]
The screen resizing appears very erratic on firefox on my system, Can some one else check it to make sure it is not just me

**Comment by tmccormi** [comment]
Unclear what commit or issue you are referring to @teryhill .  Current master branch or some pull request being tested.  This thread is a generic discussion issue not at pull or code development issue

**Comment by teryhill** [comment]
@tmccormi Main branch. the resizing of the frames.

**Comment by tmccormi** [comment]
IT's beautiful in Chrome and Firefox on Linux!  nice

**Comment by azwreith** [comment]
@aethelwulffe For the tabs follow frames part, where do you suggest tabs which are unlocked go, cuz their frames will disappear.

**Comment by aethelwulffe** [comment]
@azwreith 
Ujjwal, I am not completely sure what you are asking in terms of "go", or I would gladly give you a simple answer.   Since I am not able to, I would ask that you either make this tabbed UI thing work by a design concept of your choice, or lay out the behavior scheme as you currently understand it, then get input.
  Unlocked tabs were originally intended to mean "don't replace me with another".  We are looking at a new paradigm here, so it may be that the "lock" concept implementation becomes something completely different.
Can you give us a general idea of how **_you_** think the whole interface should work?

General unsolicited advice:
   _I would suggest you use your instinct to determine what you feel the best control with the least user hassle would be, and go with it.  If you come up with an ultimate behavior scheme and want input, post it and we can discuss, but you are doing design work here...not just filling a job order.  This issue post and silly .png file I posted here is a concept...not a blueprint.  Always go beyond the customer's expectations and give them what they NEED, and not what they think they want.  In this case, I am the 'customer'.  If the customer really had the time and ability to figure out a complete standard and work out all the kinks, they would not ask for help.  The customer almost never knows what they are really asking for.  The customer is a bit of an idiot.  Don't waste too much time trying to make a customer's idiot ideas actually work.  Just figure out what the problem really was that started them making idiot noises in the first place (if there really was one), then solve THAT problem with your skills and your opinions;  Your value to the customer is the combination of both, not just one.

  You already understand that the user may need to compare two or more UI views of almost anything.  I am also sure you understand how a tabbed view works, and have some opinions on what a good implementation behaves, and what is not so good.  Your code work has been excellent to this point.  Can you give us some excellent design work as well?_

**Comment by azwreith** [comment]
@aethelwulffe Yep you are absolutely right. I'm sorry for asking to be spoon-fed :sweat_smile: 
Thanks for the great piece of advice there, I'll keep that in mind for sure. I guess till now I was afraid to make a wrong move, that you won't like my ideas, etc. But yuh I guess making mistakes while coming up with your ideas isn't bad when you guys are there to correct me if I'm going in the wrong direction :smile: 

I apologize for not being clear in my above post. I was thinking this sort of UI for the tabs:
![screenshot from 2017-03-13 23-30-15](https://cloud.githubusercontent.com/assets/10354323/23868988/7d3fdd50-0847-11e7-8a2c-30b64e216c00.png)

That is all fine and dandy but I ran into the problem that tabs which get unlocked, i.e replaceable tabs, also have their frames removed from the interface. So I was wondering where to place them because they should be located right on top of their frames, which aren't there. I was thinking we can move all the unlocked tabs to the top like this:
![screenshot from 2017-03-13 23-42-13](https://cloud.githubusercontent.com/assets/10354323/23869145/005f9676-0848-11e7-84a3-4820afc381f5.png)

And then when you click on them:
![screenshot from 2017-03-13 23-42-48](https://cloud.githubusercontent.com/assets/10354323/23869161/0c2d1a82-0848-11e7-8f62-39ca91265160.png)

Though this kind of looks weird, so I was thinking we could have a sidebar of unlocked tabs, or maybe even rethink the entire concept of locking tabs. For example, if 1 or more unlocked tabs are there, one of them HAS to stay open, and then we would keep all the unlocked tab controls next to it, kinda like this (made with paint, mind you):
![screenshot from 2017-03-14 00-02-25](https://cloud.githubusercontent.com/assets/10354323/23869790/43fa9ca8-084a-11e7-9278-da345251ebdb.jpg)

**Comment by aethelwulffe** [comment]
Nobody thinks you, (or any other recent contribs here) have asked to be spoon-fed anything.  You guys have proven you look for your own answers.  The next step was getting you to feel we have confidence in you, and the full weight of your skills and imagination should be brought to bear.
  Personally, I don't think that the "floating" tab looks so bad.  Form must follow function.  I favor keeping the top white space to a minimum, but I would rather have them at the top than taking up a wide side-bar.  I like the second concept of grouped unlocked tabs a lot.

**Comment by azwreith** [comment]
@aethelwulffe I had already made the floating tabs thingy, the group tabs screenshot is an edited one in paint ^^" I can implement it but I'm having my mid terms right now so I can only get to it by start of next week. Also, can you and @teryhill look over my proposal draft timeline? It needs more work but your feedback will be extremely valuable ( ͡° ͜ʖ ͡°)

**Comment by azwreith** [comment]
So I guess next would be moving the user stuff into a single line and adding the latest encounter? c:

**Comment by aethelwulffe** [comment]
Well, the "latest encounter" tells someone the date of the most recent visit.  This is important because the user must have constant reminders that they are not in the most recent visit record.  There is a problem with people adding notes and forms to old encounters.  If the UI is always aware that there is a more recent encounter, the business logic can give warning etc...  With that item displayed, someone, say, doing billing, will also gain some value (difficult to even list all the reasons) from this simple status/reminder poking them in the face.

**Comment by aethelwulffe** [comment]
Hi folks!
Should we leave the Glory Road issue open for reference, or close it now that we have some significant improvements already, and a lot of big design changes coming?

**Comment by teryhill** [comment]
It can always be re-opened if needed.

**Comment by aethelwulffe** [comment]
Cool.  Closing.
