### ISSUE TITLE
customer request for a report showing insurance companies Charges, Adjustments and payments

### ISSUE THREAD

**Issue by teryhill** [LibreHealthIO/LibreEHR#426]
I had a customer request a report like the insurance distribution report but it needs to show Adjustments and payments.

This is the insurance distribution report.

![patient_ins_dist](https://cloud.githubusercontent.com/assets/4655366/23178441/6c1af344-f838-11e6-964d-fc788c49b8a6.PNG)

This is the insurance summary report.

![pat_ins_summary](https://cloud.githubusercontent.com/assets/4655366/23178462/7dc39a24-f838-11e6-8575-a84cf9370faa.PNG)

Keep them both ?

**Comment by tmccormi** [comment]
I see no reason for both

**Comment by teryhill** [comment]
How about the name? Do I just call it the distribution report?

**Comment by aethelwulffe** [comment]
cornfusing crud.  That is all.  makes users ask questions that should 
not be asked.  Think of it as a placeholder that should be used for 
something real.
