### ISSUE TITLE
Customer requested that ordering, referring and a user defined field be added to fee sheet

### ISSUE THREAD

**Issue by teryhill** [LibreHealthIO/LibreEHR#428]
Customer requested that ordering, referring and a user defined field be added to fee sheet. The user wants the user defined field to be a changeable label that they can make their own. They have interns and contractors that they use. The label changing is for different sites one which has the interns and the others use contractors. This field just stays in the encounter form it does not go to HCFA or 837.

**Comment by aethelwulffe** [comment]
Did you get the commit for this in?  I saw the code screenshots, and I would like to add to it

**Comment by teryhill** [comment]
Not yet I have it working and just need to test and make sure I got all the HCFA files done.

**Comment by teryhill** [comment]
@aethelwulffe  just sent a pull request
