### ISSUE TITLE
MIlestone #2 Discussion

### ISSUE THREAD

**Issue by tmccormi** [LibreHealthIO/LibreEHR#43]
Time to talk about the next milestone and what it should have:

**Comment by tmccormi** [comment]
This from Art's most recent pull:

> Need further discussion on upgrades, conversions, patches and all that.

One of the stated goals was to not provide migration path from OpenEMR as native, and sense we need to change the version tracking to back to 1.0 then we should drop all sql_upgrade code and supporting files.   I think we can do better with industry standard 'migration' model instead of the hacked sql file and libraries.

**Comment by aethelwulffe** [comment]
That piece was, for the most part, a way to provide the ability to use an existing database for testing.  It is also useful for very early adoption, but it is very much an interim measure.  The whole database and upgrade model is in fact total poo. 
 I like the idea of dropping all the upgrades immediately.  Going from there, I have no idea on how to proceed.

**Comment by teryhill** [comment]
Do we need a con call for this discussion?

**Comment by aethelwulffe** [comment]
We are kinda due for one anyway.
My availability is low, but my interruptability is high, so someone post a confcall.

**Comment by tmccormi** [comment]
Let's shoot for a recurring meeting on Wednesdays at 10am Pacific/1pm Eastern?

**Comment by tmccormi** [comment]
Do you think we should consider dropping the old leftnav and option to use it entirely?  Vote on this with the Reaction Thumbs Up/Down

**Comment by tmccormi** [comment]
Here's another: drop all the current sql_upgrade and patch scripts and the admin.php security gap in favor of a more current "migration" process.  vote.

**Comment by tmccormi** [comment]
Drop the myportal/ (ZHH) directory and all references. Vote

**Comment by tmccormi** [comment]
Should we completely remove all dependencies on ZHH external services?  Vote

**Comment by teryhill** [comment]
Can we do the call at 4 or 5 pm Est?

**Comment by aethelwulffe** [comment]
All items upvoted.
I am a little saddened with the removal of the upgrade script and setup script interactions for the dozens of different steps involving scattered code all over the place.  You see, for the first time, I really actually now KNOW how it all works and when... :facepunch:

**Comment by teryhill** [comment]
That's what was needed, some one who understands .... then it can be removed.

**Comment by aethelwulffe** [comment]
REmoval is easy...replacing is kinda needed in the process.  I am pretty sure we want the gacl ripout to happen in the same Swell Foop.

**Comment by aethelwulffe** [comment]
Oh,
VOTE:  Completely remove all GACL stuff and add a registered component system.

**Comment by tmccormi** [comment]
The GACL stuff is way to pervasive and has flexibility that is very useful.  I think the way it is implemented could be improved dramatically and probably should be replaced, but not in Milestone this release

**Comment by aethelwulffe** [comment]
Ha!  I just wanted to see a downvote for a change.

**Comment by tmccormi** [comment]
Proof democracy has a chance....

**Comment by aethelwulffe** [comment]
Try again:
VOTE:  Remove excess fluff files from GACL not directly related to license, and keep only one copy of either the documentation pdf, html, or odt.

**Comment by tmccormi** [comment]
Just to prove what a CSS hack I am ... https://github.com/LibreEHR/LibreEHR/compare/menu-border-hack

This, sort-of, adds some border separation to the menu.   I tried using, oh, the border-width settings to no avail.

**Comment by aethelwulffe** [comment]
Hah!  I didn't even know where that css was!

**Comment by tmccormi** [comment]
Regarding: _I am a little saddened with the removal of the upgrade script and setup script interactions for the dozens of different steps involving scattered code all over the place._

There is a much better model we use in other projects ...   it relies on smaill specific php scripts in a migrations directory to handle this instead of a big horking single file with customized sql logic constructs.

**Comment by tmccormi** [comment]
For a look at how modern upgrade/migrations scripts work look here: 
https://github.com/mi-squared/volunteer-portal/tree/master/service/database/migrations

**Comment by tmccormi** [comment]
I think the agnositic migration tool is here: https://phinx.org/

**Comment by aethelwulffe** [comment]
The atheists seem to have more trouble than the agnostics, 'cause I 
still can't get composer to do it's thing.

**Comment by tmccormi** [comment]
This is 3 months past what we had planned..  Time to give release 1.0.1 a bump and get it done.  I've changed the date to Jan 31st.  Any objections?   Let's review the list and make some choices and kick it in the pants.

**Comment by tmccormi** [comment]
Hello?  anyone out there?  no response to my previous post...

**Comment by aethelwulffe** [comment]
There were no objections!

**Comment by tmccormi** [comment]
That is one positive way to look at it :-)

**Comment by tmccormi** [comment]
In the interest of having more fun the development branches going forward will have code names based on favorite books/stories.    

First up:  gloryroad - "Glory Road, Robert Heinlein" - an ordinary guy recruited to become an interstellar/cross dimensional hero

**Comment by tmccormi** [comment]
RELEASE IS RELEASED!

(master)$ git tag -f REL_101
Updated tag 'REL_101' (was eb211d4)

(master)$ git push origin master
...   ae80fb3..d222d14  master -> master

(gloryroad)$ git push origin gloryroad 
 * [new branch]      gloryroad -> gloryroad
