### ISSUE TITLE
Validate Date of Death to not allow future dates.

### ISSUE THREAD

**Issue by teryhill** [LibreHealthIO/LibreEHR#438]
Validate Date of Death to not allow future dates.

**Comment by tmccormi** [comment]
why? ;-)

**Comment by teryhill** [comment]
Well I guess if the morgue was slow. 😎

**Comment by tmccormi** [comment]
support of alternative medicine, like Psychic services ...

**Comment by azwreith** [comment]
Validation for both front and back end right?

**Comment by teryhill** [comment]
Yes Front-end and Back-end

**Comment by aethelwulffe** [comment]
DECEASED (17228 days ago)
Getting this on a two day old patient.

**Comment by aethelwulffe** [comment]
This is with the new date picker.

**Comment by teryhill** [comment]
Yes and I have been looking for the problem. It is giving an 12/31/69 date on that and financial review. Haven't traced it down yet.

**Comment by aethelwulffe** [comment]
Nothing is scoring in the logs that looks specific, and I am not seeing 
things in the DOM that clue me in.  Good to see confirmation elsewhere 
though...I thought it was possibly one of my branches for a minute.

**Comment by teryhill** [comment]
No it is something to do with the layout forms and those dates. the date picker works but if it is blank it defaults to a bad date. I guess I need to look at the field in the database and see it that is set to date(which I am guessing not) that might be it!!

**Comment by teryhill** [comment]
nope not in the database

**Comment by teryhill** [comment]
@aethelwulffe I have it figured out.

**Comment by teryhill** [comment]
The fix to DOB took care of this one also I am closing this issue see #338
