### ISSUE TITLE
Phone number formatting in demographics eg (123)456-7890.

### ISSUE THREAD

**Issue by teryhill** [LibreHealthIO/LibreEHR#439]
Phone number formatting in demographics example (123)456-7890. This should be user definable using a global variable.

**Comment by azwreith** [comment]
Hey! I decided to give this a shot. Assuming we have to add the setting for changing the phone number format in the `Demographics` section of the `Administration -> Globals` page. I guess it will be overkill to ask them to enter regex for it? ^^" 

Maybe I can add a dropbox of options showing commonly used formats such as `(ddd) ddd-ddd`?

Thanks!

**Comment by teryhill** [comment]
The drop box would be best since most users have little to no Idea about pattern matching (regex)

**Comment by aethelwulffe** [comment]
I think the regex would be called "underkill" for a office worker, and a regex is capable of carrying code.....Yeah...dropdown selection would be best!

**Comment by azwreith** [comment]
Okay then, drop box it is! I'll get to working on it when I get back from classes (7 am here rn) c:

**Comment by azwreith** [comment]
Wow, turns out I won't even need to modify any SQL at all for this haha :laughing:

**Comment by azwreith** [comment]
@teryhill The documentation in options_inc_php says layout.options.edit_options for P means `Default to previous value when current value is not yet set`, but I think it classifies phone numbers. Is that correct?

**Comment by aethelwulffe** [comment]
I honestly don't think defaulting to the last value is a great idea for a phone number in the use cases in the application.  If that is a FORMAT of a phone number, fine, but recalling the last phone number...no, leave the P off please.

**Comment by azwreith** [comment]
I meant when you check `select field_id, edit_options from layout_options where edit_options="P";`, only see:
```
+---------------+--------------+
| field_id      | edit_options |
+---------------+--------------+
| phone_biz     | P            |
| phone_cell    | P            |
| phone_contact | P            |
| phone_home    | P            |
+---------------+--------------+
```
Since only phone numbers have that, I was wondering if I can use edit options to detect if the field is a phone number :see_no_evil:

**Comment by aethelwulffe** [comment]
Seems like there should be a layout option TYPE that says "I am a phone number", hunh?  Same for "I am an email address".  Then sanity checks (based on the global format structure of phone numbers) would check to make sure the phone number was "real".  It is possible that you might have two different phone number structures for internationalization...but I don't know how bad overlooking that would be.

**Comment by azwreith** [comment]
Well, the title description and field id do contain the term "phone" so I can check for the occurrence of that at the worst case, but I don't see any other field that explicitly defines them as phone numbers.

I didn't understand the sanity check part. Could you elaborate?

I think you guys can just keeping phone numbers as 10 digits using a check function, and then storing it in the database in the format `xxx-xxx-xxxx`. So what I'm doing is stripping the `-`s from the phone numbers, and then converting it into a format according to the option in the global variable.

**Comment by aethelwulffe** [comment]
Sanity check would just ask "are there ten numbers?"  "Are there only digits?"  Meaning give an error message if it is a value that does not fit the format.  That behavior might be hard (since the whole thing doesn't use bootstrap), but if it is possible, that would be good.  Otherwise, the feature will still be better than it was.

**Comment by azwreith** [comment]
Ohh, I see what you mean. I think I saw functions for limiting it to only 10 digits and removing all non-digits from it. But it doesn't give an error message, just saves. I'll confirm when I get back home.
