### ISSUE TITLE
 Change statement to allow selection of no printing if patient is deceased.

### ISSUE THREAD

**Issue by teryhill** [LibreHealthIO/LibreEHR#440]
Change statement to allow selection of no printing if patient is deceased. This should be user definable using a global variable.

**Comment by azwreith** [comment]
I'll work on this ahuehue :smile:

**Comment by azwreith** [comment]
Where do I find the reports? Do you mean "Generate Report", "Download PDF" in the CCR page?

**Comment by teryhill** [comment]
look for the statement report in the sites directory . they are printed from the posting screen.
/sites/default/statement.inc. for the file. fees=>posting for the running screen.
Add a switch to globals to turn it on and off.
