### ISSUE TITLE
A report listing the top ten (or any number selected) CPT or ICD10 codes for a time frame.

### ISSUE THREAD

**Issue by teryhill** [LibreHealthIO/LibreEHR#442]
A report listing the top ten (or any number selected) CPT or ICD10 codes for a time frame. This report will have a date range, selection for CPT , ICD10 or Both, Number of codes to display.

**Comment by aethelwulffe** [comment]
There is a link between this and the "important codes" elements in at least one report.  There is also the flag that can be set in the codes administration UI that allows you to flag it "reporting".

**Comment by teryhill** [comment]
Duplicated.in 836 closing this one
