### ISSUE TITLE
Installation instructions for different Operating Systems

### ISSUE THREAD

**Issue by teryhill** [LibreHealthIO/LibreEHR#446]
Installation instructions for different Operating Systems, troubleshooting guide, FAQ .

**Comment by azwreith** [comment]
I'd like to work on this!

**Comment by nileshprasad137** [comment]
Even I would love to work on this!!

**Comment by nileshprasad137** [comment]
@teryhill Please have a look at https://github.com/LibreHealthIO/LibreEHR/pull/448

**Comment by teryhill** [comment]
@nileshprasad137  It looks good , you might want to mention restarting Apache when making PHP changes. The other Dev's will look at this also,

@azwreith Your instructions are welcomed as well.

Everyone needs to remember that in most instances the people that are installing the software lack any previous experience installing software of this type, So the instructions need to be very detailed and precise.

**Comment by aethelwulffe** [comment]
Dudes!  Make sure to assign issues to yourself before you start working on them!  If you want the project, that lets you steal it from everyone else first.  🥇

**Comment by htuck** [comment]
RE: the docs mentioned in issues 448 and 449: they look v. good to me from a technical point of view: good information clearly described.  However, per Teryhill's observation above of the experience level of most Libre users, it occurred to me that if the docs talk about using WAMPP or XAMPP, it's a little odd that they should continue on with file system path/ text editor- oriented instructions.

I realize the INSTALL file is a just re-work for Libre of the one in OpenEMR and it's not really aimed at the less cyber-literate users.  But if Libre is targeting a different audience, that might need to be taken into account.  INSTALL file's Steps 5 and 6 talk about editing php.ini and httpd.conf.  XAMPP and WAMP both provide a GUI based control panel- type tools accessed from either a shortcut to the XAMPP folder or the WAMPP icon on desktop/ toolbar.  With those tools you can do all the tasks you need to manage the web server: editing the config files; restarting the server, etc.  It might be good to give some rudimentary instructions how to use those tools in the (text format) INSTALL file and say something like, "see the FAQ for more detailed descriptions of the GUI config tools provided by XAMPP and WAMPP".  Then if the FAQ is going to be in a suitable format, like a pdf or doc file, put some illustrated detail into an answer to "Is there a GUI tool to manage the web server?"

**Comment by aethelwulffe** [comment]
Typical users don't ever see a MAN file, but no matter where the documentation is, it should be well indexed under a single master document.  If there are multiple media versions, they should all have the same content and...be linked.  On-line, off-line, and by version marker.

**Comment by aethelwulffe** [comment]
The latest XAMPP package, which is currently only available (slowly) at http://suncoastconnection.com/downloads/LibreHealthEHR-64bit-1.0.1-DEV.zip has a full set of revised docs and installation instructions for windows as well as general use...with pictures and all that...that will need revising all over again very soon.

**Comment by pri2si17-1997** [comment]
Hello @teryhill I have installed it on linux system, and made a note of it. These steps worked for me, so i'm pasting the link here.
  
https://forums.librehealth.io/t/steps-to-setup-libreehr-on-local-machine/579/14

**Comment by rksahu17** [comment]
@teryhill  I am documenting the installation procedure for windows with xampp soon be having a pull reqst...

**Comment by rksahu17** [comment]
@teryhill @tmccormi look at the documentation attached pdf(Installation for Windows with xampp
[Installation(Windows).pdf](https://github.com/LibreHealthIO/LibreEHR/files/853015/Installation.Windows.pdf)
)

**Comment by rksahu17** [comment]
@teryhill @tmccormi See this Installation documentation on Windows with xampp
[Installation(Windows).pdf](https://github.com/LibreHealthIO/LibreEHR/files/853017/Installation.Windows.pdf)

**Comment by rksahu17** [comment]
#521 pull request Installation windows guide...

**Comment by azwreith** [comment]
@aethelwulffe I think this one can be closed as well~
