### ISSUE TITLE
Calendar does not respect the Globals Locale setting for 24hr clock.

### ISSUE THREAD

**Issue by tmccormi** [LibreHealthIO/LibreEHR#455]
See screen shot:
![calendar-locale-times](https://cloud.githubusercontent.com/assets/285835/23526519/2b4be0f6-ff47-11e6-8b04-0b44de6675eb.png)

**Comment by teryhill** [comment]
That did not work in 4.1.2(7) either

**Comment by aethelwulffe** [comment]
Looks like we need a new calendar, hunh? 🤕

**Comment by teryhill** [comment]
I got it just need to put it on the switch

![image](https://cloud.githubusercontent.com/assets/4655366/23530821/63583dda-ff71-11e6-8ebb-86a73a9a9adf.png)

**Comment by teryhill** [comment]
You closed this too soon I have a fix for add_edit_event to follow the time global also

**Comment by teryhill** [comment]
here it is

![image](https://cloud.githubusercontent.com/assets/4655366/23532852/fb7387c8-ff7b-11e6-883a-62cb219979f5.png)
