### ISSUE TITLE
iFrames need to be resizable

### ISSUE THREAD

**Issue by aethelwulffe** [LibreHealthIO/LibreEHR#457]
We need to be able to re-size the iframe divs, and the tab labels need to follow them:
A resource for using css or other methods for doing this (some of these solutions will not work for our application:
http://stackoverflow.com/questions/8117761/how-can-i-make-an-iframe-resizable

**Comment by azwreith** [comment]
I can give this a shot!

**Comment by aethelwulffe** [comment]
You rock man.  GO!GO!GO!

**Comment by teryhill** [comment]
I have tested this and it looks and works food with 3 or less tabs open. 4 tabs it is no longer re-sizable on my screen (laptop) Good work @azwreith

**Comment by aethelwulffe** [comment]
Terry, how about doing the review on this and approve it.  I have not tested it.  I imagine that 4 tabs hits a minimum size or something anyway...
I will go for whatever you think...I just want to see it merged!

**Comment by azwreith** [comment]
Yes, it's not re-sizable with 4 tabs because I set the minimum width of each tab to be 20%. That can be changed though

**Comment by azwreith** [comment]
This can be closed now, unless we want to keep it open for future fixes :smile:

**Comment by aethelwulffe** [comment]
Darn good job.  Closing this issue.

**Comment by teryhill** [comment]
@azwreith  fixes can be on there own issue. This is a great addition to the code base. @pri2si17-1997  @nileshprasad137  and @azwreith  I sincerely hope y'all stick around after GSOC we can use all the help we can get.

**Comment by nileshprasad137** [comment]
@teryhill Surely, I will!

**Comment by pri2si17-1997** [comment]
@teryhill Sure...

**Comment by pri2si17-1997** [comment]
@teryhill, i'm not able to access chat forum. It is showing '502 Bad Gateway'. Please help me.

**Comment by aethelwulffe** [comment]
Chat is down at the moment...for all of us.

**Comment by teryhill** [comment]
It is down I have sent a request for assistance.
On Monday, March 6, 2017, 1:03:06 PM EST, pri2si17-1997 <notifications@github.com> wrote:
@teryhill, i'm not able to access chat forum. It is showing '502 Bad Gateway'. Please help me.

**Comment by aethelwulffe** [comment]
Ditto.

**Comment by azwreith** [comment]
I sure will, @teryhill :blush: 

Good night y'all!

**Comment by teryhill** [comment]
Good night
On Monday, March 6, 2017, 1:11:50 PM EST, Ujjwal Arora <notifications@github.com> wrote:
I sure will, @teryhill 😊
 
Good night y'all!
