### ISSUE TITLE
Can open multiple instances of the first two tabs.

### ISSUE THREAD

**Issue by teryhill** [LibreHealthIO/LibreEHR#459]
With the new code that was added to allow selecting of the first two tabs, you can open two instances of the calendar. 

Should there be a check to see if the tab is already open?

Is this a bug?

**Comment by aethelwulffe** [comment]
Or is it a FEATURE?  :)
Probably not really a feature...no.

**Comment by tmccormi** [comment]
I think that is because the are not identified in the menu as the base type.  The default login creates the tab with the original ID (from OpenEMR) and the menu JSON has a different ID for them.

**Comment by aethelwulffe** [comment]
So, resolve, won't fix, bug, what?

**Comment by tmccormi** [comment]
@yehster ???

**Comment by yehster** [comment]
Is the issue really that there are two calendars open for a user? Or is it that they have the calendar set for the second tab in options at startup, but it opens in the first tab from the menu?
It was a bit of a mess getting the startup options working for the second tab properly, so I am hesitant to mess with things.

**Comment by aethelwulffe** [comment]
I honestly don't see why having two (or three) open is a problem...more 
like a feature!

**Comment by teryhill** [comment]
2 instances of can be opened of the first tab can be opened.

![image](https://cloud.githubusercontent.com/assets/4655366/26724626/82f78904-4768-11e7-8550-d78e39be323b.png)

**Comment by aethelwulffe** [comment]
So whatever the first tab is, it can be opened again, but not any other tabs, right?

**Comment by teryhill** [comment]
what ever is in the first TWO tabs can be opened twice, sorry I was not clear 

![image](https://cloud.githubusercontent.com/assets/4655366/26725368/38c67148-476c-11e7-8035-23d77d2b4ed7.png)

**Comment by yehster** [comment]
The basic flaw is from the changes that were introduced which makes the menu items create new locked tabs instead of using the existing ones.  I honestly dislike that approach as things can get crowed very quickly. If it were up to me the  approach I would take to fixing this issue would be to revert to the old scheme.

**Comment by teryhill** [comment]
Ok then we will not worry about this and call it closed

**Comment by teryhill** [comment]
The changes to make the screen look different were put in place on the 16 of march. this issue occurred when the ability to define the first 2 tabs was introduced. @azwreith can you look at this and offer your opinion.

**Comment by aethelwulffe** [comment]
The other issue being that the original way was far too restrictive.  I got immediate feedback "Why can't I open more stuff?  I should be able to open more stuff!  Can I at least open another window?"  
The billing lady and the treatment plan reviewers like the browser open and extended across three monitors.

**Comment by yehster** [comment]
A mechanism to either use an existing tab or create a new tab based user preference rather than forcing one way or the other would be the ideal approach.

**Comment by yehster** [comment]
(by user preference I DO NOT mean another global flag), mostly likely another control(s) as part of the menu so it can be done on the fly.

**Comment by aethelwulffe** [comment]
Well we do desperately need better user pref settings, but Yep,  I am with you.  What we need are better ui controls...meaning better ways for the user to get what they want when they want it...not settings.

**Comment by azwreith** [comment]
Sorry I was down with a really bad cold for the last couple days >_< I just checked noticed that the Message center tab (which is 2nd default tab for me) can have only 1 instance open, and it gets overwritten by only a few of the tabs such as "Add new patient", "Summary". 
The calendar can be made to have 2 instances open, however if you close the default calendar tab and reopen it, only 1 instance will be open at a time.

About the other issue, can't we have a preference to create all new tabs as either locked or unlocked?

**Comment by teryhill** [comment]
This is still happening in the latest release. Just an update.
