### ISSUE TITLE
New patient screen not saving with datepicker changes

### ISSUE THREAD

**Issue by teryhill** [LibreHealthIO/LibreEHR#460]
@nileshprasad137  pointed out that the patient add was not saving in the latest development code.

**Comment by pri2si17-1997** [comment]
@teryhill it is getting saved. Here is the screenshot of the same:
![screenshot from 2017-03-03 19-28-10](https://cloud.githubusercontent.com/assets/12952169/23553645/c04bc45e-0047-11e7-95e7-ed8aad5ee991.png)

I have first created the sample patient and then searched it using the name.

**Comment by teryhill** [comment]
@pri2si17-1997 That is great. I know there are a couple of versions of the code out there, one is from the XAMPP package download (Windows) and the other is from a github download (Linux) .

Screen shot from the development code

![image](https://cloud.githubusercontent.com/assets/4655366/23554075/8fc60110-fff1-11e6-8dce-daebd7ab48f7.png)

**Comment by nileshprasad137** [comment]
@teryhill You can close this issue. It works fine now
