### ISSUE TITLE
XAMPP capital in DB name ACL setup fail

### ISSUE THREAD

**Issue by aethelwulffe** [LibreHealthIO/LibreEHR#464]
Apparently, as discovered today, with the XAMPP package, if you use a capital letter in the database name, the ACL setup fails...partially.
It says it can't find the database, but gives a success message.  Total tables is 192 vs. 194.  I will re-create the issue a third time as verification.
Note:  The was against the NationNotes module branch, but the next test will be against master.

**Comment by aethelwulffe** [comment]
Also, in master, this is the recommended database name...with capitals and a space...

>  (This is the name of the LibreHealth EHR database in MySQL - 'LibreHealth EHR' is the recommended)

**Comment by aethelwulffe** [comment]
lower_case_table_names

    Description: If set to 0 (the default on Unix-based systems), table names and aliases and database names are compared in a case-sensitive manner. If set to 1 (the default on Windows), names are stored in lowercase and not compared in a case-sensitive manner. If set to 2 (the default on Mac OS X), names are stored as declared, but compared in lowercase.
    Commandline: --lower-case-table-names[=#]
    Scope: Global
    Dynamic: No
    Data Type: numeric
    Default Value: 0 (Unix), 1 (Windows), 2 (Mac OS X)
    Range: 0 to 2 
It seems that the setting of 1 does not work as advertised.  The names are stored in lowercase, yet case-comparisons seem to be happening.  0 is not inherently compatible with everything else, as a name having only a case difference can have significant issues if imported to another OS.  2 is also potentially problematic.
Any suggestions?

**Comment by teryhill** [comment]
Change the recommendation to lower case with no space and add a warning to the XAMPP install

**Comment by aethelwulffe** [comment]
I think a warning to the xampp install would be good...but setting the mode after you have already created a database is an issue. still.

**Comment by aethelwulffe** [comment]
I will keep this in mind.  Closing as an issue.
