### ISSUE TITLE
Replace Administration->Practice

### ISSUE THREAD

**Issue by aethelwulffe** [LibreHealthIO/LibreEHR#478]
This interface controls most of the clinic's basic configuration details.  Including legal entities and connectors to 3rd parties like insurance companies and pharmacies.
They consist of HTML templates using the venerable SMARTY template engine, as does the Post-Nuke calendar system.  The calendar system is up for replacement, and this is another piece of migrating from the template engine.
Job package items:

- Replace the existing UI system.  Fields should have sanity/type checking.
- Identify and document SMARTY dependencies used by this interface, as well as any other UI elements that are found to be using the SMARTY package.
- Remove the original UI components as completely as possible without breaking other features.
- Graphically and textually document the use of the UI.
- Provide context documentation (hover text et cetera) within the UI.

Additional items desired:
Migration scripts from any modified or replaced table structures.
Improved use of the addresses, phone_numbers and related tables.

**Comment by nileshprasad137** [comment]
It seems interesting. Is this a GSOC project idea?

**Comment by aethelwulffe** [comment]
Just an idea.  Right now it is on the "issues considered" list, as decided by just one person (yours truly). 😺  We don't know how many interns we may get, and we must discuss priorities, reality checks for the intern to actually have the hours needed to complete the deliverable, and other worries I am not even privy to.  I DO know that this UI must die...along with the template engine.

**Comment by rksahu17** [comment]
@aethelwulffe sir, do we have to make a new UI for the LibreEHR in this idea??

**Comment by aethelwulffe** [comment]
The UI is built on the 17 year-old SMARTY template system...so yes.

**Comment by nileshprasad137** [comment]
@aethelwulffe Are we migrating from Smarty Template Engine only on `Calender` and `Administration->Practice` or can there be a proposal for a complete revamp of UI throughout ?

**Comment by aethelwulffe** [comment]
@nileshprasad137 Ujjwal has put out a calendar proposal, but the rest of the SMARTY UI removal and modernization could well be another project.  I would strongly encourage you to put out a proposal for a major UI and perhaps thematic renovation...thereby removing as many legacy holdbacks and "alternate" UI tools as possible while improving function and accessibility of the good, useful, and comprehensible.

**Comment by nileshprasad137** [comment]
@aethelwulffe He is already doing the revamp of UI. I just saw his proposal.

**Comment by tmccormi** [comment]
Do put in your own proposal, we like healthy competition :-)

**Comment by nileshprasad137** [comment]
Sure ,  I like competition, its just that @aethelwulffe mentioned that, so I wanted to inform him as there could be a possible confusion.

**Comment by aethelwulffe** [comment]
No-one is going to completely revamp the whole UI in ten weeks...and I am absolutely positive we can coordinate efforts, and as Tony said, the more proposals, the better the work package analysis will be.  Try to keep your deliverables in the proposal as limited as possible.  The better defined the scope, the more coordinated the POAM is, the better the proposal is by definition.
  The UI needs the pieces that currently run on SMARTY to be replaced completely.  There is also a lot more to the UI than just those pieces.  I am sure I don't have to point many of them out to you for you to get the idea.  The back-end is just as rich of an pack of "opportunities" as the front end.  The database is a mess.

**Comment by aethelwulffe** [comment]
This is assigned to and being worked on by Nilesh.  I think we can close this as a specific issue as it is clearly part of the larger UI revision.
