### ISSUE TITLE
Datepicker accepting string

### ISSUE THREAD

**Issue by pri2si17-1997** [LibreHealthIO/LibreEHR#500]
Whenever there is any field which is supposed to be of date type, there is date picker, but that field is also taking string in input. This is in reference to #447. Will soon get a fix for it.

![screenshot from 2017-03-12 00-16-07](https://cloud.githubusercontent.com/assets/12952169/23825973/a71df3da-06b9-11e7-86f8-85d9deeb6730.png)

**Comment by aethelwulffe** [comment]
Do we want to require the date-picker to be used?  Some folks are very keyboard-centric, and touching a mouse slows them down...and even causes errors they would not have made otherwise.
-Me, I like the date-picker!

**Comment by pri2si17-1997** [comment]
Hello @aethelwulffe , I was saying that we must not allow string input. As soon as anyone types string, we must indicate that it is invalid input format. So he/she will enter the correct format.

**Comment by aethelwulffe** [comment]
You obviously have a handle on this, and yes, I agree with your statement.

**Comment by pri2si17-1997** [comment]
Hello @aethelwulffe @teryhill 
Can you please look at https://github.com/LibreHealthIO/LibreEHR/issues/447#issuecomment-287148587
and give your views.

**Comment by pri2si17-1997** [comment]
Hello @aethelwulffe @teryhill 

I want to implement following things and need your help. Please look at it and do comment and correct me wherever i'm wrong. Your views are important for me.

- Validations : Validation of all the forms. Screenshot of one such i posted in #447. This will be helpful as user will get to know the wrong entries and write entries as soon as he/she types.(By marking that input type with red and green border.) I have a clear picture in my mind of implementing it.

- UI : There are some place like, create new patient, where we have to follow two steps for creating patient. Also the design of calendar and way of booking appointment. I want to use bootstrap responsive framework for it, as it will provide us full responsiveness and compatibility with mobile devices. Also it can solve the tab issue, where we can have multiple tabs open and one tab will be displayed on whole screen. There will be a side menu(a small icon), which will keep the list of all tabs opened and clicking on it will switch to that tab.(as suggested by @aethelwulffe earlier). Also bootstraps modals.

- Database Upgrade : This was mentioned in (https://forums.librehealth.io/t/practice-appointment-calendar-for-librehealth-ehr/513). I actually don't understand what you meant, but what I thought, I would like to mention that : I was thinking of using PHP PDO. It can help us in future, if we wanted to migrate to another database. Also it has more feature than mysqli (named parameters and quotes.) Also it is my personal choice of using PDO, because of its object oriented nature. But it depends on you guys.

Lastly,

- User Registration and Communication : I looked at issue #78 . I think there is no user registration by this time.(Correct me if i'm wrong.) If we have user registration then we can have email address verification and mobile number verification.(by now i'm validating it using regex type email) This can also help us in communicating to our patients through their mail id or phone number.

Your reviews are important, so please look at it.

**Comment by aethelwulffe** [comment]
Dude, you are correct on about all points.  I for one also have no problem with you hijacking your own thread to discuss your proposals in short-term (Ujjwal already did), but it is better served elsewhere, as these get buried...
  We would be very very happy to receive a proposal on moving the whole project to PDO.  It is a massive project, as it touches almost everything.  Nilesh and Ujjwal are all over the "fun" stuff at this point,  but a proposal on the communication piece _or_ the PDO database piece would received with great enthusiasm.
  I am going to start posting responses to these in a continuous thread...

**Comment by pri2si17-1997** [comment]
Thanks @aethelwulffe .

I will rectify it more. :)

**Comment by pri2si17-1997** [comment]
Hello @aethelwulffe 

I am asking about registration? Should user registration be included?

If user registration is there, then we could have some good stuffs :)

**Comment by aethelwulffe** [comment]
OK, discipline in ranks sailors!  Put posts in relevant topics PUHLEEZ!  -but yeah, registration...optional...totally optional...is a long-held dream...but totally unrelated to date-pickers!

**Comment by pri2si17-1997** [comment]
Ya, but I continued this thread only, as I thought I have previously asked in it so  Sorry for that. No such mistakes from next time.
