### ISSUE TITLE
"Portal Dashboard" page is missing

### ISSUE THREAD

**Issue by azwreith** [LibreHealthIO/LibreEHR#516]
Steps to replicate: 
1. Go to Miscellaneous -> Portal Dashboard
2. 404 error
3. Profit??

It seems to be looking for a file `/LibreEHR/patients/patient/provider` which doesn't exist.

**Comment by pri2si17-1997** [comment]
Yes. I also faced this issue.

**Comment by aethelwulffe** [comment]
That sounds like a terrible directory name scheme from the get-go.  There have been some resource directories changed...but I don't think this was one of them.  @teryhill ?

**Comment by teryhill** [comment]
@azwreith @pri2si17-1997 @nileshprasad137 @aethelwulffe  the commit was added to the code base 9 days ago. are y'all up to date on the code changes 

![capture](https://cloud.githubusercontent.com/assets/4655366/23979024/649e00d8-09cd-11e7-8364-27222af1dcde.PNG)

**Comment by azwreith** [comment]
@teryhill I checked the `sites/default/menu_data.json` on this repo. It still says
```javascript
{ 
        "label" : "Portal Dashboard",
        "menu_id" : "por2",
        "target" : "por",
        "url" : "/patients/patient/provider",
        "children" : [ ],
        "requirement" : 0,
        "global_req_strict" : "portal_onsite_enable",
        "acl_req" : [ "patientportal", "portal" ]
    },
```

**Comment by teryhill** [comment]
do you have the following directory structure?

![image](https://cloud.githubusercontent.com/assets/4655366/23995469/1b06cb96-0a20-11e7-86e0-4ad8c027022d.png)

**Comment by azwreith** [comment]
@teryhill This is what I get:
![image](https://cloud.githubusercontent.com/assets/10354323/23997200/5e599f1c-0a76-11e7-855f-71b4819c8c9f.png)

**Comment by teryhill** [comment]
under the directory patient do you have a .htaccess file and does it have correct permissions

**Comment by azwreith** [comment]
Nope I don't see any `.htaccess` file. Hey what's the filename path of the Portal Dashboard frame you sent above?

**Comment by teryhill** [comment]
The same as yours. 

Look on the repository and see if you see the file.

**Comment by azwreith** [comment]
Oh wait, stupid me was looking under the `patients` directory not the `patient` directory. The `patient` directory does have the .htaccess file. It has rw-r-r. The github repo doesn't have the `provider` folder either though.

**Comment by teryhill** [comment]
change the permissions to execute.

**Comment by teryhill** [comment]
The .htaccess has a redirect in it to the index.html for security reasons.

**Comment by azwreith** [comment]
@teryhill I got working after enabling `mod_rewrite` by using `a2enmod rewrite`. I guess this can be included in the install instructions revamp PR :)

**Comment by aethelwulffe** [comment]
Leaving this issue up until it is reported that the instructions...somewhere...have reflected this "gotcha".

**Comment by azwreith** [comment]
Added in the documentation PR, this can be closed now :smile:

**Comment by azwreith** [comment]
Closing this since it was added with the new installation instructions :blush:
