### ISSUE TITLE
There is no forget password option in the admin page. 

### ISSUE THREAD

**Issue by rksahu17** [LibreHealthIO/LibreEHR#520]
we can take the email while installation and send the recovery link to reset password.

**Comment by rksahu17** [comment]
@teryhill have a look at this issue.

**Comment by rksahu17** [comment]
@aethelwulffe see this issue
I got this as i forgot my password...hehe

**Comment by aethelwulffe** [comment]
I am not completely following you there, but I think you are saying "Dudes, when you are running the install/setup, there should be an option to do a "breakglass" email setup for password recovery...right?

**Comment by rksahu17** [comment]
yes,i was suggesting any means of password recovery.

**Comment by aethelwulffe** [comment]
In review, I see that the setup prints your initial username and passphrase out for you a couple of times.  To add an access recovery option at setup, you would need to have a full globals configuration available at that time, which is not a totally bad idea, but would involve smtp setup and everything else before logging in.  There is already a breakglass for recovery, but you do have to log in at least one time to set it up.
  I am thinking that an immediate admin user level recovery system might not fit into a security protocol without a good bit of thought.
