### ISSUE TITLE
Error on Portal Dashboard

### ISSUE THREAD

**Issue by navendu29** [LibreHealthIO/LibreEHR#527]
There is an error occuring on Portal Dashboard
1.Go to Miscellaneous -> Portal Dashboard -> Audit Changes
   It gives "An unknown error occured"
2.Go to Miscellaneous -> Portal Dashboard -> Patient Mail
   It gives "Error: Table 'libreehr.onsite_mail' doesn't exist"

**Comment by aethelwulffe** [comment]
onsite_mail not found in the /sql directory.
Grep
LibreEHR\patients\lib\portal_mail.inc(22,58):         $n = sqlQueryNoLog("SELECT MAX(id) as newid from onsite_mail");
LibreEHR\patients\lib\portal_mail.inc(26,35):     return sqlInsert("INSERT INTO onsite_mail (date, body, owner, user, groupname, " .
LibreEHR\patients\lib\portal_mail.inc(51,5):     onsite_mail AS p
LibreEHR\patients\lib\portal_mail.inc(89,5):     onsite_mail AS p
LibreEHR\patients\lib\portal_mail.inc(164,5):     onsite_mail AS p
LibreEHR\patients\lib\portal_mail.inc(183,30):         sqlStatement("update onsite_mail set message_status = ?, activity = '0' where id = ?", array($message_status, $id) );
LibreEHR\patients\lib\portal_mail.inc(186,30):         sqlStatement("update onsite_mail set message_status = ?, activity = '1', deleted = '1',delete_date = ? where id = ?", array($message_status, date('Y-m-d H:i:s'), $id) );
LibreEHR\patients\lib\portal_mail.inc(189,30):         sqlStatement("update onsite_mail set message_status = ?, activity = '1' where id = ?", array($message_status, $id) );
> 8 occurrence(s) have been found.

**Comment by navendu29** [comment]
The table  'onsite_mail' does not exists in the database .
