### ISSUE TITLE
Delete Patient

### ISSUE THREAD

**Issue by pri2si17-1997** [LibreHealthIO/LibreEHR#531]
Steps to reproduce : 

- Create patient or use existing patient.

- Delete that patient from the DELETE button provided. A popup will come displaying the tables from that patient reference has been deleted(ideally this should not happen). Close that popup.

- The page will not get refreshed after closing the above said popup, and it will still show the patient as it is.
 It should get refreshed as soon as the patient is deleted.

Here is the screenshot : 
![screenshot from 2017-03-29 16-27-43](https://cloud.githubusercontent.com/assets/12952169/24451503/b7b3c896-149c-11e7-8405-c1055a8f48f4.png)

Clearly it can be seen that, no patient is present right now (as patient finder shows no records). And export is showing some default values. Ideally that must get refreshed immediately.

**Comment by pri2si17-1997** [comment]
Hello @teryhill @aethelwulffe , please look at this so that if required then I can proceed further.

**Comment by pri2si17-1997** [comment]
Hi @aethelwulffe 

This is what log file shows : 
`PHP Fatal error:  Uncaught Exception: TCPDF ERROR: Could not include font definition file: helvetica in /var/www/html/LibreEHR/modules/html2pdf/vendor/tecnickcom/tcpdf/tcpdf.php:2927\nStack trace:\n#0 /var/www/html/LibreEHR/modules/html2pdf/vendor/tecnickcom/tcpdf/tcpdf.php(4275): TCPDF->Error('Could not inclu...')\n#1 /var/www/html/LibreEHR/modules/html2pdf/vendor/tecnickcom/tcpdf/tcpdf.php(4436): TCPDF->AddFont('helvetica', '', '', true)\n#2 /var/www/html/LibreEHR/modules/html2pdf/vendor/setasign/fpdi/fpdf_tpl.php(303): TCPDF->SetFont('helvetica', '', 12)\n#3 /var/www/html/LibreEHR/modules/html2pdf/vendor/tecnickcom/tcpdf/tcpdf.php(1962): FPDF_TPL->SetFont('helvetica', '', 12)\n#4 /var/www/html/LibreEHR/modules/html2pdf/_class/myPdf.class.php(45): TCPDF->__construct('P', 'mm', 'LETTER', true, 'UTF-8', false)\n#5 /var/www/html/LibreEHR/modules/html2pdf/html2pdf.class.php(136): HTML2PDF_myPdf->__construct('P', 'mm', 'LETTER', true, 'UTF-8')\n#6 /var/www/html/LibreEHR/interface/patient_file/report/custom_report.php(56): HTML2PDF->__con in /var/www/html/LibreEHR/modules/html2pdf/vendor/tecnickcom/tcpdf/tcpdf.php on line 2927, referer: http://localhost/LibreEHR/interface/patient_file/report/patient_report.php`

I think, there might be some issue with adding fonts.

**Comment by aethelwulffe** [comment]
Looks like the logic that determined what should appear in the top or bottom pane of the original UI does not know what to do with tabs that "belong" to a patient that no longer exists.  It seems like the delete button itself should be doing the resetting of the tabs via a function in a standard library.

**Comment by pri2si17-1997** [comment]
Shall I go for it @aethelwulffe. This can be solved if we make request using ajax. When the response is "Success", then refresh that frame or say the whole page.(whichever suits best). Also we need not to show the user from which table that values are getting removed. What you say?

**Comment by aethelwulffe** [comment]
I think that some sort of summary like "billing stuff, documents stuff, medications stuff removed" isn't a bad way to summarize what they did...or are about to do...when they delete a patient is a good idea, but no, you don't need the table names specifically (I LIKE THEM...but I am a developer, and this ain't for me!).  I think you should go for the ajax approach...everywhere we can.

**Comment by teryhill** [comment]
I would really it was made a "Soft" delete at some point instead of the hard delete that it is currently. Customers will always say I did not mean to delete them and then I am stuck combing thru the logs to re-create the deleted information.

**Comment by aethelwulffe** [comment]
Yeah...you know this would be a good time to take care of that @teryhill @pri2si17-1997 .
The "soft delete" means setting a flag field to "deleted" in the database.  On the other hand, having the option for a hard delete (with admin confirmation) is really useful when you have a totally junk patient record.

**Comment by aethelwulffe** [comment]
"Do you really want to delete patient 9343?"
[Enter]
"Do you really really want to delete patient 9343?"
[Enter]
"Do you really really really want to delete patient 9344?"
[Enter]
"Ha, fooled you.  You are not paying attention.  I just asked you if you wanted to delete a different patient.  Please call your supervisor.  This interaction has been recorded for QA purposes."

**Comment by pri2si17-1997** [comment]
Hello @aethelwulffe @teryhill 

I am busy with mid - evaluations of academic projects. I will remain inactive for few days, and will resume my work asap.

**Comment by azwreith** [comment]
@aethelwulffe You really should get a job as an Easter Egg maker for applications xD

**Comment by aethelwulffe** [comment]
Easter Egg:  _An undocumented feature of function._
-Seriously, I think we have _quite_ enough of those already. 😈

**Comment by yehster** [comment]
On success, the delete button, needs to some how end up calling the javascript used for the "clear button"  next to the patient name.

https://github.com/LibreHealthIO/LibreEHR/blob/master/interface/main/tabs/js/tabs_view_model.js#L231

**Comment by tmccormi** [comment]
Merged, but it does need to address @yehster suggestion.

**Comment by aethelwulffe** [comment]
@pri2si17-1997 Think you could take another look at this?

**Comment by pri2si17-1997** [comment]
Yes @aethelwulffe . I will surely look at this.

**Comment by aethelwulffe** [comment]
Thank you.  #242 has a key point too.

**Comment by aethelwulffe** [comment]
Closing this...referring it to the UI modifications.
