### ISSUE TITLE
"Encounter Summary" tab not accesible from "Administrative" and "Clinincal" tab

### ISSUE THREAD

**Issue by nileshprasad137** [LibreHealthIO/LibreEHR#535]
Steps to reproduce:
1. Create and then choose an encounter or a past encounter.
2. Go to `"Administrative" ` or ` "Clinical" ` tab.
3. Encounter Summary tab is not accessible from there.

**Comment by aethelwulffe** [comment]
Verified.  You must cancel the form you are in to get to the encounter summary (being "form_encounter").  Basically, it looks to me like the tab simply does not work!
As a side note, the SOAP form does nothing.  I suspect that is because we removed it, but it is still in the default registry table database.

**Comment by aethelwulffe** [comment]
<a href="JavaScript:void(0);" id="enc2" onclick=" return top.window.parent.left_nav.loadFrame2('enc2','RBot','patient_file/encounter/encounter_top.php')">Encounter Summary</a>
Right now, you must hit cancel to reload the frame to the encounter summary.

**Comment by aethelwulffe** [comment]
What works when you cancel a form is this: 
`<input value="Cancel" onclick="top.restoreSession();location='/libremaster/interface/patient_file/encounter/encounter_top.php'" type="button">`
What it is doing is this:
`<a href="JavaScript:void(0);" id="enc2" onclick=" return top.window.parent.left_nav.loadFrame2('enc2','RBot','patient_file/encounter/encounter_top.php')">Encounter Summary</a>`
That is obviously not real good.
The other tabs do this:
`<a onclick="openNewForm('/libremaster/interface/patient_file/encounter/load_form.php?formname=fee_sheet')" href="JavaScript:void(0);">Fee Sheet</a>`

**Comment by nileshprasad137** [comment]
Thanks @aethelwulffe , I'll get back to this in a couple of hours.

**Comment by aethelwulffe** [comment]
I am pretty sure this will be an easy fix for you.  Let me know if you need anything.

**Comment by nileshprasad137** [comment]
PR #535 Fixes this.

**Comment by aethelwulffe** [comment]
Already reviewed and approved.
