### ISSUE TITLE
Download PDF is not working for patient report

### ISSUE THREAD

**Issue by pri2si17-1997** [LibreHealthIO/LibreEHR#536]
Here is the screenshot of the same.
![screenshot from 2017-04-10 01-05-43](https://cloud.githubusercontent.com/assets/12952169/24851539/aa320efe-1df1-11e7-9cb8-09caba2f0d2e.png)

**Comment by pri2si17-1997** [comment]
Hello @teryhill @aethelwulffe 
Need some help. Not getting any info from log file.
@nileshprasad137 You can also look at it.

**Comment by aethelwulffe** [comment]
Look and see what pdf generator that calls.  That was moved (by me).  Aside from that, I will check out the jquery version location and all that.

**Comment by aethelwulffe** [comment]
I will see about replicating the issue when I get to the house.

**Comment by aethelwulffe** [comment]
Couldn't get anything done last night, so I am working on this now.  Sorry for the delay.

**Comment by pri2si17-1997** [comment]
Hi @aethelwulffe

This is what log file shows :
`PHP Fatal error: Uncaught Exception: TCPDF ERROR: Could not include font definition file: helvetica in /var/www/html/LibreEHR/modules/html2pdf/vendor/tecnickcom/tcpdf/tcpdf.php:2927\nStack trace:\n#0 /var/www/html/LibreEHR/modules/html2pdf/vendor/tecnickcom/tcpdf/tcpdf.php(4275): TCPDF->Error('Could not inclu...')\n#1 /var/www/html/LibreEHR/modules/html2pdf/vendor/tecnickcom/tcpdf/tcpdf.php(4436): TCPDF->AddFont('helvetica', '', '', true)\n#2 /var/www/html/LibreEHR/modules/html2pdf/vendor/setasign/fpdi/fpdf_tpl.php(303): TCPDF->SetFont('helvetica', '', 12)\n#3 /var/www/html/LibreEHR/modules/html2pdf/vendor/tecnickcom/tcpdf/tcpdf.php(1962): FPDF_TPL->SetFont('helvetica', '', 12)\n#4 /var/www/html/LibreEHR/modules/html2pdf/_class/myPdf.class.php(45): TCPDF->__construct('P', 'mm', 'LETTER', true, 'UTF-8', false)\n#5 /var/www/html/LibreEHR/modules/html2pdf/html2pdf.class.php(136): HTML2PDF_myPdf->__construct('P', 'mm', 'LETTER', true, 'UTF-8')\n#6 /var/www/html/LibreEHR/interface/patient_file/report/custom_report.php(56): HTML2PDF->__con in /var/www/html/LibreEHR/modules/html2pdf/vendor/tecnickcom/tcpdf/tcpdf.php on line 2927, referer: http://localhost/LibreEHR/interface/patient_file/report/patient_report.php`

I think, there might be some issue with adding fonts.

**Comment by aethelwulffe** [comment]
https://github.com/spipu/html2pdf/
is the project that this comes from, last updated 10 months ago.  I have that repo checked out, but I also have the branch in which the html2pdf was moved originally.

**Comment by pri2si17-1997** [comment]
@aethelwulffe @teryhill 

Done. It is working. :)

Here is the screenshot of the same. 

![screenshot from 2017-04-11 21-03-20](https://cloud.githubusercontent.com/assets/12952169/24917310/5fdd0520-1efa-11e7-8d6b-9fccbc17a354.png)

**Comment by aethelwulffe** [comment]
Darn.  I just jumped a pull request on that!
Where is your PR?

**Comment by pri2si17-1997** [comment]
I have finished now. But it seems that you have added font, while I upgraded it to work for PHP7.

I am creating PR.

**Comment by aethelwulffe** [comment]
All I did was add the helvetica font, yes.  We will drop my PR once you are up.

**Comment by aethelwulffe** [comment]
Merge is in.  Closing
