### ISSUE TITLE
"Add Encounter" button not working under Popups ->Issues

### ISSUE THREAD

**Issue by nileshprasad137** [LibreHealthIO/LibreEHR#544]
Steps to replicate : Choose a patient and navigate to `Popups->Issues` . `Add Encounter` button is not working there because of some Uncaught-Type JS Error.

@teryhill I have no problem if you resolve this issue as the approaching exams are making it difficult for me to be active here.

**Comment by teryhill** [comment]
@nileshprasad137  I will look at it when time permits, You take care of getting your exams done

**Comment by growlingflea** [comment]
I went ahead and made a fix.  It looks like the javascript that was calling the location was written for frames, not tabs.  I'm not sure if this is what was the expected fix but here are some screen shots.  




![newencounterfix1](https://cloud.githubusercontent.com/assets/8116478/25774852/71b8ee48-324c-11e7-9fa8-687d8da93b26.png)
![newencounterfix1](https://cloud.githubusercontent.com/assets/8116478/25774853/73e3a186-324c-11e7-969e-ea0b32bf783f.png)
