### ISSUE TITLE
Calendar replacement discussion

### ISSUE THREAD

**Issue by azwreith** [LibreHealthIO/LibreEHR#554]
## Current Functionality:

**View calendar:** 
Date/Week/Month: already handled by FullCalendar
According to provider, facility

**Print calendar.**

**Add/Edit Appointments:**
Book for Patient, Schedule for provider
Edit/Rescheduling
Find Available time slots
Find Patient
Recurring appointments

**Find appointments:**
Using keywords, categories, date ranges, providers , facilities.

**Patient Tracker/Flow board:**
Status update and by whom (in demographics)

**Some of the same stuff in patient portal.**

## New features: 
**Wait list**
**Reordering of columns**

## Issues to keep in mind:
**Globals**
**Auto refresh**
**Responsiveness**
**Form validation**
**Work with all date formats**

## Schema stuff:
`libreehr_modules` and `libreehr_modules_vars`: Delete and make a new table for calendar globals.
`categories`, `events`: Reuse/Rename.
`patient_tracker`, `patient_tracker_event`: Keep as is.
`limits` and `topics`: Remove as it's not currently being used.

@aethelwulffe @teryhill Please look this over and see if there's anything missing or incorrect. :sweat_smile:

**Comment by teryhill** [comment]
@azwreith Looks like you have most all of the bases covered. I cannot think of anything that is obviously   missing, I will reserve the right to say "oops did not see that one" at some later date

**Comment by yehster** [comment]
Future Appointments and Appointment History for individual patients on the demographics screen is a significant feature that should probably be explicitly mentioned as existing functionality.

**Comment by teryhill** [comment]
Yes we are looking at an appoint log/audit feature that will show those items plus give more information as to what happens to the appointments.

**Comment by tmccormi** [comment]
- Schedule templates for providers, ie reserved and preferred times for appointment types.
- Appointment reports, there are several and the the fact that appoints can be specifically linked to the 'encounter/visit' so you can report on that.
- Given time we should consider group appointments, ie: multiple provider and multiple patients (behavioral and integrative medicine)
- Updates to ehr-api to support the fhir interface we have for the calendar.

**Comment by tmccormi** [comment]
Aso, consideration on how to install the new appt module and migrate old appointment data.

**Comment by aethelwulffe** [comment]
Schedule templates as a background css, then overlay the other stuff was an idea at one point.  You don't want a "template" actually interfering in any totalitarian way.
  Once we have a new data model, we can throw plenty of "real" data into a migrate script to see how messed up it is! :)

**Comment by teryhill** [comment]
@azwreith I saw where you had posted the calendar screen in side of LibreHealth EHR. Is everything going okay ?

**Comment by teryhill** [comment]
@azwreith Something like this for the appointment audit feature.

![image](https://cloud.githubusercontent.com/assets/4655366/26808772/3c6c0c68-4a2d-11e7-92e8-49749c467f25.png)

**Comment by azwreith** [comment]
@teryhill Yep that looks neat!

**Comment by teryhill** [comment]
@azwreith have you got some screen shots and/or code that we can look at?  Since you are finished with the displaying of everything.

**Comment by azwreith** [comment]
@teryhill @aethelwulffe 
Please take a look at the code here: https://github.com/azwreith/LibreEHR/tree/calendar-replace
Everything is in a new folder called calendar_new for now.

Latest Screen Shot:
![screenshot from 2017-06-15 01-28-25](https://user-images.githubusercontent.com/10354323/27166679-6e0d0a3a-516a-11e7-861e-ff449db64326.png)

I'm having problems with recurring events. I understand what everything in the serialized recurrspec means but I'm having trouble implementing it. I can't seem to find the code where they parse it either :disappointed:

**Comment by teryhill** [comment]
@azwreith look at /library/appointments.inc.php in the function fetchEvents at about line 96

**Comment by aethelwulffe** [comment]
Beat me to it...
Ujjwal, do me a favor and investigate how things work when you go to a 24 hour clock (13:00 vs 1PM) and when you have time zones that differ from system time.

**Comment by aethelwulffe** [comment]
Other testing factors you might want to check out:
Test with something like 10-20 providers, 10-20 facilities.
Check out scrolling, and see if there is any way to implement scrolling overflow for just the actual calendar section (div? frame?). 
Most preferable would be for the horizontal overflow scroll to be at the top as well as the bottom, the control sections to be static, and only the actual calendar bit to be scrollable.  Another dream would be a zoom feature (mouse controls, not just mobile gestures) that allow scaling without doing ctrl+/- for the whole browser.
We have found in the past that without horizontal scrolling, the application becomes useless for more than a couple of providers.  The median number of providers in a practice is 6.5.  The clinic I most closely work with has 48 right now.

**Comment by aethelwulffe** [comment]
Also, my personal preference is that you locate your code in /modules if possible, and contains a file describing where it is called in the rest of the application, and other dependencies that may be elsewhere.  Others may have a different opinion, but I feel that if everything for a particular feature is in one easy-to-find location with documented hooks, maintenance, refactoring, and a lot of other things become much easier in the future.

**Comment by aethelwulffe** [comment]
Other food for thought:
Have at least three layout options.
1.  How you have it.
2.  One that optimizes vertical space.
3.  One that optimizes horizontal space.
Basically that means an option for all controls to be in the little left-side navigation area, or cram everything across the top row.  Ideally, you should be able to minimize the controls as well, or have a minimized (pure icon tooltip) control set as a floating option.
-These are all just my crazy ideas.  I am not trying to distract you or set an agenda.

**Comment by azwreith** [comment]
Adding a lot of providers currently tries to fit everything in that tiny window. Yes, scrolling for the "calendar" part with the sidebar constant shouldn't be too difficult to implement. 
About the zoom buttons, I think it's possible to do it by manipulating the css zoom property using jquery so I'll try that out after I do horizontal scrolling.

Okay, I'll move the code to /modules folder. I'm sort of already creating documentation as I go but I'll put it all in one place.

I think the current one already optimizes vertical space as much as possible without zooming out by default. The horizontal space one will require a bit of thinking as to how to show the providers select option.

I think next move would be to integrate it with addeditevent and add type/sanity checking to it. I can send in a pull request for merging this part after that is done and globals are properly working.

**Comment by teryhill** [comment]
@azwreith when you look at addedit event we need a more granular way of doing the recurring appointments. Currently the options are for 2nd, 3rd,4th etc it would be easier if the user could say repeat the appointment every Tuesday for the next (time frame) or every Mon, Tue and Thu. So maybe some way of picking a day of the week to repeat on.

**Comment by azwreith** [comment]
@teryhill Okay I'mma check what I can do over there!

@teryhill @aethelwulffe 
About having too many resources in the calendar, I explored several options but in short having a horizontal scroll bar seems too hard to implement with css or jquery. They even have a ticket about such a feature on their repo. What I think instead, when a practice is dealing with a lot of doctors, they can switch to an alternate representation using one of the globals. Instead of vertical-resource-format which we have currently, they can switch over to a view such as this: https://fullcalendar.io/js/fullcalendar-scheduler-1.6.2/demos/json.html Basically the doctors become the Y axis and the time slots become the X axis. It's easier to use this view when we have a lot of doctors. What do you think?

**Comment by tmccormi** [comment]
I really like the axiz view switch.

**Comment by aethelwulffe** [comment]
I like the axis view switch too, and I am guessing it should be the default

**Comment by azwreith** [comment]
Roger that!

**Comment by teryhill** [comment]
@azwreith  looking at the todo's in the recent code, you will need to make sure that you use the globals for the appointment duration as each clinic can hay different intervals.

If you can go ahead and start a pull request for the code changes so @aethelwulffe and @tmccormi  can follow the changes that are coming.

**Comment by azwreith** [comment]
Okay! I'll add em today as well all other TODOs~

Cool, creating a PR right now!

And Happy Fourth of July everyone! Enjoy the fireworks~

**Comment by aethelwulffe** [comment]
My Happy 4th was spent rebuilding the electrical and IT infrastructure of the building after massive lightning strikes, brown-outs and blackouts.  :fro  I will still be in short supply in the immediate future, at least until I get the building ventilation running again.  Love the PR though!

**Comment by teryhill** [comment]
@azwreith  Have you looked in to adding a mechanism for holidays to be set in the calendar?

**Comment by azwreith** [comment]
@teryhill You mean like public holidays? Are they common to providers or facilities? If they are common to ALL or common to all providers in a facility, we can just make a separate table to store clinic holidays and add it as an event source with to the calendar. (Well we can also use the current event table with the provider field empty). For setting holidays I was thinking we add a button (like the search button) which takes you to a page to do that. Of course the button should be visible only to administrators or some kind of authorized peeps right?
If holidays are unique to each provider it's just like vacation and we can just add a event category type for that.

**Comment by teryhill** [comment]
Yes public holidays that the clinic observes . Like in the US Thanksgiving, NewYears, Labor Day Memorial Day etc. Each clinic should be able to load the holiday and the system should automatically block that day. If a holiday occurs on a specific day Jan 1 or if there is a formula for arriving at it like the 3rd Thursday in November.

**Comment by teryhill** [comment]
The clinic should be able to load the holidays once and the calendar should block them automatically for each and every year.

**Comment by teryhill** [comment]
Have you decided how to do the wait list for the walk in clinics, I think this would be used in a variety of countries. Patients do not schedule appointments they just go to the clinic and are seen in the order that they arrived. We  call them "walk in clinics" here.

**Comment by teryhill** [comment]
@azwreith How are things going . Have you gotten into school?

**Comment by teryhill** [comment]
Closing this was a 2017 GSoC project.
