### ISSUE TITLE
Patient Billing Encounter by Carrier report

### ISSUE THREAD

**Issue by teryhill** [LibreHealthIO/LibreEHR#555]
I had a request for this report. It is based off the encounter report but it has more options. The billing person wanted it as a snapshot of what they were working on. It uses the table sort js so each column is sortable. Screen shot here.  Report Name could use some work!!!

![new_report](https://cloud.githubusercontent.com/assets/4655366/26561339/70aa0342-448b-11e7-98d1-20cb5c3a607e.JPG)

I also added the table sorting to the encounters report.

**Comment by tmccormi** [comment]
I've always wondered with that "Status" is based on.  What does "Open/Closed" mean.  Empty seems obvious (missing coding).

**Comment by teryhill** [comment]
Here is the logic from the code.

      if ($billed_count && $unbilled_count) $status = xl('Mixed' );
      else if ($billed_count              ) $status = xl('Closed');
      else if ($unbilled_count            ) $status = xl('Open'  );
      else                                  $status = xl('Empty' );
so if there are items that are billed and unbilled on the encounter it is mixed
if it is billed it is closed
if it is unbilled it is open
if none of these apply (no charge) it is empty.

Clear as MUD right?
