### ISSUE TITLE
Calling globals.php too much?

### ISSUE THREAD

**Issue by aethelwulffe** [LibreHealthIO/LibreEHR#567]
Why are we including globals.php in anything but interface/main/main.php or other scripts that may directly change the superglobal $GLOBALS[index] ?
  Perhaps it only works on localhost and not remote, but it seems like $GLOBALS works like you would expect it too...unless register_fake_globals or something like that does something foul with it.  Using it as we do seems to just be treating it as a public variable (available in all functions, but only within a given script).
  Localhost tests made by commenting out the include/require globals.php and echoing out a value seems to work, as does the rest of the script that depends on those values.
  I know I am no PHP guru, and I also know that anytime I look into this more, I realize that OO methods have replaced the use of superglobals in php for the most part, but if someone could tell me why I am wrongheaded about this, I would appreciate it.

**Comment by aethelwulffe** [comment]
This came up when Terry pointed out that I called globals.php by using `require_once $GLOBALS['rootdir'].'/globals.php';`  in tabs/main.php
  It seems to work for me.  I echoed out the values.  I also commented out the globals.php include, and everything still worked (that was actually setting $GLOBALS[] that is.

**Comment by aethelwulffe** [comment]
Is this stuff not kept in the session or cookie?

**Comment by tmccormi** [comment]
logically is seems like anything loaded by the main menu would already have globals included, but I am not a Computer Scientist...  You should only need to include globals if the program can be loaded "directly" by an external force (like a daemon or deity)

**Comment by aethelwulffe** [comment]
Then we call it unnecessarily in about 5000 places...

**Comment by teryhill** [comment]
I had to put the ../globals.php to get my system to run. It looks like it is needed even though it is in every program. I don't know if cache is helping Art , but I have yet to find a way around it. Main.prg definitely does not like being with out ../globals.php. I do not know enough about what globals.php does or doesn't do.

**Comment by teryhill** [comment]
So right now until main.prg is changed I think the repo is hosed.

**Comment by aethelwulffe** [comment]
Well, all we gotta do is get this commit merged, and it is all taken care of, right?

**Comment by kchapple** [comment]
The menu just generates links, the flow of execution doesn't actually go through the menu when you click on something. Each click is a new request, and since this is not an MVC program, each file needs to include globals.php because it contains all the database logic, authentication stuff and everything else that makes the system work.

**Comment by kchapple** [comment]
If it were MVC, then we could include globals.php only once and have some sort of dispatcher module dispatch the request to the appropriate file.

**Comment by teryhill** [comment]
Fixing Main now

**Comment by teryhill** [comment]
okay that should do it.

**Comment by aethelwulffe** [comment]
Closing this unanswerable unponderable. 😸
