### ISSUE TITLE
Move /patients to modules?  (Patient Portal question)

### ISSUE THREAD

**Issue by aethelwulffe** [LibreHealthIO/LibreEHR#576]
Should, as an optional module, Patient Portal and all it's libraries be moved into the Modules directory?
  It seems that since it requires a very static and already outdated patient_data table, we may need to refactor it quite soon anyway.  Some of it's functions and features may also be useful in other areas, and will need to start using some of the new core module (calendar, FHIR server etc...) features.

**Comment by teryhill** [comment]
Portal is pretty heavily interwoven with the core. Secure messaging sending invoices to the patient etc. The next step is to add the Kiosk functionality to it. It y'all think it needs to be a module them its ok by me go for it.
