### ISSUE TITLE
Customer request for Provider and Referring provider on billing search screen

### ISSUE THREAD

**Issue by teryhill** [LibreHealthIO/LibreEHR#579]
Had a customer request this so that they could divide the work load between billers. They also wanted referring for a lab that they do billing for.

@aethelwulffe I got the dropdowns working and this is pretty slick .

**Comment by aethelwulffe** [comment]
Gave review + test.

**Comment by aethelwulffe** [comment]
having the provider in the criteria is vital.  Sometimes you need to work a particular NPI a little differently.  Add other criteria and you get to a lot of granular issues that are a pain if you are billing out batches full of other provider's stuff.

**Comment by aethelwulffe** [comment]
Code + Modifier is a good criteria we use as well.  Code by itself is worse than useless.
