### ISSUE TITLE
Role based menus. 

### ISSUE THREAD

**Issue by teryhill** [LibreHealthIO/LibreEHR#584]
I have code from Dr Ray for role base menus that he uses in his practice If it would be a good fit for LibreHealth EHR with the UI changes let me Know and I will send it. @aethelwulffe @tmccormi @nileshprasad137

**Comment by teryhill** [comment]
No one interested in role based menus!!!

**Comment by aethelwulffe** [comment]
I thought I commented on this!  Yes, hell yes I want to see it.
