### ISSUE TITLE
Implement MIPS QA, IA and ACI measure forms

### ISSUE THREAD

**Issue by aethelwulffe** [LibreHealthIO/LibreEHR#588]
Intent:
Create Advancing Care Information and Improvement Activity measure reporting forms.
Ref:  https://qpp.cms.gov/mips/advancing-care-information

Methods:

Create ACI form to draw fields for the current 11 (15 for 2016) 2017 ACI measures published from a table containing the values exactly as published in CSV format (when you select and download all).
Include  the following elements:
- Provider (linked from clinical providers in system)
- toggle buttons to enable each desired measure 
- Generates list of measure questions for each selected measure.
- Stores values for each answer.
- Displays (report view) the selected measures and adds the "score weight" for the totals, in addition to all of the below.
-Represents 25% of the provider's total score.

Create IA form to draw fields from the current 92 IA measures stored in a table containing the values exactly as published in the CSV format when you select and download all from the CMS site.
Include the following elements:
- Provider (linked from clinical providers in system)
- toggle buttons to enable each desired measure (either two for small clinics, or 4 for larger ones)
- Generates list of measure questions for each selected measure.
- Stores values for each answer.
- Displays (report view) the selected measures and adds the "score weight" for the totals, in addition to all of the below.
-Represents 15% of the provider's total score.

The QA measures system (formerly PQRS) from the SCC tool (private repo) are Registry based measures, and not the EHR measures.  Some have cross-over, and a few will have to be added for full certification...which is trivial.  The relevant code must be pulled out of the existing SCC repo, modified heavily, then implemented as a module for performing measure calculation and reporting without requiring the very clunky CDR engine elements.
-Requires many additional tables that would best be in a separate database (PDO please), or at least tables that can be flushed after a reporting period.
-Is best implemented by replacing typical values from arbitrary layouts such as have been used in the CDR engine with either HCPCS and CPT2 codes, or better yet, a translatable code set stand-in API.
-This will represent 60% of the provider's total score.

**Comment by teryhill** [comment]
Sounds like a lot of work. What exactly ,in a small synopsis so I can get my pea brain around it, does this benefit the provider. Is this something to do with the CMS stuff like MU?

**Comment by aethelwulffe** [comment]
#630

**Comment by teryhill** [comment]
@aethelwulffe is this close-able

**Comment by aethelwulffe** [comment]
Yeah, closing.  The project is underway as I speak anyway.
I am a bit out of pocket right now due to the MIPS reporting season upon us.
