### ISSUE TITLE
Not able to open Miscellaneous/Preferences

### ISSUE THREAD

**Issue by nileshprasad137** [LibreHealthIO/LibreEHR#596]
Log shows ::
`Call to undefined function include_css_library()` inside `interface\super\edit_globals.php on line 269`

**Comment by teryhill** [comment]
make sure you have this file in /library headers.inc.php

**Comment by teryhill** [comment]
also this line in the requires of the program 

require_once $GLOBALS['srcdir'].'/headers.inc.php';

**Comment by nileshprasad137** [comment]
Its there already. It only contains ` include_js_library($path)` function in headers.inc.php currently. You can also verify that in our's master branch .

**Comment by nileshprasad137** [comment]
Is this relevant? #595 ?

**Comment by teryhill** [comment]
no it should contain more information than that.

<link rel="stylesheet" href="<?php echo $css_header;?>" type="text/css">
<?php
function include_js_library($path)
{
?>
<script type="text/javascript" src="<?php echo $GLOBALS['standard_js_path'].$path;?>"></script>
<?php
}
function include_css_library($path)
{
?>
<link rel="stylesheet" type="text/css" href="<?php echo $GLOBALS['css_path'].$path;?>" media="screen" />
<?php
}

?>
<script type="text/javascript" src="<?php echo $GLOBALS['webroot'] ?>/library/textformat.js"></script>
<script type="text/javascript" src="<?php echo $GLOBALS['webroot'] ?>/library/dialog.js"></script>

**Comment by teryhill** [comment]
Yes #595 is relevant

**Comment by teryhill** [comment]
@nileshprasad137 I just merged 595

**Comment by nileshprasad137** [comment]
Yes, it works fine now. Closing.
