### ISSUE TITLE
Fee Sheet Error

### ISSUE THREAD

**Issue by rehoyt** [LibreHealthIO/LibreEHR#603]
When the fee sheet is accessed in the NHANES_Demo here is the message

ERROR: query failed: SELECT provider_id, supervisor_id, ordering_physician, referring_physician, contract_physician FROM form_encounter WHERE pid = ? AND encounter = ? ORDER BY id DESC LIMIT 1

Error: Unknown column 'ordering_physician' in 'field list'

**Comment by aethelwulffe** [comment]
The fix for that has been in for a while.  Must not be updated on the demo.

**Comment by aethelwulffe** [comment]
@teryhill Is that in the sqlupgrade ?

**Comment by teryhill** [comment]
I think so

On Friday, June 30, 2017, 5:16:35 PM EDT, Art Eaton <notifications@github.com> wrote:


@teryhill Is that in the sqlupgrade ?

**Comment by teryhill** [comment]
Yes it is , run the upgrade

**Comment by rehoyt** [comment]
I hope the version we will offer faculty will have this as I know the HIM folks will want to go into billing. I doubt the others will

**Comment by teryhill** [comment]
@robbyoconnor running the upgrade script will take care of this error.

**Comment by robbyoconnor** [comment]
Where's the upgrade script?

**Comment by aethelwulffe** [comment]
/sql/upgrade.php

**Comment by aethelwulffe** [comment]
...or is is sqlupgrade....something like that.  Sorry, I barely got internet, and my whole building is lightning fried.

**Comment by robbyoconnor** [comment]
EHR and NHANES both updated. EHR was running an old version. Fixed and updated after error logs filled the disk up...deleted them and we're good now. 

About our setup on demo: We have two vhosts: `ehr.librehealth.io` and `nhanes.librehealth.io`

**Comment by robbyoconnor** [comment]
I'm going to let @aethelwulffe, @teryhill, or @tmccormi close this...but my work on this is done...

**Comment by teryhill** [comment]
This is resolved closing the issue
