### ISSUE TITLE
Patient Portal

### ISSUE THREAD

**Issue by rehoyt** [LibreHealthIO/LibreEHR#604]
What is the status of the patient portal? When I go to Miscellaneous >> portal dashboard that generates an Internal Server Error

**Comment by teryhill** [comment]
@robbyoconnor is rewrite turned on in Apache on the demo. Can you tell me what is in the phperror log or tell me how to access it.

**Comment by rehoyt** [comment]
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at infrastructure@librehealth.io to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

Apache/2.4.18 (Ubuntu) Server at nhanes.librehealth.io Port 443

**Comment by robbyoconnor** [comment]
https://gitlab.com/librehealth/community-infra/blob/master/ansible/host_vars/nhanes.librehealth.io

Whatever is there...I followed installation instructions

**Comment by robbyoconnor** [comment]
https://gitlab.com/librehealth/community-infra/blob/master/ansible/host_vars/nhanes.librehealth.io

Whatever is there...I followed installation instructions

**Comment by robbyoconnor** [comment]
https://gitlab.com/librehealth/community-infra/blob/master/ansible/host_vars/ehr.librehealth.io

Whatever is there...I followed installation instructions

**Comment by teryhill** [comment]
Try adding this

<Directory /var/www/>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
</Directory>

**Comment by robbyoconnor** [comment]
@teryhill when I get home. File a ticket on the community-infra project please

**Comment by robbyoconnor** [comment]
also that's not the webroot...

**Comment by teryhill** [comment]
Yes I know it is not . that fix is from another site.

**Comment by robbyoconnor** [comment]
just file a ticket so I don't forget.

**Comment by robbyoconnor** [comment]
or assign this issue.. either or works

**Comment by teryhill** [comment]
Also the upgrade script needs to be ran on the demo site, I could fix the issues with access to phpmyadmin. I am just not high enough in any order

**Comment by teryhill** [comment]
I assigned this to you @robbyoconnor

**Comment by rehoyt** [comment]
It looks like I first need to select that the patient wants to join the portal under Demographics >> Privacy. After that I see the option in the patient's summary to join the portal and it generates a username and password. It also generates a URL that appears to be incomplete at this time.
https://your_web_site.com/libreehr/patients

**Comment by robbyoconnor** [comment]
Do I need to do anything?

**Comment by teryhill** [comment]
That is setup in globals. The end user would add their portal address. There is a number of items that the user can setup. Globals would be a good thing for you to look at and see if it generates any questions. I am pretty sure that once robby does his thing with setting up the rewrite options portal should work.

**Comment by teryhill** [comment]
@robbyoconnor we will need a portal address. I test on my local system as localhost which you cannot do.

**Comment by robbyoconnor** [comment]
@rehoyt, @teryhill try now. 

https://gitlab.com/librehealth/community-infra/commit/1e8c3c7351ad2bd66d90333009ce315a071743eb

**Comment by teryhill** [comment]
@robbyoconnor can you setup a address for the portal?
Not sure what everyone would like to call it.
https://your_your_web_site.com/libreehr/patients

**Comment by robbyoconnor** [comment]
Sure - remind me if I don't get to in a couple days

**Comment by robbyoconnor** [comment]
@teryhill you assume I have a clue about LibreEHR -- you're going to need to tell me what it needs to point to.

**Comment by teryhill** [comment]
https://your_web_site.com/libreehr/patients. Where your_web_site.com is the address of the server/website.

**Comment by robbyoconnor** [comment]
https://ehr.librehealth.io/patients
https://nhanes.librehealth.io/patients 

Both of those work

**Comment by robbyoconnor** [comment]
I just tested this -- This is fixed.

**Comment by robbyoconnor** [comment]
@teryhill, @aethelwulffe, @tmccormi -- I don't like touching issues on the projects which I don't maintain...but issue is done
