### ISSUE TITLE
Problem Adding New Facility

### ISSUE THREAD

**Issue by rehoyt** [LibreHealthIO/LibreEHR#605]
In the demo I can't add a new facility. I was thinking that perhaps that was the problem with appointments that don't seem to work

**Comment by teryhill** [comment]
I added a new facility with no issues. called it new facility

**Comment by rehoyt** [comment]
It looks like I needed to pick a color. After doing that I now see Lake Sumter Clinic. Thanks

**Comment by teryhill** [comment]
@rehoyt Do you feel this issue is resolved?

**Comment by rehoyt** [comment]
Now New Facility is the only choice I see, even though I created the Lake Sumter Clinic and it was accepted. Not sure why I don't see my clinic in the drop down menu when I schedule an appointment. I did re-login and refresh with no change

**Comment by teryhill** [comment]
Look now

**Comment by teryhill** [comment]
The box service location needed to be checked.

**Comment by rehoyt** [comment]
Thanks. I now see that is where I would also check "billing facility"

**Comment by teryhill** [comment]
If it is the billing location , then yes the end user would check it. There is should only be 1 billing location in the system.

**Comment by teryhill** [comment]
See if this will help in the future. May it will be a starting point. It will need to be un-zipped.

[facility.zip](https://github.com/LibreHealthIO/LibreEHR/files/1117382/facility.zip)

**Comment by rehoyt** [comment]
Thanks. I want to be sure Lake Sumter Clinic has billing set up correctly because they are likely the first college to use the educational version and they will be using coding and billing so this needs to be right

**Comment by teryhill** [comment]
Issue should be resolved closing.
