### ISSUE TITLE
Are Risk Factors Editable?

### ISSUE THREAD

**Issue by rehoyt** [LibreHealthIO/LibreEHR#606]
When I go to History >> General and select "edit" I see a list of risk factors. Can this be edited as I don't see obesity as just one example. I didn't find it under the "Lists" in admin either

**Comment by teryhill** [comment]
obesity added to the risk Factors list

**Comment by teryhill** [comment]
The other tabs can be changes via globals=>layouts. The layout is called History

**Comment by teryhill** [comment]
Opened an issue for date picker not working on life styles.

**Comment by teryhill** [comment]
Issue should be resolved, closing .
