### ISSUE TITLE
Life styles in patient history needs date picker updated

### ISSUE THREAD

**Issue by teryhill** [LibreHealthIO/LibreEHR#607]
Noticed this while looking at questions raised by @rehoyt . Will look at this as I can.

**Comment by nileshprasad137** [comment]
Will look at this.

**Comment by nileshprasad137** [comment]
@teryhill I have fixed this on my system. Will send the PR when my Prescription PR gets merged.. Or should I send a commit fixing it on that PR itself?

**Comment by nileshprasad137** [comment]
I am afraid that if I send a new PR now, that might cause a conflict later..

**Comment by teryhill** [comment]
Send the or we will deal with any conflicts later.

**Comment by nileshprasad137** [comment]
Closing this as it is resolved.

**Comment by nileshprasad137** [comment]
Oh , there isn't a button here to close.  Maybe you would have to do it. @teryhill
