### ISSUE TITLE
Race vs Ethnicity

### ISSUE THREAD

**Issue by rehoyt** [LibreHealthIO/LibreEHR#608]
When I go to Reports >> Client >> Clinical to search, for example for patients with diabetes (ICD-10 = E11.9) I have no problem finding them based on age and gender. When I select anything in the race category, I get no results. On the other hand, when I select Non-Hispanic black under ethnicity I get results. Does that mean that NHANES racial characteristics were uploaded to ethnicity?

**Comment by yehster** [comment]
Yes, that is correct. I used the "ethnicity" column for the NHANES data.  This is again one of the odd quirks of the system that both exist, and "Ethnicity" is the one that is part of the demographics information by default.

**Comment by aethelwulffe** [comment]
I will refer this to the database refactor issue and PR
#599
