### ISSUE TITLE
Comprehensive Search Capability

### ISSUE THREAD

**Issue by rehoyt** [LibreHealthIO/LibreEHR#609]
I think when we speak to potential industry partners (like IBM) it would be important to be able to describe the potential of LibreHealth EHR to perform analytics for a subgroup of users interested in research. We have started to talk about what it would take to enable SQL queries. That's great, but I wonder about the low hanging fruit of being able to generate a comprehensive report that is downloadable as a CSV file (and imported into IBM Watson Analytics, as just one example). 

I realize that this requires a lot of programming hours but would likely have a lot of downstream payoff. For example, now that we have lab cut off values, it would be great to search for those patients with a glycohemoglobin (A1c) > 7 who are not on metformin. I can think of many more examples or scenarios. Can anyone put a price tag on this (approximately), in case someone like IBM would be interested in funding the enhancement?

**Comment by teryhill** [comment]
Developing/adding a report generator to the package would be beneficial from an end user standpoint. It has been discussed between us and it is agreed that it would be good to have, we just have not progressed to the design/research stage yet. If it is wanted it will never get done if we wait on funding. (IMHO)

**Comment by teryhill** [comment]
This is one I found that might work http://www.reportico.org/site/index.php

**Comment by rehoyt** [comment]
I have no problem discussing this with IBM on Thursday. The last time IBM funded me it was almost immediate payment. If for any reason IBM does not want to be a partner, I will then contact Wolters-Kluwer because of their heavy involvement in health education. 

Do you have any ball park idea what this might cost in programming time; if you used reportico? I told Kevin that I would be willing to fund some projects if they are in the $1-5K range.

**Comment by teryhill** [comment]
I would think some where in the 3-4k range for a price to do the work. That is an off the cuff estimate maybe @yehster , @tmccormi  or @aethelwulffe  would like to weigh in on this. They had a better grasp on the overall project that I do.

**Comment by yehster** [comment]
There is a very large "upfront" cost for building a generic reporting tool.  It's also very hard to anticipate possible queries of interest.  To make it possible for a "lay person" to be able to easily find data of interest is honestly not something I would consider "low hanging" fruit.  The "clinical report" that already exists in the application doesn't accomplish nearly what I suspect we would need and it has fairly significant development effort sunk into it already.

My suggestion is that we start by setting up PHPMyAdmin on our educational system to provide read-only SQL Query access.  Learning how to run basic SQL queries feels like a valuable lesson for students, and could be part of the curriculum.  We can start to identify the kinds of information that would be useful and include that as part of the requirements for a generic reporting tool down the road, and we can explore this as a combination of "give a man a fish/teach a man to fish" sorts of exercises :)

**Comment by rehoyt** [comment]
There is no question that SQL queries are the method of choice for most data science explorations. Perhaps if we made the process as easy as possible with PHPMyAdmin, we can encourage those interested in research to proceed in that direction. 

Maybe down the road with further input from surveys and funding we can actually find out what faculty actually need/want with an educational EHR

**Comment by aethelwulffe** [comment]
I find that anyone doing real data science typically HAS some sort of database experience, there therefore the ability to find and use a professional level toolset to do so.  I find the needs of clinical and administrative (billing etc.) use to require much more pre-set means of collating and presenting data.
  As this is a discussion, I am closing this issue.  It is already being discussed on the forum.
