### ISSUE TITLE
SNOMED CT

### ISSUE THREAD

**Issue by rehoyt** [LibreHealthIO/LibreEHR#616]
The only place in the EHR I find SNOMED CT coding is tobacco use. Is this correct? The HIM folks may want to know this

**Comment by tmccormi** [comment]
SNOMED can be used everywhere, but it's not useful for billing in the USA, so it's not frequently activated for general use

**Comment by rehoyt** [comment]
Thanks Tony. That is my impression as well but this might come up with my HIM friends
