### ISSUE TITLE
Patient List Creation Issues

### ISSUE THREAD

**Issue by rehoyt** [LibreHealthIO/LibreEHR#617]
The font for this search engine is now white and extremely difficult to see. Also, the search for lab results does not appear to work, which is an issue. The search option for communications isn't working, probably not an issue

**Comment by teryhill** [comment]
Try changing your theme. Got to Miscellaneous then Preferences and select the theme drop down. Metal is a darker theme.

**Comment by rehoyt** [comment]
It is set on metal. It is the only window where the font is in white rather than black

**Comment by teryhill** [comment]
I will look at it as soon as I can.  Do you have a priority list? I will be glad to look over you documentation if you would like for me to.

**Comment by rehoyt** [comment]
[EHR Tutorial Student #1.docx](https://github.com/LibreHealthIO/LibreEHR/files/1143098/EHR.Tutorial.Student.1.docx)
[EHR Tutorial Instructor.docx](https://github.com/LibreHealthIO/LibreEHR/files/1143100/EHR.Tutorial.Instructor.docx)
These are rough drafts. I am planning two more guides. One will be creating a new patient and adding diagnoses, meds, images, allergies, etc. etc. Lastly, I want to create one of more complex exercises. My wife is working on a scavenger hunt to be sure students can prove they know how to navigate the EHR

**Comment by teryhill** [comment]
This is caused by some work in the header file . It should be corrected when the PR for that is added to the repo and the nanes site is updated.

**Comment by rehoyt** [comment]
I do plan to use Patient List for denominator stats but I don't think students can see the white font. See screen shot
![patient list](https://user-images.githubusercontent.com/25651922/28275979-303e62be-6adb-11e7-9a38-f33142ca51de.png)

**Comment by teryhill** [comment]
@tmccormi or @aethelwulffe  The header changes to remove the bootstrap items that load by default need to be added to the code base to fix these issues. This is included in the prescription changes by @nileshprasad137 .

**Comment by aethelwulffe** [comment]
Then please do the second look at that PR and merge it.  I made a note to that effect.  Tony has lead on that, but we are the ones here today...and that code has been there for a bit.

**Comment by teryhill** [comment]
This appears to be fixed in my system with Niles PR. @tmccormi  @rehoyt and @aethelwulffe  do you want  @robbyoconnor to update the demos with the latest release? @rehoyt will need to check his documentation against the new code to make sure everything works or may be there needs to be a staged release to just the ehr demo site and not the nhanes site.

**Comment by rehoyt** [comment]
Just checked patient list creation and the font is still white. I assume the demo was not updated yet?

**Comment by robbyoconnor** [comment]
Updated.

**Comment by robbyoconnor** [comment]
Updated @teryhill -- close this issue at will.

**Comment by rehoyt** [comment]
Fixed. Thanks
