### ISSUE TITLE
CCR and CCD reports

### ISSUE THREAD

**Issue by rehoyt** [LibreHealthIO/LibreEHR#623]
When I tried to create an assignment about downloading a CCD or CCR, when I select the download button for each it states "missing the ziparchive PHP module". It does say popups must be enabled and in globals that box is checked. 

The Patient Report is confusing. If I just completed an encounter for e.g. acute bronchitis how can I just print that out or create a CCD of just that for sending to a specialist?

**Comment by teryhill** [comment]
Enable popups on your web browser. I will check check this when I get a chance. @robbyoconnor can you check on the "missing the ziparchive PHP module"

**Comment by teryhill** [comment]
It looks like you just need to enable popups in your browser. @robbyoconnor no issue on the demo site or nhanes site

**Comment by teryhill** [comment]
Sorry  @robbyoconnor can you check on the "missing the ziparchive PHP module" it is the download that is using it

**Comment by robbyoconnor** [comment]
@teryhill added.

**Comment by rehoyt** [comment]
The CCD now downloads as a XML file, as expected. I was unable to open it with either Chrome or Safari. Thoughts?

**Comment by yehster** [comment]
Likely cause for the "problems" not displaying is that the report was never updated to handle ICD-10 instead of ICD-9.  

Labs appear to be working properly at this point.

**Comment by yehster** [comment]
Found the offending code where problems are hard coded to ICD9.  More testing required to look for other quirks will update when ready.

**Comment by yehster** [comment]
Pull request created to change from ICD9 to ICD10

**Comment by robbyoconnor** [comment]
For housekeeping, just linking: https://github.com/LibreHealthIO/LibreEHR/pull/635/

**Comment by teryhill** [comment]
Pr Merged closing issue
