### ISSUE TITLE
Is this project on Laravel or Core PHP

### ISSUE THREAD

**Issue by ankitjain28may** [LibreHealthIO/LibreEHR#624]
I would like to contribute on this project, can you please guide from where should i start contributing ?

**Comment by teryhill** [comment]
Down load the code and install it locally. Then look at the current issues and ask about what you would like to work on. And have Fun.

**Comment by tmccormi** [comment]
It's currently core PHP, with some things that are and will be Laravel.  In the future use the Forum for general questions.  Issue are for bugs and development work.  see - http://librehealth.io

Thanks and Welcome.
