### ISSUE TITLE
Patient Portal URL

### ISSUE THREAD

**Issue by rehoyt** [LibreHealthIO/LibreEHR#626]
I am writing a patient portal exercise. Do we have a portal URL yet?

**Comment by yehster** [comment]
I updated the configuration with the correct url.
https://nhanes.librehealth.io/patients

**Comment by rehoyt** [comment]
Great. The only issue I see is that the actual lab results do not port over. You can see that they got the NHANES panel but no actual results.
In another post, I mentioned that the medical problems are not showing up in CCDs which is an issue

**Comment by yehster** [comment]
![ccdtest](https://user-images.githubusercontent.com/302795/28292825-f98f54c8-6b1e-11e7-9ffa-541d8d4e24a5.gif)
This screen has lab results.  Is there a different one you are looking at where they are still missing?

**Comment by rehoyt** [comment]
I think what the problem was that there are a lot of lab reports with no results. So I saw several that showed the units but no results. For example, what I see is 17 potential lab results on e.g. Steve Abbott but only about half show results. Thanks.

**Comment by yehster** [comment]
Not the simplest task, but instead of having one single lab panel for all of the NHANES results, splitting them up separately based on the original data files would probably be better.
e.g. CBC, triglycerides, hdl and total cholesterol, etc. could be listed as separate procedure orders.
This way, total cholesterol would be listed for all of the ~6000+ patients where it's available, and triglycerides will only be displayed for the 3000 with results.

**Comment by rehoyt** [comment]
I think we need to do that and whenever we have the time and money create the tools to search for individual labs. This would expand our teaching capabilities. Example, find every diabetic with a creatinine > 2. Today I'm going to see how productive it is to search for chronic renal disease and see what I get. My HIM friend would like the ability to go over some of these patients with students and ask how the coding (ICD-10) could be improved

**Comment by rehoyt** [comment]
I did find 19 patients on renal dialysis so created an exercise based on these patients

**Comment by yehster** [comment]
Going to start looking into splitting the labs up into separate panels.  At present there are 10 tables from NHANES.  So this means needing to create 10 new procedure orders to start.  Going to see if I can create the procedure orders programmatically which will make introducing new lab data in the future simpler as well.

**Comment by teryhill** [comment]
@yehster Is this still an active Issue. It is a little misleading as a portal issue. Maybe you could close it and open one that better describes the issue.
