### ISSUE TITLE
Home for User Manuals

### ISSUE THREAD

**Issue by rehoyt** [LibreHealthIO/LibreEHR#627]
How might we re-configure the Help menu, such that when a user clicks on User Manual it would take them to the 4 PDFs I am creating?

**Comment by teryhill** [comment]
That link is configured partly in the code and in globals.

**Comment by rehoyt** [comment]
Could not find it in globals. I'll post the Instructional PDFs shortly in the Forum, but having them under the Help menu would not be unreasonable

**Comment by teryhill** [comment]
The way the link is designed is to point to a section of the librehealth.io website so it would be advantageous to add the documents to (where ever they are) the wiki pages

**Comment by rehoyt** [comment]
Ok. I was thinking about adding a new section to the Education section of the Forum for User Manuals so that would work

**Comment by teryhill** [comment]
The location the code looks for is "https://forums.librehealth.io/c/7-support".attr($v_major).".".attr($v_minor).".".attr($v_patch)."_Users_Guide";

**Comment by aethelwulffe** [comment]
@rehoyt  and everyone else.  We need to also find a home for public (out of application) access and display of documentation _and a home for video presentations and instructables._  We want it all grouped somehow, or under a single publisher/account.

**Comment by tmccormi** [comment]
Let's post on the Forum and see if the project has/wants a youtube account (or something similar)   The documentation should be publically accessible outside of the installed apps.  On the project website in some fashion

**Comment by teryhill** [comment]
Closing youtube channel is up and wiki is agreed upon.
