### ISSUE TITLE
Nation Notes

### ISSUE THREAD

**Issue by rehoyt** [LibreHealthIO/LibreEHR#629]
I saw that OpenEMR offers Nation Notes which means a slightly customizable SOAP note. Does anyone have feedback on whether this form option was successful or not?

**Comment by aethelwulffe** [comment]
NationNotes is a module in LHEHR.  It has to be turned on to use.  It is really just a text-field datatype that gives you some other text-editor like options.  It is, for the most part, very clunky compared to actually creating a real form.
  There really isn't much of a shortcut to creating a quality form with direct attention to design.

**Comment by aethelwulffe** [comment]
Answered?
@rehoyt if you could please add the label "question", "Bug" etc... to issues it would be very helpful.  If you CANNOT, then we need to bump up your access here!

**Comment by rehoyt** [comment]
Ok. I'm new to this forum so will look for labels. Thanks
