### ISSUE TITLE
Console error - Not able to load "modules/openflashchart/js/json/json2.js"

### ISSUE THREAD

**Issue by nileshprasad137** [LibreHealthIO/LibreEHR#640]
This error shows up on Encounter details screen
`Not allowed to load local resource: file:///C:/wamp64/www/LibreEHR/modules/openflashchart/js/json/json2.js`

**Comment by nileshprasad137** [comment]
Oh , I figured this out. It was because  of `$GLOBALS['modules_dir']  = "$webserver_root/modules/";` in globals.php . Using $web_root in place of $webserver_root resolves this. I'll send this up in my next PR soon.

**Comment by aethelwulffe** [comment]
HA!  I used $web_root originally, then we changed that because someone told me it didn't exist...and I looked and assumed it was a typo of mine!
HA!

**Comment by aethelwulffe** [comment]
On second thought, that would not have gotten noticed (I think) unless it was breaking something else...
Is it possible that $webserver_root is out of scope somewhere because globals were not included somewhere?
  @teryhill , do you remember this?

**Comment by teryhill** [comment]
It is breaking the preprinted cms1500 form. I vaguely remember a discussion about this.

**Comment by nileshprasad137** [comment]
@teryhill I had not tested it with Nation Notes. How to check it using that?

**Comment by teryhill** [comment]
You will need to enable the nations note's module. That is in globals, then create a layout based form and set a type to nations note, like you would set a type to "listbox"

**Comment by nileshprasad137** [comment]
@teryhill I tried testing by putting `$GLOBALS['mod_nn'] = 1;` in `globals.php`. But after that, a lot of frames throwed up Internal Server Error like Administration/lists, administration/layouts. 

If I was supposed to enable nation notes using Administration/globals in UI , I couldn't find any tab for Nation Notes. I tried searching from search box, but couldn't find it.

**Comment by aethelwulffe** [comment]
Well, that sounds bad.
Likely, the fact that the NN module replaces whole script versions when it is on, and those module versions of the same scripts have not been updated to the new UI and asset locations, things may now be broken.

**Comment by teryhill** [comment]
@aethelwulffe should this issue be closed and another opened for the NN issues?

**Comment by aethelwulffe** [comment]
Yes, unless we already have one for that.

**Comment by teryhill** [comment]
Will test nation notes and open an issue if needed
