### ISSUE TITLE
Installation instructions of README.md file

### ISSUE THREAD

**Issue by eran13com** [LibreHealthIO/LibreEHR#642]
This may not be a big issue but in the README.md (https://github.com/LibreHealthIO/LibreEHR/blob/master/README.md) there is a slight error. In that the path of the php.ini file for the wamp server is correct. i. e **C:/WAMP/BIN/PHP/php.ini** but the path for the php.ini file in the xampp server should be corrected as  **C:\xampp\php\php.ini**. 
![php](https://user-images.githubusercontent.com/25362586/28611558-c4f3973c-7209-11e7-845d-c2f4b508f077.PNG)

**Comment by nileshprasad137** [comment]
Oh yes.  This is silly. You may fix this.

**Comment by eran13com** [comment]
Sure

**Comment by teryhill** [comment]
Merged PR
