### ISSUE TITLE
Immunization Issue

### ISSUE THREAD

**Issue by pri2si17-1997** [LibreHealthIO/LibreEHR#645]
Hello @aethelwulffe @teryhill 

When I click on any immunization, to view/edit, I get a blank screen.

Here is the screen shot of the same : 
![screenshot from 2017-07-26 18-51-06](https://user-images.githubusercontent.com/12952169/28623924-099b1858-7235-11e7-81df-fc215d000e1d.png)

I tried this on nhance.librehealth.io, but there also I am getting this error. 

Here is PHP error log on my machine : 

> [Wed Jul 26 18:50:48.187284 2017] [:error] [pid 21559] [client 127.0.0.1:36062] PHP Fatal error:  Uncaught Error: Call to undefined function getImmunizationObservationResults() in /var/www/html/LibreEHR/interface/patient_file/summary/immunizations.php:170\nStack trace:\n#0 {main}\n  thrown in /var/www/html/LibreEHR/interface/patient_file/summary/immunizations.php on line 170, referer: http://localhost/LibreEHR/interface/main/tabs/main.php?url=TAB_ONE_DEFAULT

**Comment by teryhill** [comment]
@pri2si17-1997 Remove line 170. I sent a PR with that fix.

**Comment by aethelwulffe** [comment]
This is fixed.
