### ISSUE TITLE
REl 101 - unable to add a patient

### ISSUE THREAD

**Issue by tmccormi** [LibreHealthIO/LibreEHR#652]
Has anyone seen this issue?
<pre>
ERROR: insert failed: INSERT INTO patient_data SET pid = '1', date = NOW(), `fname` = 'Tony', `mname` = '', `lname` = 'McCormick', `sex` = 'Male', `DOB` = '1961-01-12', `status` = '', `street` = '11725 SW Springwood Dr', `city` = 'Tigard', `state` = 'OR', `postal_code` = '97223', `ss` = '', `drivers_license` = '', `phone_cell` = '5033302239', `email` = 'tony@mi-squared.com', `billing_note` = '', `providerID` = '', `ref_providerID` = '', `pharmacy_id` = '0', `phone_home` = '5033302239', `phone_biz` = '', `contact_relationship` = '', `phone_contact` = '', `mothersname` = '', `guardiansname` = '', `county` = '', `country_code` = 'USA', `referral_source` = '', `allow_patient_portal` = '', `email_direct` = '', `hipaa_notice` = '', `hipaa_voice` = '', `hipaa_message` = '', `hipaa_mail` = '', `hipaa_allowsms` = '', `hipaa_allowemail` = '', `allow_imm_reg_use` = '', `allow_imm_info_share` = '', `allow_health_info_ex` = '', `vfc` = '', `deceased_date` = '', `deceased_reason` = '', `industry` = '', `occupation` = '', `language` = '', `interpretter` = '', `ethnicity` = '', `family_size` = '', `financial_review` = '', `monthly_income` = '', `homeless` = '', `migrantseasonal` = '', `religion` = ''

Error: Incorrect integer value: '' for column 'providerID' at row 1

/var/www/html/libreehr101/library/patient.inc at 1091:sqlInsert
/var/www/html/libreehr101/interface/new/new_comprehensive_save.php at 70:updatePatientData(1,Array,1)
</pre>

**Comment by tmccormi** [comment]
Both providerID and re_providerID are ints with NULL defaults and this code is trying to write a blank string...

**Comment by tmccormi** [comment]
There is no difference in the code for master.  So this will break on MySQL 5.7 for the master as well.

**Comment by tmccormi** [comment]
This is the same issue from #254 - strict mode.

**Comment by teryhill** [comment]
Works fine on my local system and on the Nhanes demo site.

**Comment by tmccormi** [comment]
fixed with the mod to my.cnf
<pre>
[mysqld]
sql_mode = ""
</pre>

**Comment by aethelwulffe** [comment]
Well, since the provider ID isn't being set, I guess that is an issue.

Where was that from?

**Comment by tmccormi** [comment]
Mostly the issue is that we shouldn't have to set sql_mode.  Need to make sure that is not needed. 

I was doing a test install and setup of rel101 for my Ireland customer.
