### ISSUE TITLE
Change prescriptions to mediations

### ISSUE THREAD

**Issue by rehoyt** [LibreHealthIO/LibreEHR#656]
It is my understanding that you can't search on medications because they are prescriptions

**Comment by teryhill** [comment]
In the patient list creation this is what I get, if this is where you are talking about.

![image](https://user-images.githubusercontent.com/4655366/28999589-49c0dd3c-7a19-11e7-9d7a-09cd3354fa62.png)

**Comment by rehoyt** [comment]
I stand corrected because the search for medications did work. It is the search for lab results that does not. It would still be great if the output included a csv file so students might be able to analyze all patients on a certain drug

**Comment by aethelwulffe** [comment]
If, for instance, we use the standardized medical coding systems for medications, therapies, labs, and lab result reporting, then there would be nothing...nothing we could not easily run reports on.
