### ISSUE TITLE
Ability to search for lab results under "Clinical" reports

### ISSUE THREAD

**Issue by rehoyt** [LibreHealthIO/LibreEHR#658]

**Comment by aethelwulffe** [comment]
Lab results reporting should be part of a lab interface system connected to Quest and the other usual suspects.

Currently, the only lab related stuff is under the Procedures tab, where there are five or six lab related thingies, one of which being Procedure Results, which seems to actually reference to lab stuff.

  I know that you have to load a lab order compendium from a vendor and all that to get more of this to work, and I have never had access to any of that stuff.
