### ISSUE TITLE
New UI, Menu items duplicated

### ISSUE THREAD

**Issue by tmccormi** [LibreHealthIO/LibreEHR#663]
The Admin menu has duplicated selections on the nilesh/navbar-temp (and flowboard) branches
![redundant-admin-menu](https://user-images.githubusercontent.com/285835/29150508-dc4f74e2-7d2f-11e7-9194-30e48c52daca.png)

**Comment by nileshprasad137** [comment]
Fixed. 😃

**Comment by aethelwulffe** [comment]
Nilesh, was there a PR to the project for this?

**Comment by nileshprasad137** [comment]
Yes this is resolved.

**Comment by aethelwulffe** [comment]
Ah, I just couldn't locate the merge commit.  Closing.

**Comment by nileshprasad137** [comment]
Maybe we should introduce some template for sending PR messages similar to
what some popular open source projects like Joomla does..
