### ISSUE TITLE
call_required_libraries is badly implemented (not self documenting)

### ISSUE THREAD

**Issue by tmccormi** [LibreHealthIO/LibreEHR#668]
In my opinion:
  **This is bad:**  call_required_libraries(true,false,false,false);  //impossible to know at a glance what is being included

  **This better:**  call_required_libraries(bootstrap=true,
                                        fancybox=false,
                                        knockout=false,
                                        datepicker=false);
  
  Or maybe use constants
  add this to header.inc.php
  define (BOOTSTRAP,true);
  define (FANCYBOX,true);
  define (KNOCKOUT,true);
  define (DATEPICKER,true);
  
  Modify the function:
  function call_required_libraries($bootstrap=false,$fancybox=false,$knockout=false,$datepicker=false)
  
  Then use the call like this:
  
 call_required_libraries(BOOTSTRAP);

**Comment by tmccormi** [comment]
It would even nicer if the function was not ORDER dependent in the arguments.

**Comment by aethelwulffe** [comment]
Agreed.

My instinct is to not use constants, just arguments to the function, but 
I think either way is good.  I like the all caps constants pretty 
good...certainly simpler to implement.  This is what I imagined it being 
from the beginning.

**Comment by aethelwulffe** [comment]
function F($params) {
   if(!is_array($params)) return false;
   //do something with $params['A'], etc...
}

You could then invoke it like this:

F(array('C' => 3, 'A' => 1, 'B' => 1));

**Comment by teryhill** [comment]
I would suggest lowercase as opposed to upper case. Some times it just acts funny to have them UC.

**Comment by tmccormi** [comment]
The standard for industry constants is uppercase, just saying.   but as long as it's obvious what is being included I'm good.

**Comment by aethelwulffe** [comment]
Uh, which industry.  +this-is-a-constant+, kThisIsOneToo, so_IS_This_One, AND_THIS_ONE_IS_JAVA.

PHP constant that is used in more than one class is all caps.  The singletons are lowercase...by the recommendation guide.

**Comment by tmccormi** [comment]
This one:  PHP constant that is used in more than one class is all caps. The singletons are lowercase...by the recommendation guide.  

I wasn't aware of the singleton recommendation.  Nice to know

**Comment by nileshprasad137** [comment]
Ok, I'll implement this properly in some time. (Mostly next week)

**Comment by Trodrige** [comment]
@nileshprasad137, @tmccormi I would like to implement this. If it's ok by @nileshprasad137

**Comment by nileshprasad137** [comment]
Firstly I apologize for not implementing it properly. 

Feel free to implement it. I'm busy with academics currently because of my approaching mid terms.

**Comment by aethelwulffe** [comment]
All done I think.  More will be added to this function (I am sure).

**Comment by aethelwulffe** [comment]
My mistake!
Looks like not all instances of call_required_libraries() were updated.
Look at interface/usergroup/facilities.php

**Comment by Trodrige** [comment]
There's no instance of call_required_libraries() in my local interface/usergroup/facilities.php file. However, I have Fancybox included with these lines 
`<link rel="stylesheet" type="text/css" href="<?php echo $GLOBALS['webroot'] ?>/library/js/fancybox/jquery.fancybox-1.2.6.css" media="screen" />`
and
`<script type="text/javascript" src="<?php echo $GLOBALS['webroot'] ?>/library/js/fancybox/jquery.fancybox-1.2.6.js"></script>`

**Comment by aethelwulffe** [comment]
Check line 103 in interface/usergroup/facilities.php.
I swear I ain't foolin' bro 😄 

![image](https://user-images.githubusercontent.com/553751/30788202-54e0ef80-a166-11e7-92d4-dade556c351f.png)

**Comment by aethelwulffe** [comment]
And yes Trodrige (welcome aboard dude!), there are LOTS of other places that could use some help in this same way.  We were kind of trying to go along one point at a time and move the 3rd party libraries to rootdir/assets, then point at them with this function, so lots of stuff isn't implemented...and thank you so much for pitching in like this.
 
I hadn't had a chance to welcome you yet TRK, and I do so now.  Should be pretty plain to see how badly we need you.

**Comment by teryhill** [comment]
Here here we need all the help we can get.

**Comment by aethelwulffe** [comment]
@nileshprasad137  Apologizing for "not implementing it properly"?  Uh, more like thanks for implementing it period!  Along with the boat-load of other stuff you have done!

**Comment by Trodrige** [comment]
Thanks, @aethelwulffe and @teryhill for the welcome.

**Comment by Trodrige** [comment]
@aethelwulffe this is my facilities.php file
![facilities php-screenshot](https://user-images.githubusercontent.com/16147419/30788358-166a7168-a193-11e7-8b55-da37d74deb9c.png)

**Comment by aethelwulffe** [comment]
Gotcha.
Looks like your repo may not be up-to-date.
Look here: https://github.com/LibreHealthIO/LibreEHR/blob/master/interface/usergroup/facilities.php

Try updating your fork/branch to the latest /master, then you can start a new feature branch and search for this stuff again.  

This was the commit that had it in it, merged on August 21.

**Comment by aethelwulffe** [comment]
https://github.com/LibreHealthIO/LibreEHR/commit/7e173048bc97f1940cd6cc35317f4eb9b76ada0b

**Comment by teryhill** [comment]
Getting error from the commit

[24-Sep-2017 21:16:25 America/New_York] PHP Parse error:  syntax error, unexpected '=' in C:\xampp\htdocs\LibreEHR\interface\super\edit_globals.php on line 260

**Comment by teryhill** [comment]
Fixed it on my system by changing it to this @Trodrige 

   call_required_libraries($bootstrap=true,$fancybox=true,$knockout=false,$datepicker=false);

**Comment by aethelwulffe** [comment]
Ditto.
Maybe we should revert this commit?
@Trodrige We sort of failed you on this one.  Let's revert and try again.  It is mashing up some stuff on the demos.  I feel like a total doof. 🙃

**Comment by Trodrige** [comment]
Ok, I see

**Comment by aethelwulffe** [comment]
Put in a PR for a revert...I obviously have no business merging anything right now!

We might want to think about using a fake named parameter scheme like was outlined at the top of this issue.
Stick with us @Trodrige !

**Comment by aethelwulffe** [comment]
Trial by fire bro...

**Comment by Trodrige** [comment]
@aethelwulffe I don't get you here

Put in a PR for a revert...I obviously have no business merging anything right now!

We might want to think about using a fake named parameter scheme like was outlined at the top of this issue.

**Comment by aethelwulffe** [comment]
Oh, don't worry about that @Trodrige .  The sentence was supposed to say "**_I_** put in a pull request for a revert".  Meaning, Hey, @teryhill look over the revert and see if we should do that".  The other thing about named parameters is also not to be worried about.

**Comment by aethelwulffe** [comment]
We will get it worked out.  You think you would like to make another go of this tonight to get it straight, or should we revert this (it is affecting the demo system) and have you start over with a new up-to-date branch tomorrow?

**Comment by Trodrige** [comment]
Now is fine. If I get you correctly
1. create a branch
2. make changes the files with the function

**Comment by aethelwulffe** [comment]
Pull down master (update your repo).  Make sure you are in sync with upstream.
Create a branch
Make the changes, and GREP for more instances of the function.

Looks like the version you are on was between two commits that added this function, which is why you have some of them, and not the ones in that file I mentioned.

**Comment by aethelwulffe** [comment]
Let us know if you have any issues we can help with.

**Comment by Trodrige** [comment]
_Make the changes, and GREP for more instances of the function._
@aethelwulffe do you want me to change these:
`call_required_libraries(bootstrap=true,fancybox=true,knockout=false,datepicker=false);`
back to these: `call_required_libraries(true,true,false,false);`
Please be explicit on this. Not sure which is affecting the demo. Thanks

**Comment by teryhill** [comment]
@Trodrige change this 
call_required_libraries(bootstrap=true,fancybox=true,knockout=false,datepicker=false);
to this
call_required_libraries($bootstrap=true,$fancybox=true,$knockout=false,$datepicker=false);
And that will fix the errors.

**Comment by teryhill** [comment]
Then look thru the code for any more instances of call_required_libraries(true,true,false,false); and change them to call_required_libraries($bootstrap=true,$fancybox=true,$knockout=false,$datepicker=false);

**Comment by aethelwulffe** [comment]
@Trodrige 
Do what Terry says, but after pulling down the latest version of master from here.
We (I) reverted your last changes, so this is basically starting over.
This is a good short project with some very typical repo/git issues, so this makes it a very good way to get experience with our integration method.  All of us have had some problem getting our first pull requests merged for one reason or another.

**Comment by Trodrige** [comment]
@aethelwulffe and @teryhill fixed. Hope I didn't miss any file this time.

**Comment by aethelwulffe** [comment]
All good so far.
There is, of course, a lot more organizing of assets and bootstrapping of the includes to be done in the project.  This piece is a nice start.

**Comment by Trodrige** [comment]
OK, great
