### ISSUE TITLE
setup.php cloning database leads to errors due to missing table 

### ISSUE THREAD

**Issue by robbyoconnor** [LibreHealthIO/LibreEHR#669]
If you set up a site via `setup.php`, then choose to simply clone a site and its database, you wind up hitting an error with missing tables. 

To reproduce: 

- Create a new site, use `default` as the template,
- then create a new database user and a new database, but copy the database from the `default` site. 
- Run setup, wait, and then try to login. 
- Check error logs and you'll see a slew of errors. 

Log can be shared privately.

**Comment by aethelwulffe** [comment]
I assume that you have a manual work-around at the moment, Ja?

Show us them logs...somewhere.  puhleez.

**Comment by tmccormi** [comment]
The setup clone model is bad anyway, in my opinion.  It ALSO does not copy the customized sites/ content form the selected install to the new one.

**Comment by teryhill** [comment]
I don't think it is missing tables

[Wed Aug 23 06:25:02.041440 2017] [ssl:warn] [pid 1488] AH01873: Init: Session Cache is not configured [hint: SSLSessionCache]
[Wed Aug 23 06:25:02.042841 2017] [mpm_prefork:notice] [pid 1488] AH00163: Apache/2.4.18 (Ubuntu) PHP/7.0.22-0ubuntu0.16.04.1 OpenSSL/1.0.2g configured -- resuming normal operations
[Wed Aug 23 06:25:02.042852 2017] [core:notice] [pid 1488] AH00094: Command line: '/usr/sbin/apache2'
[Wed Aug 23 17:49:18.846651 2017] [:error] [pid 21398] [client 68.109.110.241:52775] PHP Notice:  Undefined index: sql_admin_tool_url in /opt/nhanes/interface/main/tabs/menu/menu_data.php on line 10, referer: https://nhanes.librehealth.io/interface/login/login.php?site=default
[Wed Aug 23 17:49:18.847779 2017] [:error] [pid 21398] [client 68.109.110.241:52775] PHP Notice:  Undefined index: Administration in /opt/nhanes/interface/tags_filters/start.php on line 74, referer: https://nhanes.librehealth.io/interface/login/login.php?site=default
[Wed Aug 23 19:03:41.736937 2017] [:error] [pid 19937] [client 68.109.110.241:53041] PHP Notice:  Undefined index: mode in /opt/nhanes/interface/usergroup/facilities.php on line 70, referer: https://nhanes.librehealth.io/interface/main/tabs/main.php?url=TAB_ONE_DEFAULT
[Wed Aug 23 19:03:41.741381 2017] [:error] [pid 19937] [client 68.109.110.241:53041] PHP Notice:  Use of undefined constant street - assumed 'street' in /opt/nhanes/interface/usergroup/facilities.php on line 168, referer: https://nhanes.librehealth.io/interface/main/tabs/main.php?url=TAB_ONE_DEFAULT
[Wed Aug 23 19:03:41.741400 2017] [:error] [pid 19937] [client 68.109.110.241:53041] PHP Notice:  Use of undefined constant street - assumed 'street' in /opt/nhanes/interface/usergroup/facilities.php on line 169, referer: https://nhanes.librehealth.io/interface/main/tabs/main.php?url=TAB_ONE_DEFAULT
[Wed Aug 23 19:03:41.741407 2017] [:error] [pid 19937] [client 68.109.110.241:53041] PHP Notice:  Use of undefined constant city - assumed 'city' in /opt/nhanes/interface/usergroup/facilities.php on line 170, referer: https://nhanes.librehealth.io/interface/main/tabs/main.php?url=TAB_ONE_DEFAULT
[Wed Aug 23 19:03:41.741413 2017] [:error] [pid 19937] [client 68.109.110.241:53041] PHP Notice:  Use of undefined constant state - assumed 'state' in /opt/nhanes/interface/usergroup/facilities.php on line 171, referer: https://nhanes.librehealth.io/interface/main/tabs/main.php?url=TAB_ONE_DEFAULT
[Wed Aug 23 19:03:41.741420 2017] [:error] [pid 19937] [client 68.109.110.241:53041] PHP Notice:  Use of undefined constant id - assumed 'id' in /opt/nhanes/interface/usergroup/facilities.php on line 174, referer: https://nhanes.librehealth.io/interface/main/tabs/main.php?url=TAB_ONE_DEFAULT
[Wed Aug 23 19:03:41.741427 2017] [:error] [pid 19937] [client 68.109.110.241:53041] PHP Notice:  Use of undefined constant name - assumed 'name' in /opt/nhanes/interface/usergroup/facilities.php on line 174, referer: https://nhanes.librehealth.io/interface/main/tabs/main.php?url=TAB_ONE_DEFAULT
[Wed Aug 23 19:03:41.741435 2017] [:error] [pid 19937] [client 68.109.110.241:53041] PHP Notice:  Use of undefined constant country_code - assumed 'country_code' in /opt/nhanes/interface/usergroup/facilities.php on line 175, referer: https://nhanes.librehealth.io/interface/main/tabs/main.php?url=TAB_ONE_DEFAULT
[Wed Aug 23 19:03:41.741441 2017] [:error] [pid 19937] [client 68.109.110.241:53041] PHP Notice:  Use of undefined constant postal_code - assumed 'postal_code' in /opt/nhanes/interface/usergroup/facilities.php on line 175, referer: https://nhanes.librehealth.io/interface/main/tabs/main.php?url=TAB_ONE_DEFAULT
[Wed Aug 23 19:03:41.741448 2017] [:error] [pid 19937] [client 68.109.110.241:53041] PHP Notice:  Use of undefined constant phone - assumed 'phone' in /opt/nhanes/interface/usergroup/facilities.php on line 176, referer: https://nhanes.librehealth.io/interface/main/tabs/main.php?url=TAB_ONE_DEFAULT
[Wed Aug 23 19:03:41.741455 2017] [:error] [pid 19937] [client 68.109.110.241:53041] PHP Notice:  Use of undefined constant street - assumed 'street' in /opt/nhanes/interface/usergroup/facilities.php on line 168, referer: https://nhanes.librehealth.io/interface/main/tabs/main.php?url=TAB_ONE_DEFAULT
[Wed Aug 23 19:03:41.741473 2017] [:error] [pid 19937] [client 68.109.110.241:53041] PHP Notice:  Use of undefined constant street - assumed 'street' in /opt/nhanes/interface/usergroup/facilities.php on line 169, referer: https://nhanes.librehealth.io/interface/main/tabs/main.php?url=TAB_ONE_DEFAULT
[Wed Aug 23 19:03:41.741479 2017] [:error] [pid 19937] [client 68.109.110.241:53041] PHP Notice:  Use of undefined constant street - assumed 'street' in /opt/nhanes/interface/usergroup/facilities.php on line 169, referer: https://nhanes.librehealth.io/interface/main/tabs/main.php?url=TAB_ONE_DEFAULT
[Wed Aug 23 19:03:41.741485 2017] [:error] [pid 19937] [client 68.109.110.241:53041] PHP Notice:  Use of undefined constant city - assumed 'city' in /opt/nhanes/interface/usergroup/facilities.php on line 170, referer: https://nhanes.librehealth.io/interface/main/tabs/main.php?url=TAB_ONE_DEFAULT
[Wed Aug 23 19:03:41.741491 2017] [:error] [pid 19937] [client 68.109.110.241:53041] PHP Notice:  Use of undefined constant city - assumed 'city' in /opt/nhanes/interface/usergroup/facilities.php on line 170, referer: https://nhanes.librehealth.io/interface/main/tabs/main.php?url=TAB_ONE_DEFAULT
[Wed Aug 23 19:03:41.741496 2017] [:error] [pid 19937] [client 68.109.110.241:53041] PHP Notice:  Use of undefined constant state - assumed 'state' in /opt/nhanes/interface/usergroup/facilities.php on line 171, referer: https://nhanes.librehealth.io/interface/main/tabs/main.php?url=TAB_ONE_DEFAULT
[

**Comment by robbyoconnor** [comment]
I shared the log privately for a reason.

**Comment by teryhill** [comment]
Why?

**Comment by robbyoconnor** [comment]
Well for one it contains my IP

**Comment by robbyoconnor** [comment]
@teryhill Security. 

- My IP is there 
- DB usernames which shouldn't be public are also there.

**Comment by robbyoconnor** [comment]
Okay, it seems to have fixed itself...somehow...not sure how...

**Comment by teryhill** [comment]
It was not broke. The error was not a missing table.

**Comment by robbyoconnor** [comment]
Ah ok :) sorry about that.
