### ISSUE TITLE
setup errors for pnTemplates

### ISSUE THREAD

**Issue by aethelwulffe** [LibreHealthIO/LibreEHR#672]
https://github.com/LibreHealthIO/LibreEHR/blob/6ddcc6b995cb4284431fdb6500c2b1c68948703f/setup.php#L73

setup.php must be updated to reflect removal of old PNcalendar.

**Comment by aethelwulffe** [comment]
Line 73 and 74 at least.

**Comment by tmccormi** [comment]
Are there any directories that need to be writable for this new version, considering that smarty is gone?

**Comment by tmccormi** [comment]
Srry, I missed the fact that there was already a pull request.  All merged now.
