### ISSUE TITLE
sql_upgrade.php error

### ISSUE THREAD

**Issue by aethelwulffe** [LibreHealthIO/LibreEHR#676]
Error: Duplicate entry 'Administrators-Globals|/interface/super/edit_globals.php-Adminis' for key 'PRIMARY'

C:\xampp\htdocs\libremaster\library\sql_upgrade_fx.php at 504:sqlStatement
C:\xampp\htdocs\libremaster\sql_upgrade.php at 58:upgradeFromSqlFile(1_0_1-to-1_0_2_upgrade.sql)

**Comment by teryhill** [comment]
@aethelwulffe is this an Issue still?
