### ISSUE TITLE
Patient name/title is "Current Patient" in EDIT mode

### ISSUE THREAD

**Issue by aethelwulffe** [LibreHealthIO/LibreEHR#680]
Header name of patient switches to "Current Patient" when editing a patient of a known name.

**Comment by teryhill** [comment]
@aethelwulffe  is this what you want? 

![image](https://user-images.githubusercontent.com/4655366/30975411-37650fae-a440-11e7-9b2e-5f4614299aa8.png)

**Comment by aethelwulffe** [comment]
Yes

**Comment by aethelwulffe** [comment]
Yes.
