### ISSUE TITLE
Layout Edit button malformed

### ISSUE THREAD

**Issue by aethelwulffe** [LibreHealthIO/LibreEHR#681]
![image](https://user-images.githubusercontent.com/553751/30791392-0f31811a-a180-11e7-9d9e-64d68f1a4255.png)

Effect is the same in all layouts that I checked.  First button top left is half-visible.

**Comment by Trodrige** [comment]
@aethelwulffe can you assign this to me. Will love to fix this.

**Comment by teryhill** [comment]
Go for it @Trodrige

**Comment by aethelwulffe** [comment]
@Trodrige Accept the invite to be added as a collaborator, and I can assign this to you officially.

**Comment by Trodrige** [comment]
@aethelwulffe I accepted the invite.

**Comment by aethelwulffe** [comment]
You have been assigned.

**Comment by Trodrige** [comment]
@aethelwulffe fixed

**Comment by aethelwulffe** [comment]
Gotta fix the sqlconf.php deleted file before testing.

**Comment by aethelwulffe** [comment]
OK, this is straight.  I still need to check it out with the alternate theme...but seems right so far.
