### ISSUE TITLE
Demographics edit URL issue

### ISSUE THREAD

**Issue by aethelwulffe** [LibreHealthIO/LibreEHR#682]
Open a patient.  Without choosing another tab (leave on "facesheet"), hit edit, then click on another tab.  This gives you a broken link.  If you first select another tab, THEN you hit edit, it works fine for all the tabs.

**Comment by teryhill** [comment]
I am not able to reproduce this can I have a few more details?

**Comment by aethelwulffe** [comment]
I will attempt to re-reproduce this.  I could have taken a screenshot, but I recall there was an older database involved in this.  I will do it again on the same set-up.  While I am at it, I will do it on one of the prod setups.  Hopefully, this is just an artifact and not an issue.

**Comment by Trodrige** [comment]
I don't get any broken while these steps.

**Comment by aethelwulffe** [comment]
Closing this.  Not replicable apparently
