### ISSUE TITLE
Tabs not always resizable

### ISSUE THREAD

**Issue by aethelwulffe** [LibreHealthIO/LibreEHR#684]
When opening multiple tabs, sometimes they become non-resizable.  This issue has been discussed before, but there has not been a specific bug report put in.

**Comment by apooravc** [comment]
@aethelwulffe A possible duplicate of #956 ?

**Comment by aethelwulffe** [comment]
#956 is a duplicate of this.  Being that this is really really old, I will drop this in favor of the new one.
