### ISSUE TITLE
Layout Editor style format error

### ISSUE THREAD

**Issue by aethelwulffe** [LibreHealthIO/LibreEHR#685]
![image](https://user-images.githubusercontent.com/553751/30877088-954cc54c-a2c6-11e7-8c16-190f1b13ba6e.png)

"With Selected:" needs to be _before_ the buttons, or the button labels need to be edited to that effect.

**Comment by Trodrige** [comment]
Hi @aethelwulffe, is this what you mean...
![layout-editor-style-error](https://user-images.githubusercontent.com/16147419/31746056-602e4ffe-b45d-11e7-99c1-78c6078e6473.png)

**Comment by teryhill** [comment]
@aethelwulffe  what about making it say When Selected

**Comment by Trodrige** [comment]
Uhhhh, @teryhill 'When selected' doesn't sound well to me. It sounds more like an INSTRUCTION is to follow, while with 'With selected' it's obvious that an ACTION follows.

**Comment by teryhill** [comment]
Ok but it sounds incomplete. I select the items now what do I do? I really want to Delete or move what I have selected. Just a thought.

**Comment by aethelwulffe** [comment]
With Selected is right...though I bet trodrige could add a little bit of padding in there, or something that looks a little cleaner or something.  
I think "With Checked ✅ " then two options with buttons proportional to the label, or otherwise separated from the "save changes".
Honestly, I think the thing needs re-writing or getting a per-line "save" button.

**Comment by aethelwulffe** [comment]
# With Selected ### <Move> <Delete>

**Comment by Trodrige** [comment]
@aethelwulffe what about this?

![layout-editor-style-error-1](https://user-images.githubusercontent.com/16147419/31747917-b00444de-b467-11e7-9b6a-e6c9c22cee0f.png)

**Comment by Trodrige** [comment]
> Honestly, I think the thing needs re-writing or getting a per-line "save" button.

What if a user edits more than one entry but ends up clicking the 'save' button of only one of the entries (lines). Will the change be discarded?. However, it'll be a good idea if the per-line "save" buttons' save logic is implemented same as the current one (invoked by Clicking Save Changes). That is they all invoke the same function that updates all changed fields(lines or entries).
Also, if we are to re-write, I think we should add per-line "delete" buttons. Just thinking...

**Comment by teryhill** [comment]
It the user edits more than one line then saves they all are saved. The delete and move are the only items that apply to the check boxes.

**Comment by Trodrige** [comment]
> It the user edits more than one line then saves they all are saved.
@teryhill, aethelwulffe says each line should have a save button in it. Are you saying each of these buttons will function same as the current 'Save Changes' button. I mean, the logic that updates the entries when the save button is clicked.

**Comment by Trodrige** [comment]
What if we change the values in the delete and move to buttons to these

![layout editor option](https://user-images.githubusercontent.com/16147419/31749248-b30e508a-b470-11e7-9900-2f1005a82953.png)

**Comment by teryhill** [comment]
I LIKE that one.

The save per section is ok as long as when any save button is activated it saves all

**Comment by teryhill** [comment]
@Trodrige how about if the buttons floated with the screen scroll so that the save button is always in the active area then one button would do.

**Comment by aethelwulffe** [comment]
@Trodrige THAT is what I like.  Pleasepleaseplease let's keep the second one!  Clean, with the whole function label in each button.  We might also want to change "Save Changes" to "Save Edits" or Save Edited Lines or something, but this is MUCH BETTER this way.

**Comment by aethelwulffe** [comment]
The same thing is needed in the FORMS ADMIN.

**Comment by Trodrige** [comment]
@aethelwulffe please can you give me directions on the forms admin issue. Or better still open a new issue for it.

**Comment by aethelwulffe** [comment]
@Trodrige I am closing this, then opening on the forms admin issue.  It is the same sort of thing where administration/forms GUI has badly arranged controls.

**Comment by Trodrige** [comment]
OK, I'll fix that too
