### ISSUE TITLE
Setup Fails on Facility table

### ISSUE THREAD

**Issue by tmccormi** [LibreHealthIO/LibreEHR#708]
During testing:  @yehster's fix reports this error:

During SQL Database creation:
unable to execute SQL: 'INSERT INTO `facility` VALUES (3, 'Your Clinic Name Here', '000-000-0000', '000-000-0000', '', '', '', '', '', '', NULL, NULL, 1, 1, 0, NULL, '', '', '', '', '','#99FFFF','0', '')' due to: Column count doesn't match value count at row 1

It does not prevent you from continuing and it should....

**Comment by tmccormi** [comment]
OF course the insert needs to be fixed as well

**Comment by tmccormi** [comment]
Works now, no errors from database SQL setup

**Comment by yehster** [comment]
Would consider a "clean abort" a significant figure request. How to handle failed SQL during install is tricky.  It could make testing and correcting more difficult.  Just reporting them seems to have helped significantly.

**Comment by tmccormi** [comment]
Yes, it's excellent improvement. and I agree, not sure about the best way to abort and clean up.

**Comment by aethelwulffe** [comment]
Art be a-publishin' a "file-per-table" replacement for database.sql (and everything else).  Starting a new issue for that, closing this one.
