### ISSUE TITLE
Change "Appointments" in the demographic screen to "Future Appointments".

### ISSUE THREAD

**Issue by tmccormi** [LibreHealthIO/LibreEHR#722]
Change the title of the appointment widget in demographics screen to read "Future Appointments"

![issue-gci2](https://user-images.githubusercontent.com/285835/31579622-ace134f0-b0ee-11e7-8192-95df58971ef7.png)

interface/patient_file/summary/demographics.php
1490:        $widgetTitle = xl("Appointments");

**Comment by teryhill** [comment]
@jdew192837 has submitted a pr for this

**Comment by teryhill** [comment]
PR Merged closing issue
