### ISSUE TITLE
Issue during installation 

### ISSUE THREAD

**Issue by SoumyadeepJana** [LibreHealthIO/LibreEHR#736]
I have configured the php.ini and mysql.ini files as mentioned but during installation, I am facing something like this.

<img width="960" alt="2017-10-24" src="https://user-images.githubusercontent.com/16064577/31931679-96a90584-b8c1-11e7-98f8-1779b10a5f3e.png">

Mysql error log is as follows:
<img width="960" alt="2017-10-24 2" src="https://user-images.githubusercontent.com/16064577/31931883-34c53f3a-b8c2-11e7-8dd7-7ab9f134276f.png">

**Comment by aethelwulffe** [comment]
max_execution_time should be set to a minimum of 90 seconds.  30 seconds 
doesn't work so good.

**Comment by SoumyadeepJana** [comment]
I have set the max_execution_time to 600,still it doesnt work.

**Comment by tmccormi** [comment]
Line 460 is a call to mysql, perhaps you have something wrong with the mysql installation/setup?

**Comment by aethelwulffe** [comment]
@SoumyadeepJana Have you resolved this as an issue?  I believe it was a php version issue, Ja?
If so, this is resolved by either fixing 7.1 compatibility, or by documenting the issue in the install/setup docs or the installer itself.

**Comment by SoumyadeepJana** [comment]
@aethelwulffe yup,I guess the issue was due to the php version because I tried it on different machines with php 7.1.10 but the I faced the same issue,both in Wamp and Xampp server.php 7.0.24 was rightly compatible.Should I update the setup docs?

**Comment by aethelwulffe** [comment]
PLEEEEZEEE!

-Good bug catch BTW!  It is a nice fat crunchy bug too.  I sure it will 
be a lot of fun ramping up a compatibility project:  Of course we want 
to see where 7.2 is going to put us before we start.  Rumor has it that 
there are issues (that we solved) that are not an issue with 7.1 or 5.7 
that were issues with 7.0. *sigh*.

Document and forge ahead!

**Comment by teryhill** [comment]
@SoumyadeepJana is this still an active issue

**Comment by aethelwulffe** [comment]
This was adodb and 7.1   We are attending to this.
