### ISSUE TITLE
Inconsistent display of frames

### ISSUE THREAD

**Issue by Trodrige** [LibreHealthIO/LibreEHR#738]
- From the main page( with 2 tabs open ) go to Administration->Other->Database. Observe that the new frame is "Unkown".
- Still from the main page(with default 2 tabs open). Close one of the tabs and head to Administration->Other->Database. Observe that the new tab has both initial tabs inside it. Sometimes it I still have the empty "Unknown" tab.

**Comment by teryhill** [comment]
Make sure you have the disable sql admin checked in globals. You are getting this because you do not have phpmyadmin installed thru the software.

**Comment by teryhill** [comment]
it is on the features tab

![image](https://user-images.githubusercontent.com/4655366/31970319-9d742aaa-b8e5-11e7-94d1-80c1e3eb417e.png)

**Comment by Trodrige** [comment]
@teryhill I checked that and this alert box keeps showing every time.

![alert](https://user-images.githubusercontent.com/16147419/31991151-f5b622e8-b96e-11e7-838b-ce21a712eeaf.png)

**Comment by Trodrige** [comment]
Right!!! I got it. I didn't have libreehr.librehr_postcalendar_events table. Saw this error

> [Wed Oct 25 10:20:35 2017] 127.0.0.1:41296 [200]: /modules/calendar/includes/get_provider_events.php
> [Wed Oct 25 10:20:40 2017] SQL Error with statement:query failed: SELECT e.pc_eventDate, e.pc_endDate, e.pc_startTime, e.pc_endTime, e.pc_duration, e.pc_recurrtype, e.pc_recurrspec, e.pc_recurrfreq, e.pc_catid, e.pc_eid, e.pc_title, e.pc_hometext, e.pc_apptstatus, e.pc_location, e.pc_aid, e.pc_eid, e.pc_alldayevent, e.pc_pid, p.fname, p.mname, p.lname, p.pid, p.phone_home, p.phone_cell, u.fname AS ufname, u.mname AS umname, u.lname AS ulname, u.id AS uprovider_id, c.pc_catname, c.pc_catid, c.pc_catcolor FROM libreehr_postcalendar_events AS e LEFT OUTER JOIN patient_data AS p ON p.pid = e.pc_pid LEFT OUTER JOIN users AS u ON u.id = e.pc_aid LEFT OUTER JOIN libreehr_postcalendar_categories AS c ON c.pc_catid = e.pc_catid WHERE ((e.pc_endDate >= '2017-10-25' AND e.pc_eventDate <= '2017-10-26' AND e.pc_recurrtype > '0') OR (e.pc_eventDate >= '2017-10-25' AND e.pc_eventDate <= '2017-10-26')) ORDER BY e.pc_eventDate, e.pc_startTime--Table 'libreehr.libreehr_postcalendar_events' doesn't exist==>/home/trodrige/Documents/LibreEHR/library/appointments.inc.php at 101:sqlStatement

I created the table, and works well now. Thanks @teryhill

**Comment by teryhill** [comment]
@Trodrige is this issue resolved?

**Comment by Trodrige** [comment]
Yup it is!!
