### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by SoumyadeepJana** [LibreHealthIO/LibreEHR#742]
I am getting this error in step 4,next time when i am visiting the index page,i am getting the login screen but my created credentials don't seem to work.Please help.

<img width="960" alt="2017-10-25" src="https://user-images.githubusercontent.com/16064577/31990335-730144b2-b992-11e7-8f3f-0d7f67a01902.png">

Mysql.ini file
https://drive.google.com/open?id=0B89Dh49ZodyQZFE1N1RleGtuRVE

php.ini file
https://drive.google.com/open?id=0B89Dh49ZodyQZ1dlMTVRc1JvVzA

**Comment by Trodrige** [comment]
> next time when I am visiting the index page, I am getting the login screen but my created credentials don't seem to work.

Hi, @SoumyadeepJana check libreehr.users table if your credentials exist.

**Comment by SoumyadeepJana** [comment]
There's no such table created.

**Comment by teryhill** [comment]
@SoumyadeepJana do you have any entries in the php error log? Sounds like some of the tables did not get created on the install. What version of PHP are you using?

**Comment by SoumyadeepJana** [comment]
@teryhill Hi
I am using php version 7.1.10

**Comment by teryhill** [comment]
I have not tested with 7.1 . 7.0 is the latest that was tested.

**Comment by Trodrige** [comment]
> There's no such table created.

I asked because I face this same problem, and had to create the missing tables myself. 
Go to your project folder-> sql ->database.sql  Here you'll find the SQL statements to create tables. Make use of it. Ensure you have all the tables in the database to avoid future blocks. Hope it helps

**Comment by SoumyadeepJana** [comment]
Should I use php 5 instead? Yeah I got the database.sql file but where should i run those commands?

**Comment by Trodrige** [comment]
@SoumyadeepJana I got php 7.0. 
I use phpmyadmin to access my databases, so I created the missing tables there.

**Comment by SoumyadeepJana** [comment]
It worked with a slight lower version of php.
Thanks @teryhill @Trodrige

**Comment by teryhill** [comment]
@SoumyadeepJana  what version? @tmccormi and @aethelwulffe php 7.1.10 will not install

**Comment by SoumyadeepJana** [comment]
My php version is 7.0.24

**Comment by aethelwulffe** [comment]
I already figured out the 7.1 issue when building the xampp installer.

**Comment by aethelwulffe** [comment]
Superglobals like $this have changes in use, datetime comparisons, 
session ID hashing, lexically bound variables like $_SERVER that have 
been used for other purposes, and a number of other things are going to 
be a problem I think.

**Comment by tmccormi** [comment]
PHP 7.1 port - Sounds like a good issue to open and for a smart volunteer to work on ...

**Comment by teryhill** [comment]
Is this still an active issue?
