### ISSUE TITLE
User UI pop-up window for Inactive Users.

### ISSUE THREAD

**Issue by aethelwulffe** [LibreHealthIO/LibreEHR#744]
Modal window/fancybox whatever in Administration/Users does not show when "inactive" users are in the list.

Replication:  
Create a bunch of users, some active, some not. 
In the UI, check "show inactive".
Click on a row.  Page loading attempts to happen, but nothing shows.
Uncheck "show inactive".
Click on a row.  Behavior is now nominal.

**Comment by tmccormi** [comment]
I am not able to replicate this issue in my installation.  It's all working normally

**Comment by aethelwulffe** [comment]
@teryhill check to make sure you are not getting the same thing I am, and if so, I will chock it up to bad data.

**Comment by aethelwulffe** [comment]
I got this error on an UBUNTU server...checking it out now on XAMPP with the same data.

**Comment by teryhill** [comment]
@aethelwulffe I am not having any issues with this on my system.

**Comment by aethelwulffe** [comment]
Closing this.  I will re-investigate what is going on with that system.  If there is a real issue, I will re-open.
