### ISSUE TITLE
Insurance group not available for editing

### ISSUE THREAD

**Issue by Trodrige** [LibreHealthIO/LibreEHR#752]
Insurance group is not available for editing in the Demographics layout. It should be made available, instead of the user adding it.

**Comment by aethelwulffe** [comment]
So you are talking about allowing the users to modify the insurance section of the demographics, right?
Unfortunately, every value in these sections are pretty much tied into the ANSI X12 837p standard.  That means they are basically sacrosanct.   Mind you, styling what order the stuff appears in etc..., or allowing a region-specific add-on module (which should be included in a billing module creation/refactor) would be by far the best thing, but allowing causal GUI modification of this section would lead to the tinkerer immediately bricking their billing system.

**Comment by teryhill** [comment]
@Trodrige could you explain what you are seeing to me a little more. Some screen shots would help.

**Comment by Trodrige** [comment]
@teryhill I hope this screenshot helps. The user can edit other sections for adding a new patient except for the insurance section. I just pointed out that it's absent. 

![edit-demographics](https://user-images.githubusercontent.com/16147419/32397495-59f82dc8-c0ea-11e7-9305-469abc9a58f9.png)

**Comment by Trodrige** [comment]
> allowing a region-specific add-on module (which should be included in a billing module creation/refactor) would be by far the best thing, but allowing causal GUI modification of this section would lead to the tinkerer immediately bricking their billing system

@aethelwulffe if I get this right, we want to add a module that enables the user to edit (or not edit) depending on their region. Is this what you mean?

**Comment by teryhill** [comment]
@Trodrige If the user were to remove an insurance field from the grouping then they would not get payment from the insurance company. That section of the screen is static ( not changeable by the user) for that reason. The Layout options are a great way for the user to create fields and delete them. In the current configuration if the end user removes a field from the layout screen that data is removed from the table (really bad thing to do).

And yes there needs to be a billing module depending on the region. Some places do not file insurance and it is cash only. Hence all the insurance information is not needed.

**Comment by Trodrige** [comment]
Ok, understood. 
Considering that we are to stand such a billing module,
1. How do we know if a region files insurance? If they do,
2. How do we determine the health insurance policies in a particular region? (to know necessary fields to display).

**Comment by teryhill** [comment]
@trodrige we use globals to say cash only or Insurance. If cash only is selected then turn off the insurance information. We cannot determine if the customer is cash only but the user will know. There are some other things that need to happen in a cash only environment, like printing a receipt , printing a statement etc so the main thing is just not generating insurance claims electronically.
This would be a start then we could expand from there based on customer feed back.

**Comment by Trodrige** [comment]
Thanks, @teryhill.
Unless @aethelwulffe has something to contribute, I'll close this issue.

**Comment by aethelwulffe** [comment]
Go ahead and close it, but this was a _very useful discussion_.  In closing this will be an important point for offering a billing module configuration.  As someone creates a billing module config for their region, we would be able to integrate it as such.
The alternative is to make the whole billing and accounting system regional.  I personally would prefer it to be a configuration based thing.  For instance, the current electronic billing system uses the X12 standards, but we need to implement UN/EDIFACT billing for most other countries.
Here is a page with links to both sets of standards.  Naturally the scummy X12.org site it links to wants money to get the federally mandated standard, where the UN/EDIFACT documentation is free.
http://www.jobisez.com/edi/documents/
