### ISSUE TITLE
Add new message icon to the main screen.

### ISSUE THREAD

**Issue by teryhill** [LibreHealthIO/LibreEHR#779]
Add a notification icon to the main screen. This icon will indicate if the signed in user has a new message in the messaging system. When there is an new message for a user display a notification icon in the upper right side of the main screen.

Changes to /libreehr/interface/main/tabs/main.php to display the notification icon.

![notify](https://user-images.githubusercontent.com/4655366/33466975-7badcdb6-d61f-11e7-909e-a8ac34c0c4cc.PNG)

**Comment by teryhill** [comment]
@robbyoconnor if you can figure out how to get this in as one of Your task it might give you some help while you are making more coding tasks for LibreEHR

**Comment by teryhill** [comment]
Currently assigned to @migdinny

**Comment by teryhill** [comment]
Assigned too @migdinny

**Comment by robbyoconnor** [comment]
@teryhill There's a generic fix an issue -- the issue can be difficult -- so it's okay to use that one.

**Comment by aethelwulffe** [comment]
http://librehealthehr.suncoastconnection.com/refresh
A little demonstrator...

**Comment by teryhill** [comment]
This is done and the PR's are merged.
