### ISSUE TITLE
add registration form to register users for LibreEHR

### ISSUE THREAD

**Issue by teryhill** [LibreHealthIO/LibreEHR#78]
add ability to register users for LibreEHR. This will allow security updates notices to be sent. Will also allow a marketing hook. Add the ability for registration to the about page and globals.

**Comment by tmccormi** [comment]
Do we make it optional or mandatory.  What about installs that are "off network"?

**Comment by teryhill** [comment]
Optional is my vote, Don't know how you would make it mandatory. Just need to add value to it to make them want to register

**Comment by pri2si17-1997** [comment]
Hello @teryhill  
Can you please explain more on it?

**Comment by teryhill** [comment]
Stale too long
