### ISSUE TITLE
Flow Board is a little messed up

### ISSUE THREAD

**Issue by teryhill** [LibreHealthIO/LibreEHR#783]
In the screen shot the open in new window has thing out of kilter. I added that back in a hurry sorry.

![image](https://user-images.githubusercontent.com/4655366/33507241-ac0d7d6a-d6c1-11e7-8080-85d675a22f21.png)

**Comment by teryhill** [comment]
Task assigned to @migdinny

**Comment by teryhill** [comment]
@migdinny I would like for you to drop the "open Patient in New Window" and place it under the settings.

![image](https://user-images.githubusercontent.com/4655366/33511375-a9699d98-d6e7-11e7-9171-46c8fab63690.png)

**Comment by MigDinny** [comment]
![image](https://user-images.githubusercontent.com/6632800/33516305-8fb5488a-d768-11e7-9f04-2899ed5371ea.png)

between these options?

**Comment by teryhill** [comment]
@migdinny Is it there under settings for you?

**Comment by teryhill** [comment]
once settings is opened it needs to stay open until the user saves it, then the auto refresh needs to continue.
