### ISSUE TITLE
Flow board 'From' and 'To' input alignment

### ISSUE THREAD

**Issue by Trodrige** [LibreHealthIO/LibreEHR#794]
This is a simple css/stylesheet issue. The date fields of the form( Appointments filter) are lower than the category field. Style these fields to be in line with the others.

![flow board from and to input fields](https://user-images.githubusercontent.com/16147419/33525879-e2ce85ca-d837-11e7-8f79-6030c70d524d.png)

**Comment by MigDinny** [comment]
@Trodrige I can't see that "Date" input, only "from" and "to".
I believe my pull request will fix that too, but just to check it, can you tell me how you got into there?

**Comment by Trodrige** [comment]
You're right about that. I checked the demo, it has the same issue too. 'From' and 'To' fields are not inline with the category field. Still needs fixing.

**Comment by MigDinny** [comment]
@Trodrige I fixed "From" and "To" fields. Where is the "Date" field? I can't find it. But if it has "type='text'" property in its HTML it'll be fixed for sure because my fix covers it too.

**Comment by Trodrige** [comment]
Your fix works fine. It should cover the 'Date' field too.
