### ISSUE TITLE
“Create client certificate” button is out of place

### ISSUE THREAD

**Issue by Trodrige** [LibreHealthIO/LibreEHR#800]
Go to  Admin->Other->Certificate. Scroll down and keep the 'Create client certificate' button in the box.

**Comment by Jdew192837** [comment]
I can do this in be I get home from church

**Comment by Jdew192837** [comment]
Will fix this next @teryhill @Trodrige :)

**Comment by teryhill** [comment]
Assigned to @Jdew192837

**Comment by SoumyadeepJana** [comment]
I have already fixed this for the bootstrap UI enhancement ,didnt give a PR
as the previous  PR was not merged.

**Comment by teryhill** [comment]
You are not GCI are you @soumyadeepjana

**Comment by SoumyadeepJana** [comment]
No I am not for GCI @teryhill,It was an issue listed in the Bootstrap UI enhancement tasks listed by @Trodrige
