### ISSUE TITLE
Make content in SSL Certificate tab responsive

### ISSUE THREAD

**Issue by Trodrige** [LibreHealthIO/LibreEHR#806]
Go to Admin->Other->Certificate. Open three different tabs. Notice that the content is not responsive.

**Comment by teryhill** [comment]
Task assigned to @jdew192837

**Comment by teryhill** [comment]
@SoumyadeepJana did you do this as part of the bootstrap re-write?

**Comment by Jdew192837** [comment]
I think I have a solution. Still testing and playing around though @Trodrige @teryhill

**Comment by SoumyadeepJana** [comment]
@teryhill Yes I did that as a part of rewrite

**Comment by Trodrige** [comment]
@SoumyadeepJana I think we should leave this for the hungry GCI guys. What do you think?
@Jdew192837 has already started work on this. Sorry, for stealing this from you!

**Comment by SoumyadeepJana** [comment]
@Trodrige  Yes I think they should work on this.

**Comment by aethelwulffe** [comment]
Cool.
@SoumyadeepJana I should have figured you were posting all these bytebugs for the GCI gang.  *duh*.  Very nicely done.
@Jdew192837 @MigDinny and all the rest....Tear these tasks up folks!
WooHoo!

**Comment by SoumyadeepJana** [comment]
@aethelwulffe The GCI gang is really doing a great job..

**Comment by aethelwulffe** [comment]
@SoumyadeepJana yeah...and we just about need one mentor per person at the rate they are going.
@Trodrige Hé mec, ces petits enfants nous font paraître paresseux!

**Comment by SoumyadeepJana** [comment]
@aethelwulffe  Their pace is uncatchable 👍 ,I must say
Should I open new issues for them or should I drop in PRs myself?

**Comment by aethelwulffe** [comment]
Just open issues like you have been doing, with the good hints for solution tactics.  If they pick them up, great.  If not, they are well documented issues.

**Comment by Jdew192837** [comment]
This is awesome. Thanks @SoumyadeepJana ! Were you a GSOC student? @teryhill mentioned that a GSOC student did a lot of bootstrap rewriting. :)

**Comment by SoumyadeepJana** [comment]
No,I wasn't a GSOC student @Jdew192837 but I am involved in bootstrap rewriting

**Comment by Jdew192837** [comment]
Oh nice! So you're a mentor then? I'd love to learn more about bootstrap, so if you have more bugs or bootstrap proposals, I'd love to do them! :)
@SounyadeepJana

**Comment by Jdew192837** [comment]
@SoumyadeepJana

**Comment by SoumyadeepJana** [comment]
@Jdew192837 Not a mentor but a collaborator to this repo,I'd love to help you wherever you need.
