### ISSUE TITLE
Missing tab name (title)

### ISSUE THREAD

**Issue by Trodrige** [LibreHealthIO/LibreEHR#807]
QA Measures->XML Editor. Add tab title(XML Editor)

**Comment by Jdew192837** [comment]
I'll fix this next. :)

**Comment by Trodrige** [comment]
Assigned to @Jdew192837

**Comment by Jdew192837** [comment]
Did you see my issues and messages on the chat @Trodrige ?

There already is a title in the index.html file, but I'm not sure why it's not displaying.

**Comment by Jdew192837** [comment]
@Trodrige Have you looked into these issues to see if they have a possible solution?

**Comment by aethelwulffe** [comment]
This fix is already in a pull request.

**Comment by aethelwulffe** [comment]
Oops...I lied.
I had decided that since it had a huge title bar already, having the tab named just added junk.  The main point was to intentionally make it non-printable, so that it would not show, but also not print "Unknown".

**Comment by aethelwulffe** [comment]
If you want to add the title...please do.  There is a bit of a puzzle involved. :)

**Comment by Jdew192837** [comment]
@aethelwulffe Can you point me in the right direction, perhaps to a file or things I should be aware of? I have spent quite a bit of time trying to navigate it, and I'm not sure where to look.

Was also having issues with https://github.com/LibreHealthIO/LibreEHR/issues/820, but I think that one is getting overwritten somehow, because it'll display "New" for a second or so. I looked around though, and am stuck there.

A pointer or two would be great! :)

**Comment by aethelwulffe** [comment]
Note:
`<head>` is metadata.
`<header>` is content, but is not the title tag the tabs are looking for.
You would need to add:
`<span class='title' visibility: hidden>XML Editor</span>`

This results in something that will not print or add to the document, but will be picked up by the tab.

**Comment by aethelwulffe** [comment]
That pointed enough?

**Comment by Jdew192837** [comment]
Yeah, hm, I tried that before but it didn't work. Let me see if the visibility:hidden does it @aethelwuffle

**Comment by Jdew192837** [comment]
@aethelwulffe

**Comment by Jdew192837** [comment]
Woops, turns out my I was editing the wrong copy of the code (not the one that was running on my local server) That would explain it hehe @aethelwulffe
