### ISSUE TITLE
Give delete warning a meaningful color

### ISSUE THREAD

**Issue by Trodrige** [LibreHealthIO/LibreEHR#808]
Go to QA Measures->Delete Old Reports(Remove provider Assignments). Let the message “This will….” be in bold red (danger!!!).

**Comment by MigDinny** [comment]
May I stay with this one? I've got a nice solution in mind.

**Comment by teryhill** [comment]
Assigned to @MigDinny

**Comment by Trodrige** [comment]
Assigned to @MigDinny

**Comment by aethelwulffe** [comment]
This is completed.
Closing.
