### ISSUE TITLE
Missing issue form header

### ISSUE THREAD

**Issue by Trodrige** [LibreHealthIO/LibreEHR#819]
Go to Popups->Issues-> click Add Issue. The form has no header. Give it a header. 
Click on Add Encounter, the form has a header. Give "Add issue" its header.

**Comment by Jdew192837** [comment]
I'll fix this @Trodrige

**Comment by Trodrige** [comment]
Assigned to @Jdew192837

**Comment by Jdew192837** [comment]
@aethelwulffe Any guidance or pointers?
