### ISSUE TITLE
Missing "Chart label", "Barcode label" and "Address label" tab titles

### ISSUE THREAD

**Issue by Trodrige** [LibreHealthIO/LibreEHR#820]
Go to Popups->chart label(barcode label, and address label). Label tab as “Chart Label”, “Barcode Label” and "Address label".

**Comment by Jdew192837** [comment]
I'll fix this @Trodrige

**Comment by Trodrige** [comment]
Assigned to @Jdew192837

**Comment by muhammad-mullboccus7** [comment]
May I fix this please?

**Comment by Trodrige** [comment]
Hi Muhammad, sorry Jake is already on this one. Ping him, be can decide to
give you. Otherwise, I'll be adding similar issues later today. Please be
patient, and work on any of those. Thanks

**Comment by Jdew192837** [comment]
@Trodridge Have you looked into these issues to see if they have a possible solution?

**Comment by Jdew192837** [comment]
@trodrige ^

**Comment by Jdew192837** [comment]
@aethelwulffe Any guidance or pointers?

**Comment by Jdew192837** [comment]
Highly stuck on this. Looked around fpdf.php, label.php, everywhere.

Thought I might be able to do it around line 1003 in fpdf.php, but I am actually stuck. I have no idea where I can insert the necessary html.

Tried adding `echo "<span class="title" style="display: none;"><?php echo xlt("Chart Label"); ?></span>";` to label.php, but then it doesn't output the .pdf

I'm very lost, and could use some guidance. @aethelwulffe

**Comment by Trodrige** [comment]
@Jdew192837 I tried doing this too. No success as of now. @teryhill has proposed using a new library for printing PDF.

**Comment by teryhill** [comment]
This is being closed . It will require a rewrite and redesign of the pdf print engine
