### ISSUE TITLE
Duplicated images, fonts and styles (fancybox and glyphicons)

### ISSUE THREAD

**Issue by alpinus4** [LibreHealthIO/LibreEHR#822]
Related task: _LibreHealth EHR Matching Game_

Duplicated files:
- _/library/js/fancybox_  and  _/assets/css/fancybox/_  (duplicated many images and _jquery.fancybox-1.2.6.css_),

**Comment by robbyoconnor** [comment]
The second aren't duplicates

**Comment by robbyoconnor** [comment]
Otherwise good.

**Comment by alpinus4** [comment]
Ok

**Comment by aethelwulffe** [comment]
broken link.  Goes to github...and if corrected to gitlab, you get a 404 (even after signing in).
All the same, this is a valid task claim.

**Comment by teryhill** [comment]
The PR for this was merged.
