### ISSUE TITLE
Print button needs to be prioritized in Reports->Blank Forms->Super Bill

### ISSUE THREAD

**Issue by SoumyadeepJana** [LibreHealthIO/LibreEHR#825]
Currently it is below the form and not highlighted and has an inconsistent UI.

**Comment by MigDinny** [comment]
i can handle this

**Comment by MigDinny** [comment]
Wow, realized now that this issue was already solved.

@SoumyadeepJana when you send a pull request, on its description just write something like Fixes #825

**Comment by aethelwulffe** [comment]
Guys, when SoumyadeepJana posts an issue...I think that is with the intention of fixing it.  When Terry, Tony, Trodrige or myself post an issue, that means we are too dumb to fix it, and we want one of you guys to jump on it. 
NOTE TO TEAM:  We need GCI user tags of some kind.

**Comment by SoumyadeepJana** [comment]
@aethelwulffe  haa haa :D  I had a laugh over this confusion

**Comment by Trodrige** [comment]
@aethelwulffe I can't label nor assign issues here. At least not yet.
