### ISSUE TITLE
UI consistency: replace old date dropdowns with calendar widget

### ISSUE THREAD

**Issue by htuck** [LibreHealthIO/LibreEHR#826]
Poss GCI: Go through the whole project and replace all the old date dropdowns with calendar widgets.  This would be a major UI consistency improvement, to say nothing about the old ones being a lot more work to use.  And they're ugly too.

Per the 1st pic below, one of the old dropdowns is found in the NewRx module found by clicking 'Edit' in  the pt's Prescription widget.  Others will be found in the older code as those dropdowns are from the original OpenEMR that Libre is forked from.

The desired calendar widget is shown in the calendar event panel; pic #2.

![dateddown](https://user-images.githubusercontent.com/8339489/33680549-d6ccb012-da76-11e7-8585-2e62836eccc2.png)

![calwidget](https://user-images.githubusercontent.com/8339489/33680555-d9df294c-da76-11e7-820c-0ee440507411.png)

**Comment by Jdew192837** [comment]
@teryhill Do you think this would be suitable for GCI? I'm up for the challenge. :)

**Comment by aethelwulffe** [comment]
@Jdew192837 
Do it.
GOGOGOGOGOGO...

**Comment by aethelwulffe** [comment]
OK, we merged up the html5 color picker...and the HTML5 date picker function now exists in Firefox Quantum...that being the last browser that didn't have that one function.

**Comment by teryhill** [comment]
@Jdew192837 is this still an active project on your list?

**Comment by aethelwulffe** [comment]
A good number of these are already in the spotlight, and we are converting to browser-based date pickers.  If Jake is on it, then he is on it, but GCI is long done, and this is a well known target item.  Closing...
