### ISSUE TITLE
Colorpicker is too clumsy and is very limited in terms of choice in Admin->Facilities->Add

### ISSUE THREAD

**Issue by SoumyadeepJana** [LibreHealthIO/LibreEHR#829]
Instead of javascript, HTML input type "color" be used as it is more customizable and looks beautiful

Existing
<img width="960" alt="2017-12-07 4" src="https://user-images.githubusercontent.com/16064577/33683268-5423439a-daf0-11e7-928e-6be900cb522d.png">

Proposed
<img width="960" alt="2017-12-07 5" src="https://user-images.githubusercontent.com/16064577/33683279-5af1912c-daf0-11e7-8bd9-484ab111c9ce.png">

**Comment by Jdew192837** [comment]
I can fix this as well @SoumyadeepJana

**Comment by aethelwulffe** [comment]
Colorpicker in html5 is just an input type, and is provided by your browser.
<input id="background-color" type="color" />

**Comment by aethelwulffe** [comment]
Hey, Jdew...
Did you just claim jump @SoumyadeepJana ?
I see your PR....but you need to collaborate a little more closely.  Soumyadeep, go steal one of Jdew's issues now.  😈 
  Kudos to Soumyadeep for the project management and solution design.  That should be worth the creation of a new GCI task if there is not a matching one already.  Good job (both of you actually)!

**Comment by Jdew192837** [comment]
Oh sorry about that. I thought I did that by saying "I can fix this" but I guess I should have waited for a response... Sorry about that :(

**Comment by SoumyadeepJana** [comment]
It's completely fine :) @Jdew192837
