### ISSUE TITLE
Add bootstrap to 'Messages' view components

### ISSUE THREAD

**Issue by Trodrige** [LibreHealthIO/LibreEHR#838]
This is one of many bootstrap tasks. Under the Messages menu, there are various pages. Add bootstrap classes to the elements of these pages. What we want is to make full use of Bootstrap across the entire project.

**Comment by Trodrige** [comment]
Assigned to @Jdew192837

**Comment by Jdew192837** [comment]
Interested in doing this. :) @Trodrige

**Comment by Jdew192837** [comment]
@Trodrige Can you give some specifics about this, Thanks

**Comment by Trodrige** [comment]
@Jdew192837 we want a bootstrap table. The table should have .bordered(must) and .hover classes.

**Comment by aethelwulffe** [comment]
@Jdew192837 get this claimed!

**Comment by Jdew192837** [comment]
What do you mean?
