### ISSUE TITLE
Add Insurance company inactivate

### ISSUE THREAD

**Issue by teryhill** [LibreHealthIO/LibreEHR#848]
Add a Deactivate and Activate to the insurance companies.

![image](https://user-images.githubusercontent.com/4655366/33800740-95fc1988-dd14-11e7-8d9f-932bc089cd60.png)

Active insurance company 

![image](https://user-images.githubusercontent.com/4655366/33800757-ebdda952-dd14-11e7-903f-be7d4323edc9.png)

Inactivated insurance company

![image](https://user-images.githubusercontent.com/4655366/33800762-0e5985f0-dd15-11e7-9b20-cb35ce7579ff.png)

Deactivated Insurance Company

![image](https://user-images.githubusercontent.com/4655366/33800766-4972da74-dd15-11e7-92e7-6c2642d4cbaa.png)

**Comment by aethelwulffe** [comment]
This was merged.
