### ISSUE TITLE
Add new patient Insurance form needs some structure

### ISSUE THREAD

**Issue by Trodrige** [LibreHealthIO/LibreEHR#853]
I just watched this: [video](https://www.youtube.com/watch?v=G9auafGlwQs&feature=push-u&attr_tag=j6VRqPJKYqnl-xqg-6)
I was filled with shame when it reached the 4th minute. Just take a look at the insurance form. The difference is clear with the other categories of forms while adding a new patient. Something has to be done.

**Comment by aethelwulffe** [comment]
@MigDinny You are assigned this issue.
I will send you an invitation to join the project so that you can be "officially" assigned.

**Comment by MigDinny** [comment]
@aethelwulffe what you mean by "project"?

**Comment by aethelwulffe** [comment]
Meaning this repository, and the LibreHealthEHR project.  Joining as a collaborator.  I sent you an invitation.

**Comment by MigDinny** [comment]
@Trodrige @teryhill What exactly needs to be done? What exact screen are we talking about?

**Comment by Trodrige** [comment]
The insurance forms while adding a new patient.

**Comment by MigDinny** [comment]
Check it out, guys.
@Trodrige 
@aethelwulffe

**Comment by aethelwulffe** [comment]
All happy done-done.
