### ISSUE TITLE
Log the reasons statements did not print.

### ISSUE THREAD

**Issue by teryhill** [LibreHealthIO/LibreEHR#858]
In the /sites/default directory is the statement.inc.php. It will currently ignore a statement if the dollar amount is less that the setting in Globals. The code in the statement file to do this is at about line 106 and line 462. There needs to be some way of letting the end user know that statements that they selected did not print for these reasons. Instead of just returning these lines need to have more logic and then return.

  #minimum_amount_due_to _print
  if ($stmt['amount'] <= ($GLOBALS['minimum_amount_to_print']) && $GLOBALS['use_statement_print_exclusion']) return "";
  if ($stmt['statement_print'] == "NO" && $GLOBALS['use_statement_print_exclusion']) return "";

**Comment by MigDinny** [comment]
I'll do this

**Comment by teryhill** [comment]
It will need to be tested.

**Comment by MigDinny** [comment]
But can i have this task?

**Comment by teryhill** [comment]
@MigDinny Yes you can , but you will need to test your solution in the system to make sure it works with out causing any other issues.

**Comment by MigDinny** [comment]
I'll see that on weekend

**Comment by MigDinny** [comment]
Need some help here. What part of the website are we talking about? What is the real goal?

**Comment by teryhill** [comment]
@MigDinny 

In the /sites/default directory is the statement.inc.php. It will currently ignore a statement if the dollar amount is less that the setting in Globals. The code in the statement file to do this is at about line 106 and line 462. There needs to be some way of letting the end user know that statements that they selected did not print for these reasons. Instead of just returning these lines need to have more logic and then return.

**Comment by MigDinny** [comment]
@teryhill Yes, but what part of the website is this? What page?

**Comment by teryhill** [comment]
Fees/posting

**Comment by yehster** [comment]
Here's my attempt to clarify some details... 
From the Screen under menu item Fees SubItem Posting.
After searching, and selecting statements to print...

When the "PDF Download Selected Statements" is clicked, the create_HTML_statement function (which line 106) is a part of are called in a loop from sl_eob_search.php (indirectly through "make_statement" function calls.

The code near line 106, should do something like increment a global counter (statementsBelowThresholdIgnored) before returning the empty string.

Then when all the statements have been printed, there could be a summary statement either included in the printout, or as a popup or something that says "(5) Statements ignored below threshold...)

**Comment by yehster** [comment]
https://github.com/LibreHealthIO/LibreEHR/blob/master/interface/billing/sl_eob_search.php#L262

This is the "loop"

**Comment by yehster** [comment]
Rephrasing "the goal" as well.

Currently, statements which were selected to be printed are sometimes silently ignored based on the "minimum amount to print" global setting.

The goal is to inform the user when this happens.

**Comment by apooravc** [comment]
Working on it.
