### ISSUE TITLE
Can't search patient

### ISSUE THREAD

**Issue by alpinus4** [LibreHealthIO/LibreEHR#860]
Open Patient/Client ==> Add New/Search. Then type some information about any existing patient and click search. And then you see this:

![can t_find_patient](https://user-images.githubusercontent.com/25907897/34017352-bf4c938e-e125-11e7-8a48-0bb6559bf43a.png)

**Comment by teryhill** [comment]
Make sure you enter a date of birth and a valid sex. The fields in red are required. @alpinus4

**Comment by alpinus4** [comment]
I filled all fields in red correctly... @teryhill

**Comment by teryhill** [comment]
I will test on my system but your screen shot has sex as unassigned that is why I said that.

**Comment by teryhill** [comment]
Also can you look at the php error log and see what the error is?

**Comment by teryhill** [comment]
I am seeing it on my system. I guess we never try to find a patient like that. We just use the finder. Good catch.

**Comment by alpinus4** [comment]
No matter what I enter to fields, I see the same result...
You think about this file? I'm not hmm... very experienced with PHP :/
[error.log](https://github.com/LibreHealthIO/LibreEHR/files/1561022/error.log)

**Comment by alpinus4** [comment]
Thanks :)

**Comment by teryhill** [comment]
@aethelwulffe can you check this on the mips site you have?

**Comment by aethelwulffe** [comment]
Sorry Tony closed that, I can still check some stuff out of it.
I am going to use something close to the original (or your version), and move the MIPS related version to it's own module directory.
  I will have the PR up as soon as I can, and test both sets of functionality tonight.

**Comment by aethelwulffe** [comment]
Now MIPS reporting is broken, but at least this is fixed.  We will be taking care of that next.
