### ISSUE TITLE
Can't close popup " Search/Add Insurer" after clicking search button

### ISSUE THREAD

**Issue by alpinus4** [LibreHealthIO/LibreEHR#861]
Go to Patient/Client ==> Add New/Search ==> Insurance ==> click "Search/Add Insurer" . Then If you click search without filling any fields you can't close the popup. Missing cancel button.

![when_didn t_find_insurer](https://user-images.githubusercontent.com/25907897/34019025-1e0a64e4-e12d-11e7-9be8-2c2044810cde.png)

**Comment by Trodrige** [comment]
@alpinus4 isn't this same as #852 ?

**Comment by alpinus4** [comment]
@Trodrige These are different bugs. This issue is about missing button and #852 is about strange position of popup.... Two different troubles, similar, but not identical....

**Comment by MigDinny** [comment]
Fixed with #870 .

**Comment by teryhill** [comment]
MigDinny stated it was fixed with #870
