### ISSUE TITLE
Everything freezes when try to resize the tab from the far right side of the far right tab

### ISSUE THREAD

**Issue by alpinus4** [LibreHealthIO/LibreEHR#862]
Refresh the site. Drag the right border of the tab. If there two tabs, drag the right border of the right tab. But do it, when you have this cursor.
![resize_cursor](https://user-images.githubusercontent.com/25907897/34019297-70df4ea4-e12e-11e7-96c6-3e66e3075943.png)

Then everything freezes and you still have resize cursor.

**Comment by pri2si17-1997** [comment]
@alpinus4 I am not able to reproduce your error. Please provide some more details. Else it is working fine on my system.

**Comment by alpinus4** [comment]
@pri2si17-1997 
Look at this: https://www.dropbox.com/s/eanu2fc0bzq770v/ehr_bug.avi?dl=0

**Comment by pri2si17-1997** [comment]
@alpinus4 I still can't reproduce it. Let others check it.
@Trodrige @aethelwulffe @teryhill

**Comment by teryhill** [comment]
@pri2si17-1997  I reproduced it. Do the drag on the right side of the screen. You have to refresh to get control back.

**Comment by abhigyank** [comment]
Het, I am able to reproduce the bug. One observation, the bug occurs when we resize the tab from the far right side of the far right tab directly, if we first resize anyother tab first in the screen and then do the above then the bug doesn't occurs. 
Any ideas how to approach this?
