### ISSUE TITLE
Globals should default to SQL Admin disabled

### ISSUE THREAD

**Issue by tmccormi** [LibreHealthIO/LibreEHR#865]
Since we do not by default install phpmyadmin or any other tool, this should be off by default

![adminlink](https://user-images.githubusercontent.com/285835/34021693-11ab7d10-e0f0-11e7-874d-dd26e01f96ce.png)

**Comment by tmccormi** [comment]
Also - change this hardcoded line in library/globals.inc.php to be an editable configuration on the SYSTEM section

80:  $sql_admin_tool_url  = 'http://localhost/phpmyadmin';

**Comment by teryhill** [comment]
Should the bug label be removed since this was actually an incomplete fix from the removal of PHPmyadmin

**Comment by Jdew192837** [comment]
@tmccormi Is this good?

**Comment by tmccormi** [comment]
An incomplete fix, I would consider a bug.  Even If I'm the one that did it :-)
