### ISSUE TITLE
Wrong URL Name in PQRS_settings_config.sql

### ISSUE THREAD

**Issue by Jdew192837** [LibreHealthIO/LibreEHR#875]
In line 243 of PQRS_settings_config.sql, it should be
`'https://your_web_site.com/libreehr/patients'`
instead of
`'https://your_web_site.com/openemr/patients'`

Originally reported by @aethelwulffe  sometime.

I'd be glad to fix this and other instances if needed @aethelwulffe @teryhill.

Let me know what you think.

**Comment by Jdew192837** [comment]
@aethelwulffe Do you reckon I fix this?

**Comment by aethelwulffe** [comment]
Do it!
