### ISSUE TITLE
Can't edit history

### ISSUE THREAD

**Issue by Kachachan** [LibreHealthIO/LibreEHR#881]
**Steps to Reproduce**
1. `Patient/Client` --> `Add New/Search` --> select any patient
2. Click on History
3. Click on Edit.
4. Try and change Patient's history, observe errors.
![libreehr8](https://user-images.githubusercontent.com/6000894/34308291-4495ea90-e77f-11e7-90ed-b5e7095bcac4.png)

**Reproduction Rate**: 5/5

**System Specs** LibreHealth EHR v2.0.0, Chrome Version 63.0.3239.84 (Official Build) (64-bit), Windows 10 Version 10.0.14393 Build 14393

**Comment by aethelwulffe** [comment]
GCI bug found. BUT is not reproducible on the main demo here:  https://ehr.librehealth.io/interface/login/login.php?site=default

Assuming that this can be reproduced elsewhere with a valid updated database: 
Suggested solutions:
1.  Simply remove hard-coded fields that do not exist in database for layout.  
2.  Ensure that it only tries to save those that exist.

**Comment by prabhakarpd7284** [comment]
@teryhill 
Is above approach not fine ? Please respond.

**Comment by teryhill** [comment]
I would remove usertext11 from the code.

**Comment by aethelwulffe** [comment]
Yeah, I made some additional comments in the review, but it seems the cleanest approach is removal of the field completely.  It does not appear to be an actual utilized standard field.  Formerly, I think it was used in the patient portal, though I would reference Terry on that issue.

Thank you for your work!
