### ISSUE TITLE
Pressing Lock and then Refresh on a UI Element Creates Two Instances

### ISSUE THREAD

**Issue by Kachachan** [LibreHealthIO/LibreEHR#882]
**Steps to Reproduce**
1. Click on the 'Lock' on one of the UI elements. This hides the element.
![libreehr9](https://user-images.githubusercontent.com/6000894/34308854-ca2c610a-e781-11e7-8cfb-1fedb470aef8.png)

2. Whilst the element is hidden, click on the 'refresh' button. Observe two instances of the same element being created.
![libreehr10](https://user-images.githubusercontent.com/6000894/34308885-dfda71c2-e781-11e7-8cbe-781d4a513512.png)

Seems like if you open the hidden one, the opened one gets replaced, though. So in the end only one instance of the element will be displayed anyway. Minor UI bug.

**Reproduction Rate**: 5/5

System Specs LibreHealth EHR v2.0.0, Chrome Version 63.0.3239.84 (Official Build) (64-bit), Windows 10 Version 10.0.14393 Build 14393

**Comment by apooravc** [comment]
In terms of element UI, what is the use of having refresh icon when an element is locked or hidden? Isn't that an extra thing to have in the hidden state?  Besides having unlock and close. @teryhill @aethelwulffe

**Comment by teryhill** [comment]
@apooravc goodpoint. That would fix this error.

**Comment by apooravc** [comment]
I can do it if @Kachachan has no issues with that.
