### ISSUE TITLE
Bootstrap on Encounter's Pages

### ISSUE THREAD

**Issue by MigDinny** [LibreHealthIO/LibreEHR#886]
Some elements have bootstrap but there are some without bootstrap.

- New Encounter form

- Past Encounter List (and inside "tabs")

**For example:**

![image](https://user-images.githubusercontent.com/6632800/34323895-2aa77e48-e854-11e7-858b-b03f399282a0.png)
_Dropdown inputs_

![image](https://user-images.githubusercontent.com/6632800/34323898-3fd57e5a-e854-11e7-8468-1fe3912af42d.png)
_All those inputs_

And many other cases.
I can do this but I need approval to start working @Trodrige @teryhill 

**PS:** I'm in the proccess of learning bootstrap and I can't ensure I'll be able to bootstrap all those inputs without any problem, but I'll do my best.

**Comment by MigDinny** [comment]
@Trodrige 
I would like to add bootstrap to some places but it has been a nightmare for me.

Look at this:
![image](https://user-images.githubusercontent.com/6632800/34370071-fb282f98-eab8-11e7-9891-de6eb0c33672.png)

Basically, adding bootstrap to some elements makes them having "width:100%" and "display:block" which creates that mess. I was thinking about adding bootstrap here but it's impossible because it's not dynamic. I don't know why bootstrap classes mess with displays and sizes... Anyway, do you have any suggestion? As I've told you on the other PR, bootstrap isn't a good idea...

**Comment by teryhill** [comment]
Jdew is already working on this and other forms.

**Comment by teryhill** [comment]
This is covered under issue 876 . Duplicate work closing this issue.
