### ISSUE TITLE
Unable to add a name for a new Procedure Provider

### ISSUE THREAD

**Issue by sanjaykarthic** [LibreHealthIO/LibreEHR#891]
Click on Procedure->Provider->New 
'Name' field is a drop down, but there are no values in the drop down. is this something to come from the database. also if i just go ahead and submit, the entry is getting created. pls refer screenshot below.
is it allowed to create provider without any name? also is 'Name' a drop down list ?

![librehealth-new-procedure-provider](https://user-images.githubusercontent.com/34680990/34354841-21f3e408-ea57-11e7-8bd0-16c6fa38c5ac.png)

**Comment by pri2si17-1997** [comment]
@teryhill @aethelwulffe This is not a bug IMO. What you say?

**Comment by teryhill** [comment]
It is a training issue. There is a process for setting that up.

**Comment by pri2si17-1997** [comment]
Yes.

**Comment by aethelwulffe** [comment]
Agree with Priyanshu, not a bug....good try though! @sanjaykarthic
