### ISSUE TITLE
Images not in use.

### ISSUE THREAD

**Issue by phanindra789** [LibreHealthIO/LibreEHR#902]
1. https://github.com/LibreHealthIO/LibreEHR/blob/master/images/approve_patient.png
2. https://github.com/LibreHealthIO/LibreEHR/blob/master/images/blankbtn.gif
3. https://github.com/LibreHealthIO/LibreEHR/blob/master/images/CMS_logo0.png
4. https://github.com/LibreHealthIO/LibreEHR/blob/master/images/fee.png
5. https://github.com/LibreHealthIO/LibreEHR/blob/master/images/file2.png
6. https://github.com/LibreHealthIO/LibreEHR/blob/master/images/inventory.png
7. https://github.com/LibreHealthIO/LibreEHR/blob/master/images/leftbtn.gif   (Available in assets)
8. https://github.com/LibreHealthIO/LibreEHR/blob/master/images/messages.png
9. https://github.com/LibreHealthIO/LibreEHR/blob/master/images/module.png
10. https://github.com/LibreHealthIO/LibreEHR/blob/master/images/pfb.png
11. https://github.com/LibreHealthIO/LibreEHR/blob/master/images/phpinfo.jpg
12. https://github.com/LibreHealthIO/LibreEHR/blob/master/images/procedures.png
13. https://github.com/LibreHealthIO/LibreEHR/blob/master/images/rightbtn.gif  (Available in assets)
14. https://github.com/LibreHealthIO/LibreEHR/blob/master/images/space.gif 
15. https://github.com/LibreHealthIO/LibreEHR/blob/master/images/upbtn.gif

**Comment by phanindra789** [comment]
@teryhill  @aethelwulffe 16 out of 44 images are not used anywhere.

**Comment by teryhill** [comment]
CMS_logo0 needs to be left. It is part of the mips module and the program that uses it is being re-worked. correct @aethelwulffe

**Comment by aethelwulffe** [comment]
True. @teryhill 
Leave the CMS logo.
I think the rest are good to leave (except the ones in assets.  Moving the rest to /assets/images might be good.
  Aside from that, there is a possibility of us adding in an icon-based menu at some point, at least for quick-pick buttons.  Even so, any images that are used should be generated natively with our own look.

**Comment by abhigyank** [comment]
I am working on this and will put a PR soon.

**Comment by aethelwulffe** [comment]
@abhigyank Thanks man!
Welcome to the team!
-Art Eaton

**Comment by abhigyank** [comment]
@aethelwulffe Should these images be removed from the repository from the images folder, or should they just be moved to /assets/images folder?

**Comment by aethelwulffe** [comment]
After verification, dump them.  As noted above, at least one of the files are in use.  That image belongs to a module though, and should be moved to that module's assets.
