### ISSUE TITLE
Issue while installing setup

### ISSUE THREAD

**Issue by pri2si17-1997** [LibreHealthIO/LibreEHR#907]
Hello @teryhill @aethelwulffe 

As stated by @alpinus4, there is issue while installing it. 

Attached is screenshot of the same : 
![error_install](https://user-images.githubusercontent.com/12952169/34468939-9978bc24-ef39-11e7-8be6-0f75ede80933.png)

I'm working on it.

**Comment by yehster** [comment]
https://github.com/LibreHealthIO/LibreEHR/blame/2d9827430c98521a3cdd99b2c109959c5f84397d/sql/database.sql#L2406


This is the line that is causing the problem… It is trying to create a new row in the database. Count up how many items there are in the lists…

Now this is the line that says which columns in the database table to map to each of the rows… Note how many columns are specified
https://github.com/LibreHealthIO/LibreEHR/blame/2d9827430c98521a3cdd99b2c109959c5f84397d/sql/database.sql#L2362

My explanation in GCI chat about what is happening

**Comment by pri2si17-1997** [comment]
Got that @yehster . Thanks :slightly_smiling_face:

**Comment by teryhill** [comment]
Code base fixed. Issue resolved
