### ISSUE TITLE
Popups ==> Refer, not found (err. 404)

### ISSUE THREAD

**Issue by alpinus4** [LibreHealthIO/LibreEHR#937]
## Steps to reproduce

1. Go to _Popups_ ==> _Refer_

![](https://user-images.githubusercontent.com/25907897/34645376-d4c70a68-f34b-11e7-8829-8ccc357c315a.jpg)

2. See error

![error](https://user-images.githubusercontent.com/25907897/34645378-e293f476-f34b-11e7-9e03-c2f86924759c.jpg)

Found it also on https://ehr.librehealth.io/

I'm using Wamp, Firefox 57.0.4, Windows 10 ver. 1709

**Comment by teryhill** [comment]
I think that was removed in one of the slash and burn episodes. @aethelwulffe  or @tmccormi  may be able to answer this

**Comment by alpinus4** [comment]
@aethelwulffe @tmccormi What should I do with it?

**Comment by aethelwulffe** [comment]
@alpinus4 I am looking into it...
