### ISSUE TITLE
Patient Documents not displaying.

### ISSUE THREAD

**Issue by teryhill** [LibreHealthIO/LibreEHR#939]
This is what the screen should look like

![image](https://user-images.githubusercontent.com/4655366/34685717-4c5525fc-f477-11e7-9773-d97651c715d6.png)

This is what it looks like

![image](https://user-images.githubusercontent.com/4655366/34685468-6aad5958-f476-11e7-9ca6-eb1694547ff6.png)

Get to it from documents here.

![image](https://user-images.githubusercontent.com/4655366/34685917-e79e741e-f477-11e7-9d6d-e4e68d12e13f.png)

**Comment by MigDinny** [comment]
I'll see it

**Comment by pri2si17-1997** [comment]
Hello @teryhill @MigDinny this is what php error log show : 

> PHP Fatal error:  Uncaught Error: Call to a member function get_id() on null in /var/www/html/LibreEHR/templates/documents/general_view.php:108\nStack trace:\n#0 /var/www/html/LibreEHR/controllers/C_Document.class.php(401): require_once()\n#1 /var/www/html/LibreEHR/library/classes/Controller.class.php(137): C_Document->view_action('1', '2')\n#2 /var/www/html/LibreEHR/controller.php(6): Controller->act(Array)\n#3 {main}\n  thrown in /var/www/html/LibreEHR/templates/documents/general_view.php on line 108, referer: http://localhost/LibreEHR/controller.php?document&list&patient_id=1

**Comment by teryhill** [comment]
Yes @pri2si17-1997  that is what I am getting. I suspect that the information is not being passed as a result of the smarty template removal.

**Comment by aethelwulffe** [comment]
Oopsie!

**Comment by aethelwulffe** [comment]
CCR

 <?php if(($this->file->get_ccr_type($file->get_id()=="CCR") &&

**Comment by MigDinny** [comment]
@aethelwulffe what do you mean ?

**Comment by aethelwulffe** [comment]
You got it.

**Comment by aethelwulffe** [comment]
file->get_ccr_type($this->file->get_id()=="CCR")

**Comment by 2208Abhinav** [comment]
When I click on **Documents**
I get this 
![screenshot from 2018-01-20 22-18-55](https://user-images.githubusercontent.com/30211121/35182858-61c7a45c-fe02-11e7-8b85-61ba3a43d15c.png)

**Comment by MigDinny** [comment]
@2208Abhinav it was fixed already >> #940

**Comment by 2208Abhinav** [comment]
Is the result I am getting right ?

**Comment by MigDinny** [comment]
@2208Abhinav Yes, I think so

**Comment by 2208Abhinav** [comment]
Okay, Thank You

**Comment by teryhill** [comment]
Pr was merged
