### ISSUE TITLE
MigDinny fix this please

### ISSUE THREAD

**Issue by teryhill** [LibreHealthIO/LibreEHR#941]
missing images for this pr 

![image](https://user-images.githubusercontent.com/4655366/34701308-8816adde-f4b5-11e7-829c-547f9c4ccc20.png)

The images are 

![image](https://user-images.githubusercontent.com/4655366/34701322-98e67608-f4b5-11e7-9c3d-19319f70c8e6.png)

**Comment by MigDinny** [comment]
@teryhill check this out!

**Comment by aethelwulffe** [comment]
This issue was merged.
Bugfix for Miguel (his own bug, but who wants to get all technical?).  Closing this.
