### ISSUE TITLE
Missing logo in printable versions of reports

### ISSUE THREAD

**Issue by alpinus4** [LibreHealthIO/LibreEHR#962]
# Steps to reproduce:
**1.** Go to patient screen and click _Report_

![](https://user-images.githubusercontent.com/25907897/35188011-4d7d96ba-fe2e-11e7-81ba-073f1d283ffe.jpg)

**2.** Click 3, 4, 5 or  6  _Generate report_ button
![](https://user-images.githubusercontent.com/25907897/35188140-cc2fec86-fe30-11e7-8839-1fc89a7ae288.jpg)

**3.** Go to _Printable Version_ of report
![](https://user-images.githubusercontent.com/25907897/35188146-dd91e13c-fe30-11e7-9f5d-046a53a527e8.jpg)

**4.** See missing image
![](https://user-images.githubusercontent.com/25907897/35188139-c8653818-fe30-11e7-8a07-44d9b95e0064.jpg)

Browser: Firefox 57.0.4
OS: Windows 10 ver. 1709

**Comment by teryhill** [comment]
Most likely someone moved the images with out changing all the code.

**Comment by teryhill** [comment]
$practice_logo = "$OE_SITE_DIR/images/practice_logo.png";

Yep the code needs to be changed

**Comment by teryhill** [comment]
Looked and the images are still in the sites/images directory so missing images is not the issue. It appears that the code is seeing that an image exists but it cannot properly display it.

**Comment by 2208Abhinav** [comment]
I solved this problem.
Now the page looks like this
![screenshot from 2018-01-21 18-15-38](https://user-images.githubusercontent.com/30211121/35191759-4e187948-fea9-11e7-9820-25c0bf9c7671.png)

**Comment by 2208Abhinav** [comment]
I have pulled a request #960  for this including issue #949

**Comment by teryhill** [comment]
Pr merged
