### ISSUE TITLE
Error when trying to save changes in patient history

### ISSUE THREAD

**Issue by alpinus4** [LibreHealthIO/LibreEHR#964]
# Steps to reproduce:

1. Go to patient screen and click _History_

![](https://user-images.githubusercontent.com/25907897/35192479-a89d60ce-fe93-11e7-89e8-b6bf25507161.jpg)

2. Click _Edit

![](https://user-images.githubusercontent.com/25907897/35192504-4493939a-fe94-11e7-8cfc-4466d0243056.jpg)
_ button

3. Make some changes and save

![](https://user-images.githubusercontent.com/25907897/35192519-9a939c90-fe94-11e7-9550-5fd5d4bbdfa1.jpg)

4. See error:

![](https://user-images.githubusercontent.com/25907897/35192527-aeb1a528-fe94-11e7-8764-cdcd5f2c9b43.jpg)

I haven't found this bug in Demo: https://ehr.librehealth.io/interface/login/login.php?site=default

Browser: Firefox 57.0.4 and Chrome 63.0.3239.132 
OS: Windows 10 ver. 1709

**Comment by 2208Abhinav** [comment]
How to login at 
https://ehr.librehealth.io/interface/login/login.php?site=default

**Comment by alpinus4** [comment]
Look there: https://librehealth.io/demos/ @2208Abhinav

**Comment by MigDinny** [comment]
"usertext11" field doesn't exist in the database. Tried to update my database using sql_upgrade.php but didn't work. A database fix is probably required, or it shouldn't be there... I'll take a look at this anyway in a few hours

**Comment by alpinus4** [comment]
Sorry folks.... I haven't noticed that the same issue already exist
