### ISSUE TITLE
Admin -> Lists start at "language" instead of at the top of the list

### ISSUE THREAD

**Issue by tmccormi** [LibreHealthIO/LibreEHR#966]
The selection of the list, for some reason has always started with Language, instead of the Alphabetical top of the list

This is a easy task.
Current:
![current-default](https://user-images.githubusercontent.com/285835/35410721-26003430-01cb-11e8-9658-b1f384d12915.png)

Proposed:
![alphabetical-top](https://user-images.githubusercontent.com/285835/35410731-30aba93c-01cb-11e8-9df3-f8d15f2ac3f9.png)

**Comment by tmccormi** [comment]
Extra points for a search as you type list selector :-)

**Comment by aethelwulffe** [comment]
TEN!  Ten extra points for a type-ahead selector!

**Comment by teryhill** [comment]
@Perseus it should display the first item in the list. I am not sure what @aethelwulffe  is asking for on the type ahead cause I have always just used the first letter of a known list.

**Comment by Perseus** [comment]
Great. I'll do a PR first thing tomorrow morning with that fix!

**Comment by tmccormi** [comment]
type ahead filters the list as you type each letter.  it can be 'sequential' as in the order of the list item or "contains" as in filter the list based on anything the matches what has been typed so far.   We need the second because the list names are not consistent in anyway.   For instance try and find the list that has the "rooms" in it without scrolling the whole thing...

**Comment by Perseus** [comment]
@tmccormi Would a JS library to make that happen be allowed or do I need to make a native solution?

**Comment by teryhill** [comment]
@Perseus Look in the assets directory and see if there is an asset there that you can use.

**Comment by Perseus** [comment]
@teryhill I looked around but was not able to find anything that would be useful. The library I was proposing is this: https://selectize.github.io/selectize.js/

**Comment by Perseus** [comment]
@teryhill I looked around but was unable to find anything that would be useful. The library that I was proposing is this : https://selectize.github.io/selectize.js/

**Comment by teryhill** [comment]
Okay use it.

**Comment by Perseus** [comment]
Is there any intention to eventually update the jQuery versions? The edit list page is currently using 1.2 which is quite outdated and hard to use current libraries in

**Comment by aethelwulffe** [comment]
@Perseus 
Check out the /library/headers.inc.php file.  We invoke that by calling globals.php, then using the directory variables there to call this file, then invoke the functions to call whatever assets are required as an array.
  Previously, there were assets spammed all over the place.  As we migrate to a central directory for similar 3rd party assets, and pull out native features or third-party applications and cram them into /modules, we refactor the calls to them as well as modify the features to use the latest versions.
When we are sure that nothing remains that calls an asset in an old location (example: /libraries/js), we delete that asset from the old location, retaining the copy in the new.   Once we are sure that nothing requires an old version anymore, we delete that old version asset completely.

It currently appears we have a huge number of such things.  We do.  The truth is though that we have already cleaned up even more than currently exist!  We are a bit of a mess.

**Comment by Perseus** [comment]
@aethelwulffe Could I try and use an updated version of jquery on the edit list page and see if anything breaks? If not, I could add the type-ahead selector pretty easily!

**Comment by teryhill** [comment]
@Perseus Yes please do. Upgrade the Jquery

**Comment by aethelwulffe** [comment]
Do it!  I think we have a named copy and a general jquery.js file that is supposed to be whatever the latest is...

**Comment by Perseus** [comment]
@teryhill The PR (980) made to fix this has been merged. I think it should be closed now?

**Comment by teryhill** [comment]
Pr Merged Closing issue Thanks @Perseus
