### ISSUE TITLE
Order form transcription verification

### ISSUE THREAD

**Issue by htuck** [LibreHealthIO/LibreEHR#975]
I can't quote the regs, but in the paper medical records world, when a provider writes an order (for meds, some referral or procedure) it must be 'transcribed' by office staff, i.e., the paperwork fulfilling the order must be completed and sent off.  Then the action that was performed to fulfil that order needs to be recorded along with a legally verifiable signature of the person who carried it out  (e.g., "referral sent - HTuck [date]") 

It seems that transcribing a medication order would have to be a separate workflow not addressed by these transcription processes; will look at meds elsewhere and only non-med orders here.

It may not be the only way to do this, but adding an e-sign button to an Order form specifically for the order transcription seems adequate- it has the legal e-sig and a place to put a note of how the order was carried out.

One other requirement of this issue is the ability to periodically audit all orders for ones that still have not been transcribed.  Libre does have a Procedures report (menu: Reports/ Procedures/ Pending Res in the pic)  which looks like it'd work but we'd need to make sure it was catching these new types of orders- last I checked it only saw the old- style Procedure Orders if they're configured in the Procedures module.

![procpending](https://user-images.githubusercontent.com/8339489/35645753-be9ad758-0681-11e8-80d0-c90d99a0fb07.png)

**Comment by teryhill** [comment]
@htuck I added some fields to the encounters report a few years ago, to allow the user to see unsigned reports. This may need to be refined to get an accurate listing.

![image](https://user-images.githubusercontent.com/4655366/35646199-6ec069bc-069c-11e8-98c2-288fe3e7c96e.png)

**Comment by htuck** [comment]
that's v cool, @teryhill , it could take care of the need for auditing.
If a form has 2 e-sig buttons on it will it show that just one is unsigned and its identifier?

**Comment by htuck** [comment]
I mean... would it be difficult to make it show which were not signed?

**Comment by htuck** [comment]
Ok, my last thoughts on this for the mockup version for the video.

First we have to decide the 'Transcribed' e-sig button is the way to do it.  That's my fave solution anyway, but "I am but an egg" (M.V. Smith)

Then, if we can get even a non- functional 'Transcribed' button in the row of buttons that apply to the Order form (arrow), I believe that's all I need to get going on the Orders vid.

In future, we (you) can build in that clever visual cue of changing color when it's been e-sig'd and until then I think the fluid nature of the Libre project will excuse the video not showing all the pt and Order data fields what they're sposed to.  Especially if I tell the viewers those fields will change.  Smoke and mirrors, don't you know.

![encord](https://user-images.githubusercontent.com/8339489/35658145-be94445a-06b4-11e8-87d2-b01f7bb6c52d.png)

**Comment by teryhill** [comment]
I have a requisition printout in the works I will try to get a copy of it to you @htuck

**Comment by htuck** [comment]
Looks like the coding changes are developing a 2 channel execution process for provider orders: 
	1 a provider order which doesn't need to be processed as a transaction but can be transmitted (whatever that actually does) directly from the encounter
	2 a provider order which needs to be manually processed as a transaction

To prevent lack of accountability on these provider orders, I think we gotta have the transcriptionist review and e-sign ALL provider orders, whether printed or transmitted from the Prov Order form, or manually executed by the transcriptionist.  Else it'll be like a code block w/ 2 exit points.

To cover these 2 possibilities I think the 'Report - Encounters' needs to show if a provider order form has been 1) NOT e-sig'd by provider OR 2) NOT e-sig'd as transcribed by transcriptist OR 3) has been transmitted.

**Comment by htuck** [comment]
Ok, I'd like to post my findings on this and the basic procedure I'm using for the tutorial.
Per CMS Pub 100-08 Medicare Program Integrity, 3/3.3.2.4 - Signature Requirements, EXCEPTION 2:"...The rules in 42 CFR 410 and Pub.100-02 chapter 15, §80.6.1 state that if the order for the clinical diagnostic test is unsigned, there must be medical documentation (e.g., a progress note) by the treating physician that he/she intended the clinical diagnostic test be performed. This documentation showing the intent that the test be performed must be authenticated by the author via a handwritten or electronic signature...."

The upshot of all this is that, if the provider makes an entry in a SOAP note for an encounter, and indicates the intention to order the procedure, and e-signs that SOAP note, that is legal documentation of the order.  That way, the e-sig on the encounter's 'Order Form' (aka 'Procedure Order' form) can be used by the transcriptionist to legally document the order has been executed.

Voila, no code changes needed for this requirement.

**Comment by htuck** [comment]
and so I will close this issue.
