### ISSUE TITLE
View Facility Specific User Information

### ISSUE THREAD

**Issue by aethelwulffe** [LibreHealthIO/LibreEHR#982]
Feature is broken.
Administration/Users/View Facility Specific User Information
Tab results [UNKNOWN]

**Comment by teryhill** [comment]
Fix on the way

**Comment by aethelwulffe** [comment]
Tested, approved with screenshot.
It is a one-character bug-fix.  I suggest we go all maverick and merge...  @tmccormi  ?

**Comment by aethelwulffe** [comment]
This is merged.
Thank you Terry.
